### ISSUE TITLE
POST requests do not go through ESPv2

### ISSUE THREAD

**Issue by malemo** [GoogleCloudPlatform/esp-v2#121]
My iOS app makes POST requests to Google Cloud Run container which hosts my Django Rest Framework Project.

I've set up public ESP(deployed in Cloud Run with proper service account)  to serve as a gateway for private Cloud Run Container. In ESP I'm using Firebase Security Definition (which I've deactivated for the testing, because it works and it's not the point of the test)

All GET requests to ESP work fine: they successfully get routed to Cloud Run Container (for example when I request non existent /hello at www.example.com/hello, I get Django Debug 404)

However, for some reason, POST requests are not routed by ESP (for example I'm trying to access existing /upload at www.example.com/upload I get standard 404). When I try POST request url in the browser I get this "Path does not match any requirement URI template." error message. Googling that message has led me to this GitHub. May be somebody can help me figure it out.

All POST requests work fine if sent directly to Cloud Run Container

I've tried disabling Django csrf, setting APPEND_SLASH to false, nothing seems to work. All POST requests result in 404.

All testing done with Postman.

**Comment by qiwzhang** [comment]
Could you post your OpenAPI spec here?

The config ESP used is generated from Google ServiceManagement based on your OpenAPI sepc. 
You can get it by CLI "gcloud endpoints configs describe CONFIG_ID".  Could you double check to see if it has POST http method in http rules

**Comment by malemo** [comment]
> Could you post your OpenAPI spec here?
> 
> The config ESP used is generated from Google ServiceManagement based on your OpenAPI sepc.
> You can get it by CLI "gcloud endpoints configs describe CONFIG_ID". Could you double check to see if it has POST http method in http rules

Thanks
Issue resolved
