### ISSUE TITLE
[New Feature] User TLS authentication

### ISSUE THREAD

**Issue by TuSKan** [GoogleCloudPlatform/esp-v2#149]
What I am trying to do is a End User Certificate Authentication like this:

1. Request from user comes in to Ingress Gateway
2. Ingress Gateway checks certificate fingerprint against a whitelist
    2.1. If fingerprint exists in whitelist (populated by a secret), request enters the cluster
    2.2. If fingerprint doesn’t exist, request is rejected

**I found this filter on Envoy [envoy.filters.network.client_ssl_auth](https://www.google.com/url?q=https%3A%2F%2Fwww.envoyproxy.io%2Fdocs%2Fenvoy%2Flatest%2Fconfiguration%2Flisteners%2Fnetwork_filters%2Fclient_ssl_auth_filter&sa=D&sntz=1&usg=AFQjCNHILPbwUG7mO6EF3HKcdsM1v7J_7g)**

I will really appreciate to have this envoy configuration option on ESPv2.

I could help if have some guidance

**Comment by JLXIA** [comment]
TuSkan@:
     It would be great if you can contribute to this OOP. 

You can refer to DEVELOPER.md for developement guidance. 

Let me know if any issues.

**Comment by qiwzhang** [comment]
If ESPv2 is deployed in Cloud Run (managed),  TLS is terminated by Cloud Run,  not by ESPv2.  This only work when TLS is terminated by ESPv2.   For example, when deploying in GKE, or Cloud Run in Anthos.

**Comment by qiwzhang** [comment]
We could add a flag --client_ssl_auth_server_address.  ESPv2 will
* create a cluster to this server address
* add the network.client_ssl_auth filter to the network filter chain before http_conntion_manager.

**Comment by TuSKan** [comment]
> If ESPv2 is deployed in Cloud Run (managed), TLS is terminated by Cloud Run, not by ESPv2. This only works when TLS is terminated by ESPv2. For example, when deploying in GKE, or Cloud Run in Anthos.

I just have Cloud Run to use right now. You are saying that is **not possible** to do it on Cloud Run?

**Comment by TuSKan** [comment]
> We could add a flag --client_ssl_auth_server_address. ESPv2 will
> 
> * create a cluster to this server address
> * add the network.client_ssl_auth filter to the network filter chain before http_conntion_manager.

There is a flag named `ssl_client_cert_path` that maybe confuses with `client_ssl_auth_server_address` .
What do you think to maintain the same pattern starting with `ssl` like `ssl_client_auth_server_address`  or just `ssl_client_auth`?

**Comment by JLXIA** [comment]
If you run your service on managed Cloud Run, there is another embeded Envoy within Cloud Run, which handles the TLS with clients.  So, the path is like:
   clients -> Cloud Run Envoy -> ESPv2 -> Backend Server. 

The two in the middle are in same Cloud Run instance.

**Comment by qiwzhang** [comment]
For Managed Cloud Run,  TLS is terminated by Cloud Run Envoy that we don't have control over. 
For flag name, `ssl_client_auth_server_address` sound better.

**Comment by TuSKan** [comment]
Guys, this product  is amazing, much easier to setup than competitors (ApiGee, etc...), you are doing a great job!
But unfortunately, I just have Cloud RUN available to use right now, so I won’t be able to contribute to this feature this time.
Thank you very much for interacting with me.
