### ISSUE TITLE
Incorrect padding for X-Endpoint-API-UserInfo header

### ISSUE THREAD

**Issue by maroux** [GoogleCloudPlatform/esp-v2#178]
Per [docs](https://cloud.google.com/endpoints/docs/openapi/migrate-to-esp-v2#handle-jwt), the `X-Endpoint-API-UserInfo` header is supposed to be base64 encoded list of the original claims. However, an example value I received just now is of length 354 - which is missing `==` at the end.

Confirmed by using Python `base64.decodebytes(user_info_encoded.encode()).decode()` to decode which fails unless I add `==`.

**Comment by nareddyt** [comment]
This is a documentation error. It is base64url encoded, not base64 encoded.

https://stackoverflow.com/a/55389212/4402434

> The problem with Base64 is that it contains the characters +, /, and =, which have a reserved meaning in some filesystem names and URLs. So base64url solves this by replacing + with - and / with _. The trailing padding character = can be eliminated when not needed ...

So you need to use a base64url decoder in python.

**Comment by nareddyt** [comment]
I will update the documentation with this clarification. Thanks for reporting.

**Comment by maroux** [comment]
Okay, looks like the RFC is [unclear](https://tools.ietf.org/html/rfc4648#section-3.2) about whether padding is necessary or not for `base64url`. In any case, looks like Python's base64url decoder lacks support for relaxed checking of padding. I'll just work around this in my code. Thanks!

**Comment by nareddyt** [comment]
Should be updated soon.

**Comment by chrisfrank** [comment]
Hi there. I ran into this same issue today decoding the UserInfo header in Python 3.8 on GKE. It looks like both `base64.b64decode(token)` and `base64.urlsafe_decode(token)` are raising an "Incorrect padding" error. I can work around it by adding an arbitrary `===` suffix to the token value, but I don't feel great about sending that to production.

Any chance ESPv2 will be updated to include padding in the UserInfo token?

(Also, this is the _only_ issue we've had so far moving from ESPv1 to v2. Thanks for the smooth upgrade path, and the amazing new routing that `x-google-backend` makes possible!)

**Comment by TAOXUY** [comment]
Just search around, I think this is a common issue in python base64 url decoding and the quick solution is to add extra '=' to make the string a length multiple of 4.  Something like:
```
def decode_base64(data):
    data += '=' * (len(data) % 4)
    return base64.urlsafe_b64decode(data)
```

For details, please go https://stackoverflow.com/questions/3302946/how-to-decode-base64-url-in-python.

**Comment by chrisfrank** [comment]
Thanks, @TAOXUY. That's the workaround I'm hoping to avoid sending to production. We will ship it if there are no plans to include padding in ESPv2's token value -- but if that's the case I wonder if you'd consider specifying in the `X-Endpoint-API-UserInfo` documentation that you don't use padding? My read of the [spec](https://tools.ietf.org/html/rfc4648#section-3.2) is that implementations without padding need to specify this in order to be in compliance.

**Comment by TAOXUY** [comment]
OK, I see. I think we can directly add padding in the JwtAuthn filter and it should be an enhancement without backward compatibility issue. WDYT, @qiwzhang ?

JFYI, @chrisfrank, even if we add the padding in our side, it would be around several weeks to release.

**Comment by qiwzhang** [comment]
OK,  we can enhance Envoy jwt_authn filter to add padding for the header. 

  Hi @TAOXUY could you file a PR in upstream envoy?  Thanks

**Comment by chrisfrank** [comment]
Much appreciated, @qiwzhang and @TAOXUY. Thanks!

**Comment by TAOXUY** [comment]
The PR has been checked in so wait for ESPv2 nest upgrade on Envoy.

**Comment by chrisfrank** [comment]
Thanks so much, @TAOXUY. We'll make this upgrade as soon as it's released.

**Comment by MoSehsah** [comment]
Please let us know when this will be release as part of ESPv2 image to remove the above workaround from our dependent code

**Comment by MGItkin** [comment]
I'm running into a similar issue with the Golang's built-in base64 lib where decoding this header as base64 URL with or without padding was throwing errors. I solved it by trying to decode `base64.URLEncoding` first, then falling back to `base64.RawURLEncoding` before faulting.

A fix for encoding consistency and some additional documentation would be very helpful here.

**Comment by MGItkin** [comment]
> Hi @MGItkin , which version are you using? Please ping the latest 2.26, which should include the padding fix. Thanks!
> 
> Close the issue for now as the change has been released.

Thanks, upgrading to the latest version resolved this issue for me.

**Comment by someone1** [comment]
Ahh - this explains why my services were breaking after upgrading from 2.24!

The switch from unpadded to padded Base64URL encoding feels like a breaking change that should have been mentioned in the 2.26 [release notes](https://github.com/GoogleCloudPlatform/esp-v2/releases/tag/v2.26.0) - might be worth adding?

**Comment by qiwzhang** [comment]
Thanks.  I updated the release note.

**Comment by TAOXUY** [comment]
I thought the library handled non-padding binary and automatically handle padding binary; didn't expect some library expected strict padding/non-padding binary.

Worth to note the change is [reverted](https://github.com/envoyproxy/envoy/pull/16576) on the upstream envoy and backported in the latest 1.18.3. I have another pending [change](https://github.com/envoyproxy/envoy/pull/167520) to enable it by option. 

Our next release pinning to 18.3 will change this behavior back and later we will expose this feature as a flag.

@nareddyt, you may put the revert in the note in our next release.

**Comment by TAOXUY** [comment]
Please wait for next ESPv2 version and toggle this feature by flag `--jwt_pad_forward_payload_header`.

**Comment by giuliohome** [comment]
> I'm running into a similar issue with the Golang's built-in base64 lib where decoding this header as base64 URL with or without padding was throwing errors. I solved it by trying to decode `base64.URLEncoding` first, then falling back to `base64.RawURLEncoding` before faulting.
> 
> Some additional documentation to let users know of this inconsistency would be very helpful here!

@MGItkin Indeed yesterday I've solved my issue using a `base64.RawURLEncoding` as per this [commit](https://github.com/giuliohome/GoServerlessFirestore/commit/a81bf9af5cc65714967ac7414f869b50c1db6682) in the cloud web-app repo and this [forum post](https://www.googlecloudcommunity.com/gc/Serverless/Missing-last-character-from-X-Endpoint-Api-Userinfo/td-p/414495) exlpaining the problem.
