### ISSUE TITLE
Retrying for backend requests

### ISSUE THREAD

**Issue by tiksa** [GoogleCloudPlatform/esp-v2#179]
Hello,

Currently the dynamic Envoy configuration for backend requests generated by ESPv2's Go code doesn't contain any retry policy. This is a problem because now transient 5xx errors get directly forwarded to end-user as 500s.

The generated route configuration for our backend is now something like this, according to ESPv2 debug logs:
```
"route": {
    "cluster": "europe-west1-<our-project>.cloudfunctions.net:443",
    "host_rewrite": "europe-west1-<our-project>.cloudfunctions.net",
    "timeout": "900s"
}
```
Could we possibly have a configuration for ESPv2 so that we would end up with a configuration like this for every routes:
```
"route": {
    "cluster": "europe-west1-<our-project>.cloudfunctions.net:443",
    "host_rewrite": "europe-west1-<our-project>.cloudfunctions.net",
    "timeout": "900s",
    "retry_policy": {
        "retry_on": "5xx",
        "num_retries": 2
    }
}
```

This would hopefully be relatively small addition but bring significant value for many. For example, using a Cloud Function backend is really cool and scalable and fulfills many needs but due to occasional transient 500s that we cannot handle in any way we cannot provide a reliable service. But of course this would be great for all other kinds of backends as well!

At first I started to hack `route_generator.go` (without any Go skills) but then I realized I have to build the serverless ESPv2 locally to use it in Cloud Run. I tried to find some sensible Dockerfile or build command but didn't make it.

But I think this would be useful for other users as well!

Thank you!

Edit: Envoy's `retry_policy` documentation: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-retrypolicy

**Comment by tiksa** [comment]
Thanks for the quick response. Very happy to hear you have already started designing it, we're looking forward to using it!

**Comment by tiksa** [comment]
Any news regarding this issue? :blush:

**Comment by nareddyt** [comment]
Not yet, @qiwzhang is on vacation this week. I can ask him to take a look again next week.

**Comment by qiwzhang** [comment]
I think the main idea is: to add "retry_on_status" and "retry_number" in "x-google-backend" in OpenAPI spec. 

This issue was assigned to TAOXUY.  He will provide a design.

**Comment by TAOXUY** [comment]
Hi @tiksa, we have design for this but for some dependency reason, we have to put this feature request on hold.
