### ISSUE TITLE
Original authorization token

### ISSUE THREAD

**Issue by Dasio** [GoogleCloudPlatform/esp-v2#18]
Is it possible to retrieve an original authorization token from the user? 
My use case is log in using `hd` (hosted domain) parameter, but I'm not able to get to it.
Another use case is, that I'm using firebase auth with custom claims, where I got user's permissions and I need them to control granular access. But again no access to them without an original token.

https://cloud.google.com/endpoints/docs/openapi/authenticating-users-custom, it says that just issuer, id and email is forwarded.

**Comment by nareddyt** [comment]
Thanks for bringing this up, this is a documentation issue. I can fix it this week.

[This section](https://cloud.google.com/endpoints/docs/openapi/migrate-to-esp-v2#handle-jwt) has the correct behavior and differentiates between ESPv1 and ESPv2.

> ESPv2 Beta sets the `X-Endpoint-API-UserInfo` header differently than ESP. With ESPv2 Beta, the `X-Endpoint-API-UserInfo` header only contains the Base64 encoded payload of the original JWT without modification.

That should satisfy your use cases.

**Comment by TAOXUY** [comment]
FYI, here is an test example of the encoded `X-Endpoint-API-UserInfo` [header](https://github.com/GoogleCloudPlatform/esp-v2/blob/99e280faca23eddb4587ba427f4ab411242b17c9/tests/integration_test/http1_test/http1_integration_test.go#L155) passed to [backend](https://github.com/GoogleCloudPlatform/esp-v2/blob/99e280faca23eddb4587ba427f4ab411242b17c9/tests/endpoints/echo/server/app.go#L222:6).

**Comment by Dasio** [comment]
Thanks for the response, I should have verified it before posting issue.

**Comment by nareddyt** [comment]
Documentation has been updated in a few places, including your [original link](https://cloud.google.com/endpoints/docs/openapi/authenticating-users-custom#receiving_authenticated_results_in_your_api).
