### ISSUE TITLE
API Key with IP address restriction blocks all IP including whitelisted

### ISSUE THREAD

**Issue by volodymyrd** [GoogleCloudPlatform/esp-v2#197]
I've created ESPv2 Cloud Endpoint for my API, everything works fine except when I enabling IP address restriction in API Key, I get a message "PERMISSION_DENIED: IP address blocked." for all requests including whitelisted IP addresses.

What you expected to happen:
Block all requests except whitelisted.

Steps to reproduce:
Create IP restriction for API Key for Endpoint base on ESPv2.

I've checked the endpoint logs and see the internal google IP address instead of my IP address from which I send a request, a corresponding screenshot is attached.
<img width="408" alt="Screenshot 2020-06-13 at 14 41 40" src="https://user-images.githubusercontent.com/3913102/84682072-66bcd400-af35-11ea-823b-00bc414604d7.png">

**Comment by qiwzhang** [comment]
ESPv2 is using `x-forwarded-for` header to get client ip.  But many proxy servers on the path may add this header,  you need to use flag --envoy_xff_num_trusted_hops to tell which client ip to choose.

Please check this [doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html?highlight=xff_num_trusted_hops) for detail.

**Comment by volodymyrd** [comment]
Thanks, this config works for me:
--envoy_xff_num_trusted_hops=1
--envoy_use_remote_address

**Comment by nareddyt** [comment]
Ref https://github.com/cloudendpoints/endpoints-tools/issues/72

**Comment by nareddyt** [comment]
Glad that works. Let's keep this issue open, we need to document this behavior.

**Comment by nareddyt** [comment]
We worked with the Cloud Run team to set defaults for the `endpoints-runtime-serverless` image. We recommend the following defaults:

```
--envoy_xff_num_trusted_hops=0
```

[Your config](https://github.com/GoogleCloudPlatform/esp-v2/issues/197#issuecomment-644378832) will still work if you update to the next released version of ESPv2. There shouldn't be much difference.
