### ISSUE TITLE
Reducing coldstart for ESP beta 2 on Cloud Run

### ISSUE THREAD

**Issue by mejuhi** [GoogleCloudPlatform/esp-v2#221]
I am using Google endpoint with Google Cloud functions, with following specifications:

Cloud Run running ESP beta 2 image (service.json configured in the image):
CPU allocated: 1
Memory allocated: 512Mi
Concurrency: 80
Request time-out: 800 seconds

Cloud Function running simple python code with following specification:
Memory allocated: 128 MB
Time-out: 500 seconds

My first request on cloud endpoint(via Cloud run ESp) takes around 25-17 sec to respond (due to cold start), And it takes couple of secs without the cold start.
I want to find if there is any way to reduce this cold start time?

![image](https://user-images.githubusercontent.com/45816852/87046511-ec6f2f00-c216-11ea-95e5-5c73a60002b5.png)

**Comment by nareddyt** [comment]
Can you clarify where the cold start is? Is the cold start occurring in the ESPv2 Cloud Run service, or your Cloud Function backend?

If you followed [this tutorial](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-functions), it should minimize cold start in ESPv2.

**Comment by mejuhi** [comment]
Yes, I have followed the tutorial from the documentation, my cloud run is running the image with service.json built into it.

I think Cold start is on the Cloud run (running ESP beta 2 image). 

![image](https://user-images.githubusercontent.com/45816852/87086467-44c22300-c24f-11ea-8d12-9c52ed05f801.png)

The first log shows the request to cloud run and cloud function, when both have cold start,
The second log shows request to cloud run and cloud function, in which only cloud function had cold start. 

Things i have tried so far is increasing cloud function memory from 126Mi to 256Mi.
and on cloud run I have increased it to 512Mi from 126Mi, and also decreased Concurrency from 80 to 20. It helped me a bit, but not exactly the result i wanted.

Is there any way i can tune cloud function/cloud run to reduce the response time(reduce the cold start)?

**Comment by mejuhi** [comment]
Yes, I have followed the tutorial from the documentation, my cloud run is running the image with service.json built into it.

I think Cold start is on the Cloud run (running ESP beta 2 image).

![image](https://user-images.githubusercontent.com/45816852/87090347-6e7e4880-c255-11ea-8812-bd50396d924a.png)


The first log shows the request, when both have cold start,
Second log shows request, in which only cloud function had cold start.
Third log shows request, with no cold start on cloud run and cloud function.


Things i have tried so far is increasing Cloud function memory to 256Mi from 126Mi.
and on cloud run I have increased it to 512Mi from 126Mi, and also decreased Concurrency from 80 to 20. It helped me a bit, but not exactly the result i wanted.

Is there any other way i can tune cloud function/cloud run to reduce the response time(reduce the cold start)?

**Comment by qiwzhang** [comment]
There are two things: 1) try to reduce Cloud Run cold start latency,  2)
try to reduce number of cold starts.   Maybe there is something you can
tune for 2),  I doude about 1).   I recommend you ask these questions on
Google Cloud Run form.

**Comment by nareddyt** [comment]
I am surprised it takes ~10 seconds to cold start the ESPv2 Cloud Run image. I cannot reproduce that. At most I've seen it take 5 seconds, usually 3.

Agreed with Wayne, let's try minimizing the number of cold starts. You may find this helpful, I've done this before: https://github.com/ahmetb/cloud-run-faq#how-to-keep-a-cloud-run-service-warm

If you keep the service warm, subsequent requests that requiring scaling may require cold starts, but should be a lot faster.

**Comment by mejuhi** [comment]
Okay, Can you share the configuration you used to run ESPv2 image on cloud run, in case if it helps me to bring down the cold start i am experiencing.

And also wanted to ask, if you have used the image with service.json built into it, or by passing the _ENDPOINTS_SERVICE_NAME_ as an environment variable to cloud run. Will it have any effect on cold start?

**Comment by qiwzhang** [comment]
Yes,  by building service config into ESPv2 docker image,  it reduces a
remote call to Google service management service to fetch the
service config.  Normally, it reduces the latency around 20ms.

**Comment by mejuhi** [comment]
@nareddyt 

I tried couple of times more to get the values right, I am getting around 10 sec of cold start on ESP beta 2.  Given that i have service.json configured in the image.

![image](https://user-images.githubusercontent.com/45816852/87118191-51b73480-c298-11ea-8077-939dbbd978ef.png)


It will be great help if you can share the configuration you used to get the 3-5 sec of cold start on cloud run running ESP beta 2

**Comment by qiwzhang** [comment]
For Cloud Run cold-start latency,  there is not much config you can turn.
 It may have something to do with your region/zion, could not try to deploy
it in another region/zone.

**Comment by mejuhi** [comment]
Okay, I tested by deploying it to another region. Earlier i had cloud run and cloud function in _us-central1_, now I have deployed them to _europe-north1_. I don't think it made any difference

![image](https://user-images.githubusercontent.com/45816852/87125098-8da5c600-c2a7-11ea-97f6-16cedda6c991.png)
