### ISSUE TITLE
Windows-compatible gcloud_build_image script

### ISSUE THREAD

**Issue by EatonZ** [GoogleCloudPlatform/esp-v2#231]
When following [this tutorial](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run#configure_esp), it currently requires the rebuild of the ESPv2 image. What surprised me is the note that said gcloud_build_image doesn't support Windows. Fortunately, a workaround is given (use Cloud Shell), but that didn't work for me ("Permission Denied" error when executing the uploaded script).

It would be great if you could port this script to PowerShell, or make a batch file, so Windows users can complete the tutorial steps locally.

And maybe, if the docs team lurks here, add extra instructions explaining how to correctly execute the script in Cloud Shell for those who have never used it before (like me😬).

**Comment by nareddyt** [comment]
Thanks for the report. 

Unfortunately, we don't plan to support a PowerShell version of the script. All of our development machines and our test machines are linux based. Getting some windows VMs would require more maintenance work than we can justify, especially when we have a workaround with Cloud Shell.

Let's try to figure out why it didn't work for you in Cloud Shell. We can improve the docs then.

I just tested it, and it worked fine. I opened up Google Cloud Console and click on the cloud shell. Then I ran:

```
wget https://raw.githubusercontent.com/GoogleCloudPlatform/esp-v2/master/docker/serverles
s/gcloud_build_image
chmod +x gcloud_build_image
./gcloud_build_image -s espv2-path-matcher-lrnm3ejpeq-uc.a.run.app -c 2020-05-13r1 -p nar
eddyt-cloud-esf
```

And it succeeded.

Do you have any more details on the exact permission denied error you got? Maybe you need  to enable Google Cloud Build for your project?

**Comment by EatonZ** [comment]
Hi @nareddyt, the Cloud Shell error actually doesn't seem to happen now. So disregard that for now...

I am trying to integrate this into a build step on Windows. Since you don't plan on adding a PowerShell script, I discovered an alternative that looks like it will work: [gcloud alpha cloud-shell ssh](https://cloud.google.com/sdk/gcloud/reference/alpha/cloud-shell/ssh). Unfortunately, that too has a problem:

![SSH Error](https://user-images.githubusercontent.com/3020941/88114093-229aa000-cb81-11ea-8eab-cb1800009b6c.png)

I looked for a solution and looks like [someone else ran into this exact same problem, and someone even posted a fix](https://stackoverflow.com/questions/60908083/ssh-putty-error-unable-to-open-address-shell).

Can you let the Cloud Shell team know about this bug? Once that is fixed, I will let you know if I am able to run the script successfully.

**Comment by nareddyt** [comment]
Got it. I filed a bug internally, I'll post here if there are any updates. Keep in mind this is an alpha feature in `gcloud`, so it may not be supported yet.

In the meantime, see if there's any workaround you can do to strip out the bad suffix in your script.

**Comment by EatonZ** [comment]
It turns that out that when I added the `--command`, the problem went away! The bug only seems to occur when not specifying anything.

After running ssh once to set up key stuff, it appears to be working well. Adding `--ssh-flag="-batch"` to my build step made it work without any interaction.

Do you have any other suggestions on how to make this better? Is it possible to run it within the WSL2 layer in Windows? Might be worth investigating so you can have an option for Windows users that doesn't involve using alpha software.

**Comment by nareddyt** [comment]
Ah, glad to hear that works.

In theory, the script should work in WSL. As long as you have `curl` and `gcloud` installed. Unfortunately I don't have a windows machine to test this.

**Comment by EatonZ** [comment]
@nareddyt gcloud alpha cloud-shell ssh is _almost_ perfect. The issue I have now is that ssh will say "The server's host key is not cached in the registry." and then ask you to confirm that the server is legit. Annoyingly, it appears Google rotates [sshHost](https://cloud.google.com/shell/docs/reference/rest/Shared.Types/Environment), so before long it will ask you to confirm adding another fingerprint to the registry, interrupting the build process at unpredictable times.

**Comment by EatonZ** [comment]
I've run into that fingerprint issue many times while building today, unfortunately. The nature of that message makes it inadvisable to automatically say "yes" to it.

Because of that, and the fact that Cloud Shell has a weekly time/usage limitation that cannot be raised, I feel as though Cloud Shell is not a complete solution.

WSL _could_ be a solution, but I would like to see an option to invoke gcloud_build_image build on Google's servers, so that the developer's OS is not a barrier. I'm sure something could be added to Cloud Build. Thoughts?

**Comment by nareddyt** [comment]
Hmm, I'm not familiar with how to workaround that.

FYI the owning team resolved the first problem you described. But it seems like you are blocked anyways.

I suggest you try using WSL, it should be fairly straightforward to setup on your dev machine. Otherwise, you can always use a VM, either on your computer or via Google Compute Engine.

**Comment by EatonZ** [comment]
> FYI the owning team resolved the first problem you described.

👍

> I suggest you try using WSL

Gave it a try today. Easy to set up and it works! I think you should add this to your tutorial, Windows users may appreciate it.
Here is what I did:
1. Make sure you have the WSL feature enabled in Windows and install Ubuntu from the Windows Store.
2. After setting your Linux username and password, run `gcloud init`. (It's not necessary to re-install it, the install on Windows will be used)
3. You can now run gcloud_build_image by doing `bash -c "(gcloud_build_image commands here)"`.

**Comment by nareddyt** [comment]
Good point, I'll add a few extra alternatives (including WSL) to the note in the tutorial. 

I don't want to add too many details there. The tutorial is already very long, and adding detailed instructions on how to use WSL would be irrelevant to most users.

**Comment by nareddyt** [comment]
Docs should be updated by tomorrow.

![image](https://user-images.githubusercontent.com/11142171/91339278-3f3f7e80-e7a4-11ea-9bfb-a3674ba079a9.png)
