### ISSUE TITLE
Bug in gcloud_build_image

### ISSUE THREAD

**Issue by ToddMorrill** [GoogleCloudPlatform/esp-v2#239]
If a user doesn't pass the `-i` parameter to `gcloud_build_image` then `ESP_FULL_VERSION` doesn't get defined.
https://github.com/GoogleCloudPlatform/esp-v2/blob/db1ec6b904c9e0a72e3d05708c0eb62a83640f1b/docker/serverless/gcloud_build_image#L37

In turn, this causes errors when tagging the resulting image.
https://github.com/GoogleCloudPlatform/esp-v2/blob/db1ec6b904c9e0a72e3d05708c0eb62a83640f1b/docker/serverless/gcloud_build_image#L96

I removed `${ESP_FULL_VERSION}-` from the image tag since that seems to be in line with the name convention referred to in the documentation [here](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run#configure_esp).

**Comment by nareddyt** [comment]
I recently updated the script to automatically tag the image name with the latest ESP version.

That is odd. We do a check here: https://github.com/GoogleCloudPlatform/esp-v2/blob/db1ec6b904c9e0a72e3d05708c0eb62a83640f1b/docker/serverless/gcloud_build_image#L54

And then specifically set the `ESP_FULL_VERSION` at the bottom of the if statement.

Can you provide the exact error you received?

**Comment by nareddyt** [comment]
Also FYI I am updating the documentation to refer to the new format.

**Comment by ToddMorrill** [comment]
Here's the relevant portion of the error. TLDR; starting an image tag with `-` appears to be invalid.
```
BUILD
Already have image (with digest): gcr.io/cloud-builders/docker

                   ***** NOTICE *****

Alternative official `docker` images, including multiple versions across
multiple platforms, are maintained by the Docker Team. For details, please
visit https://hub.docker.com/_/docker.

                ***** END OF NOTICE *****
invalid argument "gcr.io/<my-project>/endpoints-runtime-serverless:-my-gateway-hash-uk.a.run.app-2020-07-24r0" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 125
--------------------------------------------------------------------------------------------------------

ERROR: (gcloud.builds.submit) build <build id> completed with status "FAILURE"
```

**Comment by nareddyt** [comment]
Hmm, looks like `ESP_FULL_VERSION` did not get set. But I cannot reproduce this, it works for me.

```
./docker/serverless/gcloud_build_image -s espv2-path-matcher-lrnm3ejpeq-uc.a.run.app -c 2020-05-13r1 -p nareddyt-cloud-esf

Using base image: gcr.io/endpoints-release/endpoints-runtime-serverless:2
Determining fully-qualified ESP version for tag: 2
Building image for ESP version: 2.14.0
...
```

Can you check the first view lines of your log file. Perhaps there was an error that is being ignored by the script?

**Comment by tydegennaro** [comment]
@ToddMorrill I too am having the same issue. A quick work around is to hard code the ESP value 2.14.0.

**Comment by nareddyt** [comment]
I updated the script to print out any errors early. If you see an error, please share so I can fix it.
