### ISSUE TITLE
gcloud_build_image bug "line 73: TAGS_BY_LENGTH: bad array subscript"

### ISSUE THREAD

**Issue by AndrewGable** [GoogleCloudPlatform/esp-v2#245]
Following the [`Building a new ESPv2 Beta image` instructions](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-functions#configure_esp) I got the following error (omitted some exact details for privacy):

```bash
chmod +x gcloud_build_image.sh
./gcloud_build_image.sh -s <CLOUD_RUN_HOSTNAME> -c <CONFIG_ID> -p <ESP_PROJECT_ID>
Using base image: gcr.io/endpoints-release/endpoints-runtime-serverless:2
Determining fully-qualified ESP version for tag: 2
./gcloud_build_image.sh: line 73: TAGS_BY_LENGTH: bad array subscript
```

I was able to use the `-i` flag, but I'm not exactly clear on the side effects of using a "custom" ESP version, so ideally I could use the defaults.

```
./gcloud_build_image.sh  -s <CLOUD_RUN_HOSTNAME> -c <CONFIG_ID> -p <ESP_PROJECT_ID> -i gcr.io/endpoints-release/endpoints-runtime-serverless:2
Using base image: gcr.io/endpoints-release/endpoints-runtime-serverless:2
Building image for ESP version: custom
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22454    0 22454    0     0  13886      0 --:--:--  0:00:01 --:--:-- 13886
[...]
```

**Comment by nareddyt** [comment]
Thanks for the detailed error message, this must be related to the errors also reported in #239.

Any chance you are on MacOS? Apparently negative indices are a new feature that may not be supported on the default bash version macs come with. https://stackoverflow.com/a/16110069/4402434

Problematic line of code: https://github.com/GoogleCloudPlatform/esp-v2/blob/e1aee7fac2d3db9f94756dfc40e0a0199a52a6e7/docker/serverless/gcloud_build_image#L73

We test on debian machines, so we did not run into the error. I can take fix this later today / tomorrow. 

FYI using `-i gcr.io/endpoints-release/endpoints-runtime-serverless:2` is fine. You're just missing out on the output image containing the exact version name (so you won't know which version of ESPv2 is being used, it uses the latest by default).

**Comment by AndrewGable** [comment]
Thanks for the fast reply! Yes, I was running this script via MacOS. No rush on the fix, I am glad to hear there are no negative side effects. I will continue using the work around and am happy to verify the fix on my machine in the future 👍
