### ISSUE TITLE
Errors when building on macOS

### ISSUE THREAD

**Issue by sgammon** [GoogleCloudPlatform/esp-v2#258]
Hello esteemed ESPv2 authors,

I am having trouble building ESPv2 via Bazel on macOS. Here is the error I get:
```
2020/08/03 01:36:35 Downloading https://releases.bazel.build/3.0.0/release/bazel-3.0.0-darwin-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
DEBUG: Rule 'io_bazel_rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1523916428 -0700"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_python' which is a git_repository (rule definition at /private/var/tmp/_bazel_sam.g/c5262b9dd666f2a9cad5b9bc4d2c9fe6/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - <builtin>
 - /Volumes/KICKSTART/esp-v2/bazel/bazel_rules_python.bzl:22:9
 - /Volumes/KICKSTART/esp-v2/bazel/repositories.bzl:22:5
 - /Volumes/KICKSTART/esp-v2/WORKSPACE:91:1
ERROR: /Volumes/KICKSTART/esp-v2/tests/endpoints/grpc_interop/proto/BUILD:1:1: at least one argument must be given to the 'package' function
ERROR: /Volumes/KICKSTART/esp-v2/tests/env/testdata/BUILD:1:1: at least one argument must be given to the 'package' function
ERROR: /Volumes/KICKSTART/esp-v2/examples/BUILD:1:1: at least one argument must be given to the 'package' function
ERROR: package contains errors: tests/env/testdata
ERROR: package contains errors: tests/endpoints/grpc_interop/proto
ERROR: package contains errors: examples
ERROR: error loading package 'examples': Package 'examples' contains errors
Loading: 28 packages loaded

```

This, after running `bazelisk query //...`. Any ideas?

**Comment by sgammon** [comment]
Additionally, when building (rather than querying), I get the following error:
```
(01:40:55) INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/config/trace/v3:pkg:
envoy/config/trace/v3/opencensus.proto:12:1: warning: Import validate/validate.proto but not used.
envoy/config/trace/v3/trace.proto:5:1: warning: Import udpa/annotations/status.proto but not used.
(01:40:55) ERROR: /private/var/tmp/_bazel_sam.g/c5262b9dd666f2a9cad5b9bc4d2c9fe6/external/com_github_googleapis_googleapis/google/logging/type/BUILD.bazel:11:1: C++ compilation of rule '@com_github_googleapis_googleapis//google/logging/type:type_proto' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote ... (remaining 34 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from bazel-out/darwin-fastbuild/bin/external/com_github_googleapis_googleapis/google/logging/type/log_severity.pb.cc:4:
bazel-out/darwin-fastbuild/bin/external/com_github_googleapis_googleapis/google/logging/type/log_severity.pb.h:65:3: error: expected identifier
  DEBUG = 100,
  ^
<command line>:2:15: note: expanded from here
#define DEBUG 1
              ^
1 error generated.
Target //src/envoy:envoy failed to build
Use --verbose_failures to see the command lines of failed build steps.
(01:40:56) INFO: Elapsed time: 105.839s, Critical Path: 65.49s
(01:40:56) INFO: 700 processes: 700 darwin-sandbox.
(01:40:56) FAILED: Build did NOT complete successfully
```

**Comment by qiwzhang** [comment]
Unfortunately, we don't have resource to support building this repo in MacOS.

**Comment by sgammon** [comment]
@qiwzhang that was true of ESPv1 too. Without the ability to build ESP in a local dev environment, we are precluded from using it at all.

With the barest amount of help/support, this could be made to work on macOS. Is another Unix-like build target really beyond the reach of almighty Google?

**Comment by sgammon** [comment]
@qiwzhang the motivation behind this is rolling ESPv2's filters into our custom envoy config

which is already built on mac, Envoy itself builds fine on mac. so this is definitely an issue with ESPv2, not Envoy. there is no reason I can think of that macOS build support would be out of reach when this repo already uses Bazel and a generic C/C++ compiler.

if you are willing to unblock me on the above bug, at least, I can try to get it to work and submit a PR?

**Comment by nareddyt** [comment]
Maybe it will not be too much work, especially if Envoy already builds on mac. I can take a quick look tomorrow. But even if we can get it working, we cannot support it in the long run (we won't have any automated tests to ensure it doesn't break).

**Comment by nareddyt** [comment]
Hi @sgammon. Unfortunately I did not make much progress on this. I was not even able to get envoy to build successfully on my mac, due to missing tools and binaries. We have a few other issues to prioritize (Beta launch, documentation, oncall, etc.), so I can't spent much more time on it this week.

I took a closer look at your original comments. 
- For the first comment you opened the issue with, I suggest you run `bazel query //src/...`. Some of our test packages may have bad bazel rules that we need to fix. We don't use bazel to run our tests anymore, but everything under `/src/` should work with bazel. 
- The build error in the second comment is due to https://github.com/bazelbuild/bazel/issues/3513. This seems difficult to fully solve, you need to do some toolchain configuration. But I think one workaround is to build in opt mode: `bazel build -c opt /src/envoy:envoy`. Can you confirm this works?

**Comment by sgammon** [comment]
@nareddyt thank you for your efforts nonetheless :)

i will attempt builds locally and get back to you with results - there is a sister issue for getting macOS builds working for the new [pagespeed filter for envoy](https://github.com/apache/incubator-pagespeed-mod/issues/2024), which leverages a lot of similar code, so i am planning to look to that for guidance as well.

**Comment by sgammon** [comment]
@nareddyt building with `bazelisk build -c opt //src/envoy:envoy` produced a binary! yay!

is there a different target i should try building?

**Comment by nareddyt** [comment]
Awesome, that is the entire envoy binary that has all our filters. So it seems to build fine using `-c opt`. Hopefully that's a valid workaround (it will make debugging harder and builds take longer though).

**Comment by sgammon** [comment]
my main desire/concern here for building on mac is being able to build our full stack locally and run. i don't foresee a need to debug ESPv2 itself, or if i do, i'm happy to do so in a linux VM environment.

thank you again for your help - this is great!
