### ISSUE TITLE
ESPv2 Beta does NOT pass the CORS request to my backend Cloud Run

### ISSUE THREAD

**Issue by MarcoSantarossa** [GoogleCloudPlatform/esp-v2#261]
I have a Cloud Run backend service and I'm integrating to ESPv2 Beta following the official doc. It looks like CORS is not passed to the backend even if I have this configuration:

```
x-google-endpoints:
- name: <my-endpoint-service>.run.app
  allowCors: True
```
When I call it with my reactJS web app, I have the following error:

```
[..] has been blocked by CORS policy: Request header field x-api-key is not allowed by Access-Control-Allow-Headers in preflight response
```
because I'm using api key in the header `x-api-key` and OPTIONS response has only these headers allowed:
```
DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization
```
I've already tried using the flags `--cors_preset=basic++--cors_allow_headers` but it looks ignored and I continue having the same issue.

(If I call directly my backend, it works so it looks an issue with ESP)

**Comment by qiwzhang** [comment]
There are two ways to support CORS preflights 
* "allowCors: True"  in openapi x-google-endpoints: which config ESP to bypass CORS preflight to your backend, your backend should handle it.
* flag --cors_preset=basic  config ESPv2 to handle it,  the request will not pass to your backend.

You should not mix these two methods.   

In your case, your backend should add x-api-key in the "Access-Control-Allow-Headers"

**Comment by MarcoSantarossa** [comment]
> There are two ways to support CORS preflights
> 
> * "allowCors: True"  in openapi x-google-endpoints: which config ESP to bypass CORS preflight to your backend, your backend should handle it.
> * flag --cors_preset=basic  config ESPv2 to handle it,  the request will not pass to your backend.
> 
> You should not mix these two methods.
> 
> In your case, your backend should add x-api-key in the "Access-Control-Allow-Headers"

I tried both in different time, at the moment I'm just using the first approach but it still doesn't work. I think my backend is fine since my API calls work if I don't use Endpoint but directly my backend Cloud Run service.

**Comment by MarcoSantarossa** [comment]
I also read this "Caches the result of the preflight OPTIONS request for up to 20 days (1728000 seconds).". Can I delete this cache to make sure I'm not fighting against cache ?

**Comment by qiwzhang** [comment]
When you try to talk to your backend directly without ESPv2,  do you have `x-api-key` header in the preflight request?

**Comment by MarcoSantarossa** [comment]
> When you try to talk to your backend directly without ESPv2, do you have `x-api-key` header in the preflight request?

That's correct !

**Comment by qiwzhang** [comment]
The document about "Caches the result of the preflight OPTIONS request for up to 20 days" is incorrect. It is not implemented in ESPv2.  It is ESPv1 thing.   ESPv2 doesn't return `Access-Control-Max-Age: 1728000`

**Comment by MarcoSantarossa** [comment]
I add more experiements:
1.
`--set-env-vars=ESPv2_ARGS=^++^--cors_preset=basic++--cors_allow_headers="Test3"` << it overrides correctly 

2.
Remove point 1 and
`ENV ESPv2_ARGS ^++^--cors_preset=basic++--cors_allow_headers="Test,something"` in the script to build the image << it remains the previous "Test3"
3.
Remove point 2 and add
```
x-google-endpoints:
- name: <my-endpoint-service>.run.app
  allowCors: True
```
<< remains the previous "Test3"

**Comment by qiwzhang** [comment]
If you have flag --cors_preset=basic,   OPTIONS is handled by ESPv2,  "allowCors: true" will not apply.  In order to try the latter, you have to remove all cors flags in the ESPV2_ARGS

**Comment by qiwzhang** [comment]
For 2) and 1), there is a tricky thing in gcloud CLI.   --set-env-vars is persistent across multiple run.  So your 2) is still using --set-env-vars=ESPv2_ARGS=^++^--cors_preset=basic++--cors_allow_headers="Test3"   even you are not using it.   You should use --clear-env-vars to clear it.

**Comment by MarcoSantarossa** [comment]
> --clear-env-vars

I confirm `--clear-env-vars` made the openAPI approach work. Thank you for the help. I think the env persistency is not very clear in the doc, it would be nice to add a couple of lines to explain it. If it's open source, I'm happy to contribute in the doc !

**Comment by qiwzhang** [comment]
I fired this [bug](https://issuetracker.google.com/163042092) for Cloud Run team
