### ISSUE TITLE
ESPv2 not reporting metrics and log entries correctly when deploying with a service account (non-gcp)

### ISSUE THREAD

**Issue by gojohnkevin** [GoogleCloudPlatform/esp-v2#304]
I was originally using esp v1 then migrated to v2 using GKE. After migrating to esp-v2, I cannot see the latency times anymore in Cloud Endpoints->Services->Overview page.

Is this a problem with my configuration? I just changed the version from 1 -> 2 as stated in the migration guide.

**Comment by TAOXUY** [comment]
I am able to see it for a service deployed on GKE[1][2]. Could you check the access log by:
- go to sidebar -> Logging -> Logs Viewer -> the target service[3]
- send a request and see if it appears on the log

[1]
![image](https://user-images.githubusercontent.com/16471764/91640791-f0c4f680-e9d4-11ea-9813-aaf2ddb5f070.png)
[2]
![image](https://user-images.githubusercontent.com/16471764/91640804-0afed480-e9d5-11ea-8ff4-d710085747d4.png)
[3]
![image](https://user-images.githubusercontent.com/16471764/91640846-5d3ff580-e9d5-11ea-84d1-590a0ecb17ef.png)

**Comment by gojohnkevin** [comment]
@TAOXUY It actually does show in the log viewer but the cloud endpoints graph is empty since migration.

![Screenshot 2020-08-30 at 12 33 43 AM](https://user-images.githubusercontent.com/9165701/91641708-eb10f480-ea58-11ea-996a-8246ec953de3.png)

![Screenshot 2020-08-30 at 12 37 32 AM](https://user-images.githubusercontent.com/9165701/91641726-0419a580-ea59-11ea-9022-df6e93cc87d1.png)

**Comment by qiwzhang** [comment]
Do you see any lines in "Request" and "Error" graphs.  Cloud you play with
time tags at the right top, e.g. "1 hour", "6 hours", '1 day", ... to see
if any graph shows your ESPv2 traffic?
Generally,  if logging shows your traffic,  graphs should show too.

Did you use same deployment environment for v1 and v2,  e.g. project, GKE
cluster, service account, ?

**Comment by gojohnkevin** [comment]
@qiwzhang I have already done that. The only graph that shows is when I was still using v1. 

I have not changed any configuration in my deployment except changing the version of the docker image to 1->2. All other configuration is the same.

**Comment by gojohnkevin** [comment]
What I noticed too is that the location label in the log payload is empty for v2.
![Screenshot 2020-09-01 at 2 15 46 PM](https://user-images.githubusercontent.com/9165701/91804041-cafe5280-ec5d-11ea-836d-4020b121e430.png)

**Comment by gojohnkevin** [comment]
Closed the issue.

in ESP-v1, service_account_key was required but in v2 it's only required for non-gcp. Having the service_account_key in the config also enables non-gcp configuration.

**Comment by nareddyt** [comment]
Thanks for providing more details about it not working when a service account is provided (even though that is not your use case).

We have some e2e tests that deploy with a service account, and I see the same problems.

Missing metrics:
![image](https://user-images.githubusercontent.com/11142171/91881224-27a64100-ec4f-11ea-8a42-8e6450cd6898.png)

Missing location in some log entries:
![image](https://user-images.githubusercontent.com/11142171/91881047-e7df5980-ec4e-11ea-9274-7f96e47c420d.png)

For all out other e2e tests that use metadata server to fetch an access token, I do NOT see the same issue.

I'll re-open and investigate.

**Comment by qiwzhang** [comment]
Yes, we may have two bugs here
1) service_account_key should not cause non_gcp=true.  We should support specifying a service account key even in GCP platforms
2) if zone or location info is missing, report should work.  It seems the logging is working but metric is not.  Maybe a bug here.

**Comment by nareddyt** [comment]
I will focus on bug number 2 first.

Looking at our ESPv2 application logs, I see plenty of errors calling report. Not many other details, but this indicates it's not a permission issue with the service account key. Perhaps we're configuring the SC filter incorrectly?

```
[31][filter][src/envoy/http/service_control/client_cache.cc:145] Failed to call report, error: INTERNAL:Calling Google Service Control API failed with: 400 and body: \010\003\022%Request contains an invalid argument., str body: \010\003\022%Request contains an invalid argument.
```

Here is the full service control filter config that was generated  (too large to post here, posted on google internal pastebin): https://paste.googleplex.com/5761913645432832

I compared this with our [canonical SC filter config](https://github.com/GoogleCloudPlatform/esp-v2/blob/7ce040cc5d06d6752bbbdb399c5ed6b8440be1ca/examples/service_control/envoy_config.json#L165). But did not see anything suspicious.

I then compared it to the SC filter config for our e2e test that does not use a service account. The only difference is the missing GCP attributes (due to bug 1, where it's treated as non-gcp).

![image](https://user-images.githubusercontent.com/11142171/91884950-f16bc000-ec54-11ea-9358-caaf41751dd1.png)

The missing gcp attributes explain the missing `location` label, and maybe even the invalid argument error. Not clear if this would also cause the metrics to be missing.

**Comment by nareddyt** [comment]
Regarding bug number 1:

https://github.com/GoogleCloudPlatform/esp-v2/blob/7ce040cc5d06d6752bbbdb399c5ed6b8440be1ca/docker/generic/start_proxy.py#L653

If service account key is provided, we assume non gcp. This is not the intended behavior. Instead we should support the following 3 modes:
1. GCP with access token from IMDS, attributes from IMDS
2. GCP with access token from service account, attributes from IMDS
3. Non-gcp: access token from service account, no attributes -> This is where bug 2 (described above) seems to occur.

This also matches the [publicly documented flag behavior](https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#platform) and behaves the same as ESPv1.

In this case, i'll fix bug 1 first and support deploying on gcp with a customer service account. This should be relatively simple, and it reduce the number of deployments that are affected by missing metrics.
