### ISSUE TITLE
"Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections"

### ISSUE THREAD

**Issue by brianeroth** [GoogleCloudPlatform/esp-v2#342]
I have a setup similar to the one described here: https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run.

When I try to generate a JWT from a service account credentials JSON file, I receive an error from ESPv2: "Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections." When I inspect the JWT generated, it is in the correct format, but appears to have extra `==` signs for padding in the payload section of the token. I'm not sure if this is throwing ESPv2 off, or if it's something else. When I take the JWT and try to decode it using `google.auth.jwt.decode`, it's able to decode fine, which leads me to believe the JWT is at least in the correct format.

The code for generating a JWT from a service account is below:
```
...
        signer = google.auth.crypt.RSASigner.from_string(
            service_account_info['private_key'],
            service_account_info['private_key_id'])

        issuer = service_account_info['client_email']

        now = int(time.time())

        payload = {
            'iat': now,
            'exp': now + ONE_HOUR_IN_SECONDS,
            'aud': aud,
            'iss': issuer,
            'sub': issuer,
            'email': issuer
        }

        signed_jwt = google.auth.jwt.encode(signer, payload).decode('utf-8')
```

Any thoughts?

**Comment by nareddyt** [comment]
I've seem similar problems with JWT padding because JWTs are `base64url` encoded (not `base64`). Maybe you can try to generate a JWT in `base64url` encoding so it doesn't have the padding? This SO post explains the encoding more: https://stackoverflow.com/a/47107759/4402434

But looking at [our code](https://github.com/google/jwt_verify_lib/blob/894ba8e648161e3ada6267ff05e77c9eca8409b7/src/jwt.cc#L50-L59), I don't think the padding should throw it off. These are the only two places we return `JwtBadFormat`, it doesn't seem to check the padding.

@qiwzhang any ideas? If not, maybe you can share a JWT so we can reproduce the problem? Sharing JWTs should be safe.

**Comment by brianeroth** [comment]
@nareddyt This doesn't seem to be a problem with the JWT itself since it can be decoded fine elsewhere. Any ideas on where this error message is coming from exactly? A search for "Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections." returns almost no results.

Let me know if you have any other thoughts. If not, I can share an expired JWT

**Comment by qiwzhang** [comment]
JWT parser code is [here](https://github.com/google/jwt_verify_lib/blob/master/src/jwt.cc#L58)

If you got "Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections" error,  it seems the error is not from base64 code.   It is just from splitting the JWT sections with dot.

Well,  According to [RFC](https://www.rfc-editor.org/rfc/rfc7515.txt): JWT base64url encode should not use padding.

**Comment by qiwzhang** [comment]
It is possible the JWT token passed to ESPv2 is truncated somehow.   Could you use --enable_debug flag to turn on ESPv2 debug, and get the JWT token from the ESPv2 Cloud Run log

**Comment by brianeroth** [comment]
@qiwzhang I've sent you an email with an expired JWT in question. It doesn't look truncated and confirmed that by being able to decode it properly with all expected info in the token.

**Comment by qiwzhang** [comment]
It seems that you are getting wrong JWT for me to debug.

There are two JWT:  one is from client, Envoy jwt_authn use it to verify,
You should see it from envoy http_connectioni_manager debug log
there is another one: ESP generated, send to your backend,   you can see it
in envoy router debug log.  What you send to me, is this one.

You should send me the first one

**Comment by qiwzhang** [comment]
Update on this issue.  

We am getting correct JWT token from ESPv2 debug log.  But strange thing is:  the JWT token is good in jwt.io and in unit-test of jwt_verify_lib repo.  

So I have to build an debug docker image for users to run it.

**Comment by qiwzhang** [comment]
https://github.com/GoogleCloudPlatform/esp-v2/pull/347 is used to build this debug image

**Comment by qiwzhang** [comment]
Found the problem.  the problem is still the base64 padding "=".  "=" is not legal HTTP url and headers.  When extracting token from the header,  the string after "=" are truncated.   So jwt_authn only see partial jwt token.  Hence get that error

For jwt token, it should not have padding "=".

**Comment by brianeroth** [comment]
Thanks for investigating @qiwzhang. I guess I'll need to look more into how the JWT is being generated to understand why the extra padding is appearing.

**Comment by qiwzhang** [comment]
The key is:  jwt has to use base64url to encode,  not base64.  Here is the [different](https://stackoverflow.com/questions/55389211/string-based-data-encoding-base64-vs-base64url#:~:text=1%20Answer&text=Both%20Base64%20and%20Base64url%20are,binary%20data%20in%20string%20form.&text=The%20problem%20with%20Base64%20is,with%20%2D%20and%20%2F%20with%20_%20.) between these two.

**Comment by reken-rich** [comment]
I am not sure if I should be opening a new issue or not, but I am running into this issue when enabling token authentication in api gateway.  I have a grpc service in cloud run with api gateway configured fronting it.  If I configure api gateway with no auth (allow_unregistered_calls=true) and I set the authorization header in the metadata, I can see the token passed to the backend as x-forwarded-authorization and I can decode that token using jwt.io.  The token is an Entra ID id_token.

When I modify the config to include auth:

authentication:
  providers:
    - id: entra_id
      jwks_uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
      issuer: https://login.microsoftonline.com/<tenant id>v2.0
      audiences: <client id>
  rules:
    - selector: '*'
      requirements:
        - provider_id: entra_id
  
  I get the error in the title of this issue.  The token clearly has the 3 segments as decodes fine in jwt.io.  It seems this error is only returned when doing the parse so I'm at a loss as to what the issue could be.
