### ISSUE TITLE
Support for AuthenticationRule.allow_without_credential?

### ISSUE THREAD

**Issue by oliverchang** [GoogleCloudPlatform/esp-v2#353]
Hi!

We're building a service that needs JWT credentials to be optional. i.e. Default to api keys, but can also accept an optional JWT for additional access control. 

It seems like there is a flag in google.api.AuthenticationRule exactly for this: [allow_without_credential](https://github.com/googleapis/googleapis/blob/f446e123bc04ee0ee0edfa112f4998182638322b/google/api/auth.proto#L68) 

Are there plans to support this?

**Comment by JLXIA** [comment]
Yeah, sounds reasonable. 

We will consider the feasibility to support this.

**Comment by qiwzhang** [comment]
@oliverchang 
 Where are going to specify this flag? are you using OpenAPI spec. or gRPC [spec](https://github.com/googleapis/googleapis/blob/master/google/api/service.proto) directly?

**Comment by oliverchang** [comment]
Yes, we were hoping to add this to our [api_config.yaml](https://cloud.google.com/endpoints/docs/grpc/grpc-service-config).

**Comment by JLXIA** [comment]
for service config, it will be easy to implement.

but we should also consider the support for OpenAPI. 

I am thinking, we can do something like:
                "security": [
                    {
                        "api_key": [],
                    },
                    {
                        "allow_without_credential": []
                    }
                ],

**Comment by oliverchang** [comment]
I believe that OpenAPI has the following documented limitation (no logical-OR when api keys are involved): https://cloud.google.com/endpoints/docs/openapi/openapi-limitations

Perhaps this could just be relaxed to allow a subset of configs rather than adding an explicit flag/extension? i.e.

```
security:
  - api_key: []
    jwt: []
  - api_key: []
```

which I believe achieves the same thing but is not possible today.

**Comment by qiwzhang** [comment]
This flag match exactly as envoy jwt_authn filter `allow_missing` flag.  It should be easy to add it.

Will be implemented as following:
* Not as stated in the comment above this flag, it has nothing to do with api-key requirement.  Regardless api-key is required or not. 
* If there is any jwt requirement in this rule,  and this flag is on,  Jwt becomes optional.  If jwt is missing,  request will not be rejected,  But if jwt is in the request, it has to be a valid one.

**Comment by oliverchang** [comment]
That would be fantastic! Any timelines for when this will be added? 

Thanks!
