### ISSUE TITLE
Don't use IMDS for backend auth when running with `--non_gcp`

### ISSUE THREAD

**Issue by nareddyt** [GoogleCloudPlatform/esp-v2#359]
This is a small usability enhancement based on customer confusion in issue #352.

When running ESPv2 with the `--non_gcp` flag, it's expected that we don't contact [IMDS](https://cloud.google.com/compute/docs/storing-retrieving-metadata), as IMDS is a GPC compute-specific server. We honor this for most ESPv2 runtime components except backend authentication.

When `backend.rules` are configured for remote backends, ESPv2 by default contacts IMDS to retrieve the JWT for remote backend authentication. It will always contact IMDS for backend auth, unless the [BackendRule](https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#backendrule) has `disable_auth = true`. 

So if there is a backend rule that requires a JWT but we are running ESPv2 with the `--non_gcp` flag, we should either:
1. Reject the config, display an error to disable auth for the backend rule. 
2. Allow the config, but implicitly overwrite the backend rule to disable auth.
3. Allow the config unmodified and display a warning. Preserves the current behavior, which results in Envoy never starting because the backend auth filter can't contact IMDS. I'm definitely against this behavior, we shouldn't be making requests that we know will fail.

1 and 2 are technically breaking changes, but it's probably OK to do so. The current behavior is not intended. I'm learning towards option 1, it's the clearest option. @qiwzhang @TAOXUY any thoughts?

Some implementation considerations:
- Update [this integration test](https://github.com/GoogleCloudPlatform/esp-v2/blob/fa28e9a6c337f82394f6fd4157c42a76417fbb6f/tests/integration_test/non_gcp_test.go#L28). Currently it only tests ESPv2 with a local backend (sidecar mode), so it did not catch the backend auth filter making requests to IMDS.
- Backend auth also supports contacting IAM instead of IMDS. This is only used by Cloud API Gateway, and they'll always run on GCP. But for consistency, we should still follow the same implementation decision for IAM as IMDS.

**Comment by qiwzhang** [comment]
I prefer option 2 with additional of warning.  This will be useful for local development.  Users will deploy ESPv1 in GCP (e.g. Cloud Run) in production, but they like to test it in local Linux during development.   In the local case, they have to use --non_gcp, we should just allow it and log a warning.

**Comment by qiwzhang** [comment]
Do we know how to generate ID token from SA?  We know for access token.

**Comment by nareddyt** [comment]
We currently don't have logic to generate an ID token from a service account. We rely on IMDS or IAM for that.

Let's go with option 2 for now. If `--non_gcp`, then override `disable_auth` to true.

If API Producers are affected by this (ie. they want to test backend auth locally), we need to add ID token generation to config manager based on SA. Seems low priority, we can add that in the future if needed. For now, option 2 seems the easiest to use.
