### ISSUE TITLE
The current timeout for backend connection is 15s, which is not configurable yet.

### ISSUE THREAD

**Issue by JLXIA** [GoogleCloudPlatform/esp-v2#4]
Feature request: Make the timeout for backend connections configurable and allow long-running requests of up to 120 seconds.

For now, we will just bypass ESPv2 our long-running requests, there are just a few.

**Comment by nareddyt** [comment]
Thanks for reporting the issue Jilin. I have confirmed this behavior and have a prototype with increased timeouts.

We are evaluating the following ways of configuring this:
- Via a flag when starting ESPv2: Easier and can be released in a few days, but not flexible and not good design in the long run. Especially when we need to support long-running *streaming* gRPC requests in a few months.
- In the service configuration under the `x-google-backend` OpenAPI Extension. This is better design and more flexible in the long run. But this will probably take 2-3 weeks to fully implement (Google production change).

I will discuss with the rest of the ESP engineering team tomorrow and update here.

**Comment by nareddyt** [comment]
We have decided to follow option 2: In the service configuration.

Docs will be updated when this feature is ready.

**Comment by nareddyt** [comment]
Change is implemented in ESPv2, it just needs to be released. But it cannot be used until the next version of Google Service Management is rolled out to production. This can take until next Friday (2/7/20) to roll out to all of prod.

**Comment by nareddyt** [comment]
I have verified that the Google Service Management production release has finished.

Here is some documentation for this feature: https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#deadline

Once we make a new release of ESPv2, this should start working. We plan on releasing 2.4.0 early next week.
