### ISSUE TITLE
No traces after upgrade to v2

### ISSUE THREAD

**Issue by clehene** [GoogleCloudPlatform/esp-v2#412]
Hi,

We just upgraded from v1 to v2 because we were seeing two traces instead of one (ESP trace and a second gRPC trace) 
With v2 we only see the gRPC trace - i.e. ESP is no longer recording a trace (running with debug the only `trace` keyword we see is in the headers `x-cloud-trace-context`

```
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:2
        args: [
          "--listener_port=8443",
          "--ssl_server_cert_path", "/etc/nginx/ssl",
          "--enable_debug",
          "--service=api-dev-1.sandbox.tapwater.io",
          "--cors_preset=basic",
          "--cors_expose_headers=custom-header-1,grpc-status,grpc-message",
          "--cors_allow_headers=authorization,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,x-api-key",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:8000",
          "-z", "healthz"
        ]
```

**Comment by nareddyt** [comment]
By default, ESPv1 and ESPv2 will only trace 1 out of 1000 requests. Can you try setting `--tracing_incoming_context=1.0` and then see if there are any traces?

Ref: https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#tracing

Just FYI, we have integration tests and e2e tests that confirm ESPv2 is sending traces currently. Here is what the traces from our stress tests look like:

![image](https://user-images.githubusercontent.com/11142171/98399429-5adec500-2030-11eb-9d45-90e14354ef47.png)

**Comment by nareddyt** [comment]
Quick edit: The flag name is `--tracing_sample_rate`, I pasted the wrong one above.

**Comment by clehene** [comment]
@nareddyt thank you, that did it. Although the data gets flooded by `ingress ESPv2_Autogenerated_HealthCheck` now. Is there a way to get only these sampled? 

I think I figured the original problem of having two independent traces  (which I still do) - basically I need to set `--tracing_outgoing_context` (to avoid the defined behavior "If omitted, no trace context header is sent.")  to something that would be picked up by opencensus / stackdriver

**Comment by nareddyt** [comment]
Good points. Let me open two separate issues for these.

**Comment by clehene** [comment]
Later edit in my case this should be `--tracing_outgoing_context=grpc-trace-bin` but this isn't documented in the startup options (https://github.com/GoogleCloudPlatform/esp-v2/blob/master/docker/generic/start_proxy.py#L463-L467) perhaps it should.

**Comment by bogdandrutu** [comment]
@clehene @nareddyt in case of grpc+opencensus on the server side (application) then the outgoing header from espv2 should be `grpc-trace-bin`, maybe worth documenting.

**Comment by nareddyt** [comment]
Thanks, seems we missed documenting that option. We can add documentation for it.

@bogdandrutu quick follow-up question: 
- Does gRPC + opencensus support `traceparent`? I know OpenTelemetry does, but I assume OpenCensus does not.
- Are there any potential issues with setting the default trace context to `traceparent`? Currently we don't extract/inject the trace context by default, would changing this default introduce a breaking change or any security concerns? If traceparent is the future, we'd prefer to change this to be extracted/injected by default.

**Comment by bogdandrutu** [comment]
>Does gRPC + opencensus support traceparent? I know OpenTelemetry does, but I assume OpenCensus does not.

No, and probably will not work on that

> Are there any potential issues with setting the default trace context to traceparent? Currently we don't extract/inject the trace context by default, would changing this default introduce a breaking change or any security concerns? If traceparent is the future, we'd prefer to change this to be extracted/injected by default.

I would suggest to do that and avoid breaking in the future, and just mention in the documentation that users of opencensus need to change that.

**Comment by qiwzhang** [comment]
My understanding is tracing_incoming_context is to unify (to use the same parent trace id) the trace spans from the downstream proxy,  and tracing_outgoing_context for the upstream proxy or backend.   It  should not have anything to do with OpenCensus of OpenTelemetry.

Normally,  grpc is using `grpc-trace-bin`, http may use `traceparent`.   So maybe we can add our default trace_context base on the protocol.  downstream protocol (especially between grpc and http), we may not work beforehand,   but for upstream protocol, I think we should know.  So maybe we can set default outging_context based on backend protocol.

**Comment by bogdandrutu** [comment]
It has something to do, OpenCensus supports only grpc-trace-bin for some gRPC integration, but OpenTelemetry supports multiple options in all languages, but it has the default of traceparent (so if you emit grpc-trace-bin will not work by default in OpenTelemetry). Other systems may work, but these two that I know will have this problem

**Comment by nareddyt** [comment]
Agreed with @bogdandrutu's comment above. It really depends on the customer's backend, just because they use gRPC does not mean it supports `grpc-trace-bin`. That is just gRPC + Opencensus. 

I know that Google Cloud is moving towards `traceparent` with OpenTelemetry as the default (go/w3c-trace-context-guidelines, go/serverless-tracing-tomorrow), we should align by always defaulting to `traceparent`. We can document when users need to override it.

**Comment by qiwzhang** [comment]
OK then, lets default to `traceparent` for both incoming and outgoing trace context.

**Comment by nareddyt** [comment]
Awesome. Action items for us:
- Change trace context propagation to default to `traceparent`.
- Update public docs with this change. Also document under what conditions this should be changed, our current documentation does not give many details on this. Don't forget to mention we support `grpc-trace-bin`.

**Comment by clehene** [comment]
@nareddyt @bogdandrutu thanks again! This is working now. I'll leave this open since it has the two action items

For reference, these are the docs I used:
* https://cloud.google.com/endpoints/docs/grpc/migrate-to-esp-v2
* https://cloud.google.com/endpoints/docs/grpc/specify-esp-v2-startup-options#tracing

Also this is how my combined trace looks like. 
![image](https://user-images.githubusercontent.com/101597/98450830-ed489c80-20f4-11eb-9bfe-26c0e15f44b5.png)

**Comment by nareddyt** [comment]
Just FYI, all those traces are actually from ESPv2. The `router backend-cluster ...` span is created by ESPv2 before it sends the span to the backend. So it also includes the network hop to reach the backend, but this shouldn't matter much since you deploy on GCE/GKE.

Here is an example where the backend (on Cloud Functions) creates a span and it's combined. We use `traceparent` context propogation.

![image](https://user-images.githubusercontent.com/11142171/98579350-8362fb00-228c-11eb-850b-7c4341405536.png)

**Comment by clehene** [comment]
@nareddyt got it, thank you. I collapsed too much - mine is actually deeper 

![image](https://user-images.githubusercontent.com/101597/98600194-0dfa2900-2292-11eb-89b3-e382e6d7ff57.png)

**Comment by nareddyt** [comment]
Official documentation is updated for ESPv2 and trace context propagation

https://cloud.google.com/endpoints/docs/openapi/tracing
https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#tracing
