### ISSUE TITLE
All cors OPTIONS method fail after upgrade to v2

### ISSUE THREAD

**Issue by trongchata** [GoogleCloudPlatform/esp-v2#424]
Here is the config for the eps v2

image: gcr.io/endpoints-release/endpoints-runtime:2
        args: [
          "--ssl_port", "443",
          "--ssl_protocols", "TLSv1.2 TLSv1.3",
          "--backend=servicename.staging",
          "--service=companydomain.com",
          "--rollout_strategy=managed",
        ]

When I used the ESP v1, all the cors request OPTIONS will pass to my backend service. We will handle it. 

But after I upgrade to ESP v2, all OPTIONS request fail.  I follow the google document to change it, but it doesn't work.

**Comment by TAOXUY** [comment]
Basically, you want ESPv2 to pass through the cors request to your backend. Could you double check if 
- in your openAPI file, the `allowCors` under your backend of `x-google-endpoint` is set
- no other cors flags are provided in your args for which you look already did

If this issues is still there,  could you please provide:
- the rejecting response
- the log of ESPv2 after add `--enable_debug` in `args`


Here are some related docs
- https://github.com/GoogleCloudPlatform/esp-v2/issues/261
- https://cloud.google.com/endpoints/docs/openapi/support-cors#handle_cors_in_your_backend_application

**Comment by trongchata** [comment]
1. In my openAPI file, I already allowCors=True.  So it works fine on ESP v1
2. The rejecting response.  There is no error code, no response.
    Http Error `net::ERR_CONNECTION_REFUSED`

**Comment by TAOXUY** [comment]
Cloud you please set `--enable_debug` in your ESPv2 container `agrs` and get the ESPv2 log in the running instance? You can paste it here after removing the personal info or you can send to taoxuy@google.com, qiwzhang@google.com, nareddyt@google.com.

**Comment by nareddyt** [comment]
Hi @trongchata, are you still running into this issue?

ESPv2 is designed to be backwards compatible with ESPv1 in terms of the OpenAPI spec. So it should honor `allowCors: true` the same way. We have [a few integration tests](https://github.com/GoogleCloudPlatform/esp-v2/blob/a8f86f24e01715a83c5c959eb953bb19e4e19d8f/tests/integration_test/cors_integration_test.go#L418) that verify this behavior.

There could be some edge case we are not handling, so I'm curious.
