### ISSUE TITLE
Trace not added to a log entry

### ISSUE THREAD

**Issue by TheSpy** [GoogleCloudPlatform/esp-v2#431]
Hello, 
I am using ESPv2 2.21 within a GKE.
A request is coming in a sequence as following:

Http call >> glbc with neg -> service A  ->  service B

1. Service A receives a x-cloud-trace-context header within ESPv2 which is translated to a traceparent header and passed to a backend. A backend makes a call to a service B propagating a traceparent header.
2. Service B receives a traceparent header within ESPv2 which is passed to a backend

In a trace view I can see that a trace is propagated correctly and requests are tied together
![image](https://user-images.githubusercontent.com/514031/101350674-054c4100-3898-11eb-9dfd-15c9d35cc1e7.png)

However, when I try to search the stackdriver logs tied together by traceid, I cannot find espv2 requests, because they are missing trace field.

Here are the requests that are **correctly tied together** by trace id.

![image](https://user-images.githubusercontent.com/514031/101352598-121e6400-389b-11eb-9214-23cc8224aed7.png)

Here are the ESPv2 requests that are missing the trace field and are **not tied correctly** to a previous search result

![image](https://user-images.githubusercontent.com/514031/101353152-d2a44780-389b-11eb-841d-9fca39247aa1.png)

Am I missing something, or is it just not a supported feature yet ?

Thanks!

**Comment by nareddyt** [comment]
You are correct. When ESPv2 writes the access log, it does not populate the trace id [in the Service Control Report API](https://cloud.google.com/service-infrastructure/docs/service-control/reference/rest/v1/Operation#logentry). As you pointed out, this is needed to correlate the trace with the Endpoint's "Producer API" logs in Cloud Logging.

I don't see any major blockers for this feature, we could implement it. I will spend some time later this week prototyping to make sure it works.

Implementation details: The format is `projects/${PROJECT_ID}/traces/${TRACE_ID}`. We know project ID from the instance metadata server or command line flag, which is passed to SC filter via [gcp_attributes](https://github.com/GoogleCloudPlatform/esp-v2/blob/a8f86f24e01715a83c5c959eb953bb19e4e19d8f/api/envoy/v9/http/service_control/config.proto#L93). Trace id can be extracted from [the response headers](https://github.com/GoogleCloudPlatform/esp-v2/blob/a8f86f24e01715a83c5c959eb953bb19e4e19d8f/api/envoy/v9/http/service_control/config.proto#L93), but it will require code duplication and a direct dependency on OpenCensus. Need to research if there's a cleaner way to keep the header extraction logic in the OpenCensus envoy extension while still exposing the trace id.

**Comment by TheSpy** [comment]
Good news! Thanks!
