### ISSUE TITLE
OpenAPI compiler does not support x-google-backend at path level

### ISSUE THREAD

**Issue by haensl** [GoogleCloudPlatform/esp-v2#437]
Hi guys,

I followed this [Endpoints on Google Cloud Run](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run) guide to deploy a Node.js service behind a managed ESPv2 to Google Cloud Run. Both use service accounts and IAM. 

Everything deploys fine. Even the custom domain worked right away. If I interpret the logs correctly the Node service is booted after deploy and then scaled to 0 soon after.

However, whenever I request my API, I receive `503` with
```json
{
  "code": 503,
  "message": "upstream connect error or disconnect/reset before headers. reset reason: connection failure"
}
````

At first I thought nothing about it, because the docs say:

<img width="784" alt="Screenshot 2020-12-10 at 20 45 40" src="https://user-images.githubusercontent.com/12875760/101842743-035cd900-3b49-11eb-9a9a-042cc10c227e.png">

However, since the situation did not change within 24 hours I dug a bit and tried several things:

* Use IPv4 for backend resolution as suggested in #170 --> no change
* Made the Node service public and checked if it responds --> works fine on it's own.
* Did a lot of research into the Roles and Policies and hopefully ended up with the correct IAM setup:
    * Both Cloud Run instances use a service-account.
    * The ESPv2 service account has both the `Cloud Run Invoker` and `ServiceController` roles.
    * The Console UI shows the ESPv2 service account as member of the Node API with `Cloud Run Invoker`.
    
In the logs of the ESPv2 Cloud Run service, I can see the request coming in, the logs of the Node.js API, however, stay empty,. I.e. it appears as if it is not hit.

ESPv2 logs:
```
D1210 21:58:25.989 28 envoy] [28][http][C4] new stream
// request header complete...
D1210 21:58:25.990 28 envoy] [28][filter]get operation_name: <CORRECT_OPERATION>
D1210 21:58:25.990 28 envoy] [28][router][C4][S14571687005584178148] cluster \'backend-cluster-<MY_APP_ID>_local\' match for URL \'<CORRECT_REQUEST_PATH>\'
// request header decoding...
D1210 21:58:25.990 28 envoy] [28][pool]queueing stream due to no available connections
D1210 21:58:25.990 28 envoy] [28][pool]creating a new connection
D1210 21:58:25.990 28 envoy] [28][client][C5] connecting
D1210 21:58:25.990 28 envoy] [28][connection][C5] connecting to 127.0.0.1:8082
D1210 21:58:25.990 28 envoy] [28][connection][C5] connection in progress
D1210 21:58:25.990 28 envoy] [28][filter]Called ServiceControl Filter : decodeData
D1210 21:58:25.990 28 envoy] [28][http][C4][S14571687005584178148] request end stream
D1210 21:58:25.990 28 envoy] [28][filter]Called ServiceControl Filter : decodeData
D1210 21:58:25.991 28 envoy] [28][connection][C5] delayed connection error: 111
D1210 21:58:25.991 28 envoy] [28][connection][C5] closing socket: 0
D1210 21:58:25.991 28 envoy] [28][client][C5] disconnect. resetting 0 pending requests
D1210 21:58:25.991 28 envoy] [28][pool][C5] client disconnected, failure reason: 
D1210 21:58:25.991 28 envoy] [28][router][C4][S14571687005584178148] upstream reset: reset reason: connection failure, transport failure reason: 
D1210 21:58:25.991 28 envoy] [28][http][C4][S14571687005584178148] Sending local reply with details upstream_reset_before_response_started{connection failure}
D1210 21:58:25.991 28 envoy] [28][filter]Filter::encodeHeaders is called.
D1210 21:58:25.991 28 envoy] [28][http][C4][S14571687005584178148] encoding headers via codec (end_stream=false):\n\':status\', \'503\'\n\'content-length\', \'117\'\n\'content-type\', \'application/json\'\n\'date\', \'Thu, 10 Dec 2020 21:58:25 GMT\'\n\'server\', \'envoy\'\n\'x-envoy-decorator-operation\', \'ingress <OPERATION_ID>\'
D1210 21:58:25.992 28 envoy] [28][filter]Sending report : service_name: 
// a lot of metrics and summary of the above
```

My current OpenAPI spec:

```yaml
swagger: '2.0'
info:
  title: <API_NAME>
  description: <DESCRIPTION>
  version: <VERSION>

host: api.dev.mydomain.tld

x-google-endpoints:
- name: <GATEWAY_NAME>
  allowCors: True

schemes:
  - https

produces:
  - application/json

definitions:
  // some schema stuff

paths:
  /path:
    x-google-backend:
      address: https://<NODE_SERVICE_ID>-<HASH>.a.run.app
      protocol: h2
    post:
      operationId: <OPERATION_ID>
      parameters:
        // parameter definitions
      responses:
        // response definitions
```

Thank you in advance. Any help is greatly appreciated!

**Comment by TAOXUY** [comment]
Hi @haensl,

This is known issue and has been reported in  https://github.com/GoogleCloudPlatform/esp-v2/issues/430 and we have a fix https://github.com/GoogleCloudPlatform/esp-v2/pull/436 on the way.

**Comment by qiwzhang** [comment]
I assume this error is not transit.  It happenes on every request, is that right?

If so,  the new  `backend_retry_ons` flags we are working on will not help.

**Comment by qiwzhang** [comment]
Is it possible there is a typo in your openapi config, in this line
```
  address: https://<NODE_SERVICE_ID>-<HASH>.a.run.app
```

**Comment by haensl** [comment]
> Is it possible there is a typo in your openapi config, in this line
> 
> ```
>   address: https://<NODE_SERVICE_ID>-<HASH>.a.run.app
> ```

I take the URL to put there from the Console UI of the Node.js API, correct?

<img width="1114" alt="Screenshot 2020-12-11 at 00 58 58" src="https://user-images.githubusercontent.com/12875760/101844519-e4604600-3b4c-11eb-898b-2d16657f2610.png">

If so, then no. I checked that a million times of course. 

> I assume this error is not transit. It happenes on every request, is that right?
> 
> If so, the new `backend_retry_ons` flags we are working on will not help.

Correct. Every request.

**Comment by haensl** [comment]
Is this a problem of slow app startup and can be solved by me trying to boot the Node.js API faster?

**Comment by nareddyt** [comment]
Thanks for the detailed issue description. I think you may have misconfigured your ESPv2 Cloud Run service. These log lines are very suspicious:

```
D1210 21:58:25.990 28 envoy] [28][router][C4][S14571687005584178148] cluster \'backend-cluster-<MY_APP_ID>_local\' match for URL \'<CORRECT_REQUEST_PATH>\'
D1210 21:58:25.990 28 envoy] [28][connection][C5] connecting to 127.0.0.1:8082
```

It seems like ESPv2 is trying to connect to a local backend, not the remote nodejs backend. This could happen if the `x-google-backend` in your OpenAPI is not in the correct spot: ESPv2 will then assume your backend is local and fallback to `127.0.0.1`. Can you double check it's indented correctly and matches the one from the tutorial?

If you don't see anything suspicious, please email me (nareddyt@google.com):
1) Your full OpenAPI spec
2) The converted service config, which you can get with this command:

```
gcloud endpoints configs describe "${CONFIG_ID}" \
  --project="${PROJECT}" \
  --service="${SERVICE}" \
  --format=json \
  > service.json
```

Perhaps you added the `x-google-backend` into the OpenAPI spec later and forgot to redeploy the spec and ESPv2 with the change? Make sure the `CONFIG_ID` you deployed is correct, you used the same `CONFIG_ID` when you ran `gcloud_build_image`, and you deployed ESPv2 on Cloud Run with that image.

**Comment by qiwzhang** [comment]
Hi @nareddyt you may have something here.  I was very suspicious of this debug line too
```
connecting to 127.0.0.1:8082
```
We should not be talking to any localhost in remote proxy mode.

**Comment by qiwzhang** [comment]
I just read user config, the `x-google-backend` is between `path` and `get`  as

```
paths:
  /path:
    x-google-backend:
      address: https://<NODE_SERVICE_ID>-<HASH>.a.run.app
      protocol: h2
    post:
```

It should under `post`,  or at the top level.   I don't know the behaviors of in between.  Let me try it first

**Comment by qiwzhang** [comment]
Yes, I just tried.  You should NOT be `x-google-backend` in between `path` and `http_method`,  such as

```
paths:
  /path:
    x-google-backend:
      address: https://<NODE_SERVICE_ID>-<HASH>.a.run.app
      protocol: h2
    post:
```

It will generate a empty backend address, like

```
backend:
  rules:
  - selector: 1.loadtest_gateway_no_apikey_n2golbgymq_uc_a_run_app.Loadtest0
```

It is a bug.

**Comment by qiwzhang** [comment]
Hi @nareddyt , could you help to look at the api-compiler code to see how easy to support putting `x-google-backend` in between `path` and `post`.   If easy,  we just fix it. Otherwise we just document it.

**Comment by haensl** [comment]
> I just read user config, the `x-google-backend` is between `path` and `get` as
> 
> ```
> paths:
>   /path:
>     x-google-backend:
>       address: https://<NODE_SERVICE_ID>-<HASH>.a.run.app
>       protocol: h2
>     post:
> ```
> 
> It should under `post`, or at the top level. I don't know the behaviors of in between. Let me try it first

#### This is it! Thank you big time, I would probably have never found out!

> Yes, I just tried. You should NOT put `x-google-backend` in between `path` and `http_method`, such as
> 
> ```
> paths:
>   /path:
>     x-google-backend:
>       address: https://<NODE_SERVICE_ID>-<HASH>.a.run.app
>       protocol: h2
>     post:
> ```
> 
> It will generate a empty backend address, like
> 
> ```
> backend:
>   rules:
>   - selector: 1.loadtest_gateway_no_apikey_n2golbgymq_uc_a_run_app.Loadtest0
> ```
> 
> It is a bug in "gcloud endpoints service deploy". The workaround is to put `x-google-backend` under http_method, such as `get`, `post`. Such as
> 
> ```
> paths:
>   /path:
>     post:
>        ...
>        x-google-backend:
>          address: https://<NODE_SERVICE_ID>-<HASH>.a.run.app
>          protocol: h2
> ```

If this is considered a bug and not a user error on my side: having the `x-google-backend` where I had it validates just fine via

```
gcloud endpoints services deploy openapi.yml --project "${GOOGLE_CLOUD_PROJECT_ID}" --validate-only
```

**Comment by nareddyt** [comment]
Good find @qiwzhang. 

Technically [our documentation](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#x-google-backend) for `x-google-backend` is correct. In this OpenAPI config, the extension was specified at [a path level](https://swagger.io/docs/specification/paths-and-operations/), which is not documented.

> The extension can be specified at the top level and/or the operation level of an OpenAPI specification.

But I see why you consider this a bug instead of a user error. We don't need to support it, but perhaps we need validate against it. I'll take a look at OpenAPI compiler, if it's difficult we can make the docs clearer.

**Comment by nareddyt** [comment]
We added validation against this. Will probably take 2 weeks to roll out to prod.
