### ISSUE TITLE
CloudRun getting 503 Service Unavailable issue after 120sec request processing

### ISSUE THREAD

**Issue by vladislavkoz** [GoogleCloudPlatform/esp-v2#438]
I'm facing 503 issues as well and in my case, I'm getting 503 for each request(after 2 minutes processing). I have the following configuration: --memory 2Gi --cpu 4 --max-instances 4 --concurrency 1 --timeout "60m"

It works well when I'm restricting my code in time to less than 2 minutes. It's so weird.I was so happy that I can run processing during 15m and even 60 in beta mode but it fails each time on 2.

The request failed because either the HTTP response was malformed or connection to the instance had an error

![image](https://user-images.githubusercontent.com/40685761/101938719-81be8700-3bec-11eb-9508-ed25b34c4196.png)

I was thinking that this is because of the CPU usage but I've disabled all the code. I've added just a sleep timeout for 130 seconds and tested it. 
'Sleep timeout' is just a waiting for promise to resolve:
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

No CPU intensive work at all(start processing the request -> await sleep(120*1000) -> return response. And I still see the same 503 issues.

It works fine again once I'm setting the timeout to 119 seconds.
Here is the config:
![image](https://user-images.githubusercontent.com/40685761/101938770-9bf86500-3bec-11eb-972c-aea3e2a6d9de.png)

**Comment by qiwzhang** [comment]
Cloud you clarify following:
1) Where and how did you deploy ESPv2?  in Cloud Run,  what "Cloud Run deploy" argument you used?  
2) Where did you deploy your backend application?
2) What "119 second timeout"?  Are you testing your backend processing time?  If your backend need to process a request > 120s,  ESPv2 respond 503?   Is that the case?

**Comment by vladislavkoz** [comment]
Ohhh I'm not using ESP-v2 at all. It's just a simple CloudRun with NodeJs. That is why I was asking whether to create a ticket in this repository.

I'm getting 503 issue when it takes more then 120 seconds to return the response. There is no CPU intensive work. 119 seconds is fake timeout in code. So the code execution stops for 119 seconds before responding with the "Hello world" text

**Comment by qiwzhang** [comment]
I see.  It seems that you get timeout by Cloud Run. According to this [doc](https://cloud.google.com/run/docs/configuring/request-timeout), Cloud Run default request timeout is 5 minutes.  You tried to set it to 60m.

**Comment by vladislavkoz** [comment]
Yes, I've tried max 15mins timeout and also I've tried 60m that allowed in beta. You can see it on the following screenshot
![image](https://user-images.githubusercontent.com/40685761/101943905-9b63cc80-3bf4-11eb-8f7d-037c7f1642c4.png)

**Comment by qiwzhang** [comment]
We are not Cloud Run team.  Do you have other channels to reach the Cloud Run team?

**Comment by vladislavkoz** [comment]
Unfortunately no. I've tried to find the related repo and this one is only one that I found.
Could you point me to the corresponding repo/guys?

**Comment by qiwzhang** [comment]
OK,  I filed an internal bug to the cloud run team.

**Comment by vladislavkoz** [comment]
Thanks a lot. In which way I could get some feedback later?

**Comment by qiwzhang** [comment]
I asked them to response to you here

**Comment by steren** [comment]
Node.js has a built-in default timeout, check your Node.js configuration.

**Comment by vladislavkoz** [comment]
Yes, It's a good mention. I'll check this.

**Comment by vladislavkoz** [comment]
It is a Node.js timeout. It would be good to have some mention about it somewhere just to not forget. I was confused because of the Cloud Run timeout configuration. I got it to work. Thanks.

**Comment by steren** [comment]
We mention this explicitly already at https://cloud.google.com/run/docs/configuring/request-timeout

**Comment by arun21** [comment]
@vladislavkoz Can you tell me how you set the timeout in your NodeJs Application, as I am having the same problem as yours.

Thanks.

**Comment by vladislavkoz** [comment]
In my case:

const REQUEST_TIMEOUT = 600000;

app.post('/', async (req, res) => {
    res.connection.setTimeout(REQUEST_TIMEOUT);
    // Process the request
});

**Comment by arun21** [comment]
Thanks @vladislavkoz

**Comment by bhr** [comment]
If you want to globally increase the request timeout in a NodeJS express app:

```
const DEFAULT_TIMEOUT = 60 * 60 * 1000; // in ms
const DEFAULT_PORT = 8080;

const app = express();
const server = app.listen(PORT, () => {
  console.info(`⚡️[server]: Server is running at https://localhost:${PORT}`);
});

server.setTimeout(DEFAULT_TIMEOUT);
```
