### ISSUE TITLE
Configure the stream idle timeout

### ISSUE THREAD

**Issue by rbretecher-fcms** [GoogleCloudPlatform/esp-v2#455]
Feature request : Be able to configure the Envoy stream idle timeout :
https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#stream-timeouts

It appears that ESPv2 answers with an error after 5 minutes because of the default stream idle timeout of Envoy :
> The default stream idle timeout is 5 minutes.

Answer is :
```json
{
    "code": 408,
    "message": "stream timeout"
}
```

For now, we can only configure the backend deadline wich is something else :
https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#deadline

Could we have a flag to be able to configure the stream idle timeout ?

```json
- name: esp
  image: gcr.io/endpoints-release/endpoints-runtime:2
  args: [
    "--stream-idle-timeout=1800s"
  ]
```

**Comment by nareddyt** [comment]
Could you provide more details on when your clients see this timeout? Is the client protocol gRPC, HTTP/JSON, websocket, etc? I assume it is a streaming gRPC method. 

Do you plan to set the timeout to something large, or just disable it? Additionally, have you considered the workaround of just having your clients send a "ping" on the streaming RPC every couple of minutes to ensure the stream is never idle?

I originally implemented timeout configurability in ESPv2 a year ago. Looking over our internal design doc (go/cloudesf-long-duration-requests), I found we were aware of the issue but never followed up on it.

> The current implementation allows ESPv2 to modify Envoy's response timeouts per route. This fully supports long-running HTTP/1.x, HTTP/2, and unary gRPC requests. **But this only partially supports long-running streaming gRPC requests.** We need to allow the user to configure `stream_idle_timeout` fully support this case.

I have no objections to introducing a flag to configure this for all routes. Alternatively we can introduce another field to `x-google-backend` to configure the idle_timeout per route (similar to `deadline`). The latter would be much more complex. @qiwzhang @TAOXUY what do you think?

**Comment by TAOXUY** [comment]
It would be best if customers can have some workaround solution and we hold for API Gateway's OpenAPI-v3 config, also considering only one customer brought up this issue for the past one year.

I am OK with alternative solution of adding a flag.

I don't think we can introducing it into `x-google-backend`, as it would be same problem of adding envoy config in OP config.

**Comment by rbretecher-fcms** [comment]
Thanks for your replies

Actually, the API is a basic HTTP API, there's no `gRPC` involved. This API processes things and can take more than 5 minutes to answer (it's not perfect but this is the way it has been implemented).

The client is a Cloud Scheduler Job that just makes a `GET` request to this API.

To give you more context, at first, I had an error after 15 seconds :
```json
{
    "message": "upstream request timeout",
    "code": 504
}
```
So I decided to increase the deadline to 30 minutes and it did the job except when the backend takes more than 5 minutes to answer.

So I would say I would like to be able to increase this limit (but not disable it).

**Comment by nareddyt** [comment]
Huh, that is surprising. It sounds like ESPv2 does not support `deadline` over 5 minutes currently if the `stream_idle_timeout` is kicking in. Let's consider this a bug in the support for `deadline`. I will try to reproduce it in our integration test environment.

Implementation wise, we can simply set the per route [idle timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-idle-timeout) as:
```
routeAction.IdleTimeout = math.Max(user_specified_per_route_deadline, 5 * time.Minutes)
```

We don't need a flag, but I may still introduce one for the gRPC case.

**Comment by qiwzhang** [comment]
Hi @nareddyt your proposal sounds good for non gRPC streaming.  For gRPC streaming,  we may need to add a flag stream_idle_timeout.

**Comment by nareddyt** [comment]
Thanks, I will do both. FYI I was able to reproduce this problem. I guess setting a `deadline` over 5 minutes is fairly uncommon, but we should support it.

**Comment by qiwzhang** [comment]
SG
