### ISSUE TITLE
x-cloud-trace-context missing on gRPC responses

### ISSUE THREAD

**Issue by someone1** [GoogleCloudPlatform/esp-v2#471]
Although not something I'm really sure is a feature of ESPv2, it's something I've been using and relying on when troubleshooting client calls to my application.

I have deployed a gRPC service with the OpenAPI transcoding annotations on Cloud Run and have ESPv2 sitting in front of it, also on Cloud Run.

Requests to this API using an OpenAPI client work and returns a `x-cloud-trace-context` header on the response. A gRPC client making a request to the same endpoint (in this case, specifically a gRPC Web client), does not have the header in either the response HTTP headers or the gRPC metadata.

Is this something ESPv2 injects into responses? I can see the trace ID propagates well throughout the request via logging, but doesn't make its way back to the client. This has proven critical for helping us debug client reported issues during the development process.

**Comment by qiwzhang** [comment]
Do http and grpc-web clients send `x-could-trace-text` headers to ESPv2?  If they don't,  ESPv2 may enable trace based on the sampling rate.  Not sure if your traces are enabled by clients or sampling. 

The only different between two paths is one is using grpc_transcoding filter, and the other is using grpc_web filter.  They don't touch `x-could-trace-text`.   I don't know why there could have such different.

**Comment by someone1** [comment]
Neither my OpenAPI nor my gRPC Web client send the `x-cloud-trace-context` header in their requests and I do have trace sampling enabled on ESPV2 (100% during development), but beyond that I believe Cloud Run also injects the header for incoming requests so we can [correlate logs](https://cloud.google.com/run/docs/logging#correlate-logs).

The difference seems to be that cloud run doesn't return responses with the header injected and it only happens from ESPv2 for non-gRPC responses.

I should note that if I send a request to ESPv2 to the gRPC endpoints, if there's an authentication error or something I will get the `x-cloud-trace-context` header in the response, but not if its a successful gRPC request.

**Comment by someone1** [comment]
Actually - after more testing this may be a Cloud Run injected response header - I'm trying out the `gcr.io/cloudrun/hello` image and seeing `x-cloud-trace-context` headers in the response - maybe I need to open a ticket with their platform team?

**Comment by someone1** [comment]
Ahh - this may be due to this issue: https://issuetracker.google.com/issues/169349067

apologies for the confusion!

**Comment by nareddyt** [comment]
Yes, I suggest reaching out to Cloud Run team. This behavior is not from ESPv2. 

GCP Serverless offers are going through a transition phase from `x-cloud-trace-context` to the W3C standard `traceparent` header ([reference docs](https://cloud.google.com/endpoints/docs/openapi/tracing#supported_headers) on trace context propagation). Cloud Run may be:
- Setting one or both headers automatically if your request is missing them.
- Translating between the headers automatically if your request only has one.

If you modify your clients to set the trace context headers in the request, ESPv2 will guarantee to preserve them in the response. We have [some integration tests](https://github.com/GoogleCloudPlatform/esp-v2/blob/3892b9e2413fc8e23050bd8bd230b7723677b00b/tests/integration_test/opencensus_tracing_test.go#L506) for this. So if the trace context is important for clients, I suggest integrating a tracing framework into them (OpenTelemetry is recommended).
