### ISSUE TITLE
Docs: how to run locally with local x-google-backend addresses

### ISSUE THREAD

**Issue by chrisfrank** [GoogleCloudPlatform/esp-v2#478]
From @nareddyt's [comment](https://github.com/GoogleCloudPlatform/esp-v2/issues/352#issuecomment-702431976) in #352, it looks like it is possible to run ESPv2 locally with multiple local backends. Is this documented somewhere? What we're hoping to do is something like this:

1. Modify our OpenAPI spec locally to use local URLs in the `x-google-backend` address values.
2. Boot ESP locally, referencing the local OpenAPI spec from step (1) instead of fetching the config from GCP.

We're using ESPv2 as an API gateway into several HTTP services. Being able to run everything locally would be a huge help in development.

Assuming the approach from the linked issue is the way to go, I guess the specific thing I'm asking is: how can we convert an OpenAPI JSON spec into a valid `service_config_generated.json` file?

**Comment by qiwzhang** [comment]
We don't have doc yet for running ESPv2 locally with multiple local backends.  We will try to add one later.

For converting openapi spec to "normalized" endpoint service config used by ESPv2,  the supported way is to use CLI `gcloud endpoints service deploy` and downloaded it by `gcloud endpoints configs describe`.

There is an outdated open source api-[compiler](https://github.com/googleapis/api-compiler).  But it  has not been updated for many years, we don't recommend it.

**Comment by nareddyt** [comment]
Yup, you can run with multiple local backends by specifying localhost addresses in `x-google-backend`. Make sure to set the other fields correctly, like `protocol`.

Similar to @qiwzhang's recommendation, you can just create a dev Cloud Endpoints service and deploy the modified OpenAPI spec to it. Then use the [Non-serverless startup flags](https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#basic) to point ESPv2 to the dev service and config id. It will automatically download and use it.

Also consider setting some of the [non GCP](https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#platform) flags if you're running on your local workstation. You will need at least `--non_gcp` and `--service_account_key`. [This doc](https://cloud.google.com/endpoints/docs/openapi/running-esp-localdev) will walk you through the process.

Let us know how it works out.

**Comment by chrisfrank** [comment]
`gcloud endpoints configs describe` was the missing piece for me. Thanks all, I'll give this a try!

**Comment by fareeda0** [comment]
Hey @chrisfrank do you think you could give me a quick walk though how you got this to run locally?

I think I’m piecing together the bits and pieces required but I’m not 100% sure.

Thanks 🙏🏽
