### ISSUE TITLE
Feature: Add extra headers sent to the backend

### ISSUE THREAD

**Issue by dariuszsq** [GoogleCloudPlatform/esp-v2#479]
Team,
I have multiple ESPv2 with one backend. I realized that ESP is not able to send additional / extra header to the backend which i can use to recognize source from where request is comming.

Kindly, can i ask you to add this feature to next release ?

Thank you
Dariusz Sobiechowski

**Comment by qiwzhang** [comment]
In theory, this feature can be implemented as following:
1) add, append or remove any request headers before sending to the upstream
2) add, append or remove any response headers before sending to the downstream. 
3) it can be per-route. this require OP service config change.

Let us only do 1) for  now.   add some flags to support this.  e.g.

```
--request_headers_add=key=value
--request_headers_append=key=value
--request_headers_remove=key
```

This flag can be set multiple times. e.g
```
--request_headers_add=key1=value1  --request_headers_add=key2=value2
```

**Comment by dariuszsq** [comment]
Sounds like a plan - do you know ETA ?

**Comment by nareddyt** [comment]
Hi @qiwzhang, do you have an implementation plan for this? I'm curious if you will use the envoy router or if you'll introduce custom logic into our SC filter.

I know the router can add headers, but will it remove the header if it's already in the request?

**Comment by qiwzhang** [comment]
I will use VirtualHost or RouteConfig  [requst_headers_to_add](https://github.com/envoyproxy/envoy/blob/eeb7adc3a30456f0d4ac65e5e6c8e88e25481d2a/api/envoy/config/route/v3/route.proto#L59) field.

So it can support custom request/response [headers](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#custom-request-response-headers) 

With this, it support both request and response.  so I am going to add 4 flags
--add_request_header
--append_request_header
--add_response_header
--append_response_header
