### ISSUE TITLE
Restriction on path(from swagger file)  based on API key being used for calling Cloud endpoint (using ESPv2 as base image)

### ISSUE THREAD

**Issue by mejuhi** [GoogleCloudPlatform/esp-v2#491]
Hello!

I have a requirement where I want to restrict a API key  to access only certain path defined in swagger file. Currently I am not able to find any supporting documentation which explains how to restrict the access of an API key to only access some specific path defined in the swagger file which gets deployed on Cloud endpoint.

I believe this granularity of access though API key should be given.

**Comment by TAOXUY** [comment]
I think you can use the method-level api key [restriction](https://cloud.google.com/endpoints/docs/openapi/restricting-api-access-with-api-keys#restricting_access_to_specific_api_methods) to meet the requirement. If it doesn't, could you clarify why?

**Comment by mejuhi** [comment]
I am looking for something like this
![image](https://user-images.githubusercontent.com/45816852/110657212-a70c6280-81e6-11eb-830f-35976b057028.png)

For example I have 2 API keys (Api key 1 and Api key 2). I should be able to configure which path(s) Api key 1 can have access to and which path(s) Api key 2 have access to.
In this fig, Api key 1 should only be able to access '/path1' and should not be able to access '/path2'. Whereas Api key 2 should be able access both '/path1' and '/path2'

**Comment by nareddyt** [comment]
This is not supported by ESPv2 and it is not recommended. You should not be using API keys as a form of access control. https://cloud.google.com/endpoints/docs/openapi/when-why-api-key

I suggest you use JWT Authentication instead. You can configure certain paths to require a specific JWT.

**Comment by TAOXUY** [comment]
You are right. The granularity API Key check is project-level so in your example, if we allow access on `/path1` on `API KEY 1`, we cannot reject it on `/path2`

**Comment by mejuhi** [comment]
Okay, that makes it clear. I was hoping to get around with some configuration which will enable to support out this feature.

I will look into and try out the JWT authentication to check if it is able to do this access control and if we are able to fit it in the project requirement.

Thankyou for explanation and time

**Comment by mejuhi** [comment]
I was able to go through the following documentation of using [jwt](https://cloud.google.com/endpoints/docs/openapi/service-account-authentication#python) as authentication  
my only concern is that caller of the this Cloud Endpoints are legacy system and would not support the jwt token creation and in case we provide the JWT token to the caller it will have an expiry time associated with it. '

The issue of expiring of a token was something we resolved using API keys(since they don't expire unless deleted)

Would it be possible to create a JWT token which does not expire and can be used for a long time after initial creation?

**Comment by nareddyt** [comment]
> Would it be possible to create a JWT token which does not expire and can be used for a long time after initial creation?

Yes, you can specify the expiry time when you create a JWT. Here is a sample python client we use for our tutorials, you can override the default 3600 seconds. We generate JWTs with expiry times of 10 years for our integration tests.

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/040bea85cd92bbe882dba5d36a5e98869cfe1e36/endpoints/getting-started/clients/google-jwt-client.py#L33

**Comment by mejuhi** [comment]
That sounds great! I will try this one! Thankyou! :)

**Comment by mejuhi** [comment]
Hello! Thankyou for the suggestion of JWT token, I tried to test it out, it is working as expected and fits most of our requirements. We are just having one small issue, one of the caller of our endpoint would not able able to use this jwt token header, I do understand from your explanation and documentation that API key should not be used as access control mechanism, but if going forward can we expect some configurable options that can help us achieve this requirement of path based control which JWT is able to do with the ESP?

Again, thankyou for your time and helping with the explanation in detail!

**Comment by qiwzhang** [comment]
ESP only supports configuration that an api-key" is required or not on
per-path based.   But we don't support allowing specific api-key on
per-path based.

This is supported:
e.g.   path1 requires api-key,  path2, not requires api-key.    api-keys
can be from any consumer projects that have  enabled your service.

This is not supported:
path1 only allows api-key1 and path2 only allows api-key2.

**Comment by mejuhi** [comment]
Thankyou for explanation. Details provided by all of you has helped a lot with redesigning the architecture with the new requirements.
