### ISSUE TITLE
ESPv2 ignores `--service_account_path` when GKE Workload Identity is enabled

### ISSUE THREAD

**Issue by chrisfrank** [GoogleCloudPlatform/esp-v2#496]
Hi there,

When running ESPv2 (OpenAPI) in a GKE cluster with [Workload Identity](https://cloud.google.com/endpoints/docs/openapi/get-started-kubernetes-engine-espv2) enabled, my team has stumbled on two seemingly-related issues:

1) If the ESP pod's k8s account hasn't yet been bound to a GCP account, ESP fails to boot. We were able to fix this by mounting a volume in the pod and booting ESP with the `--service_account_path=/path/to/account.json` flag. Because this worked and we still hadn't bound the k8s/GCP accounts, I think ESP was at this point correctly calling the service management APIs under the identity we specified in `--service_account_path`. So far so good, but...

2) After resolving (1), we deployed a change to the OpenAPI spec that applied the `x-google-backend` annotation on a single new endpoint. This change again caused ESP to crash. After looking at the logs, I think ESP is detecting that `x-google-backend` is in use and attempting to contact the metadata server, but it appears to be trying to use default k8s service account instead of the account specified in the startup flag. Calls to the metadata server failed in the ESP logs with:

```
Your Kubernetes service account (dev/default) is not annotated with a target Google service account, which is a requirement for retrieving Identity Tokens using Workload Identity.\nPlease add the iam.gke.io/gcp-service-account=[GSA_NAME]@[PROJECT_ID] annotation to your Kubernetes service account.\nRefer to https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
```

I was able to fix (2) by completing the Workload Identity service account binding steps documented [here](https://cloud.google.com/endpoints/docs/openapi/get-started-kubernetes-engine-espv2#add_required_iam_roles). However, at this point it looks like ESP is still ignoring the service account we're specifying via the flag. I would expect that ESP would call the `x-google-backend` target with a self-signed JWT issued by the mounted service account. What I'm seeing instead is that ESP is calling the target backend with a JWT signed by the GKE metadata server, with an `email` value of the Workload Identity acount, _not_ the email of the account in `--service_acount_path`.

**Comment by qiwzhang** [comment]
At the 2nd step,  ESPv2 is calling GCP metadata server to get ID token.  This requires you to bound a GCP account to k8s account.   You can disable this by setting  disalbe_auth to true.  it is documented [here](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#jwt_audience_disable_auth)

**Comment by chrisfrank** [comment]
Thanks for the fast response, @qiwzhang.

To make sure I understand, are you saying the expected behavior here is that ESP will ignore the `--service_account_key` flag and try to use a bound k8s service account anyway? This is not how I understood [the service_account_key documentation](https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#platform), which says that ESP will use "the service account key to contact Google services" and only contact the metadata server "if the option is omitted."

If what we're seeing is the expected behavior, and ESPv2 always pings the metadata server for a JWT when serving `x-google-backend` requests that don't use `disable_auth`, does that also imply that `x-google-backend` will only work when running on GCP?

Re: your note about sidecar deployment, we are using ESPv2 as an API gateway. Most of the endpoints happen to be served on localhost by the other container in the pod, but we use `x-google-backend` to delegate a few endpoints to remote microservices. We may extract more endpoints into microservices as needed. This is one of the use cases `x-google-backend` was designed for, correct?

**Comment by qiwzhang** [comment]
`--service_account_key` is used to generating access_token to call Google service. This statement is still correct.  For remote backends specified by the `x-google-backend`,  normally ESP needs to send ID token to the backend. The ID token is representing `who` is running the ESP service so that your remote backend can be setup to only allow ESP to call, not others.   we are calling GCP Metadata server to get the ID token.  This  ID token is not from the SA from `--service_account_key` flag.  

If you need to send ID token from the SA specified in `--service_account_key`, this will be a new feature request. 

In your usage, do you need to send ID token to your remote backend?  If no, you can disable it.

**Comment by chrisfrank** [comment]
> The ID token is representing who is running the ESP service so that your remote backend can be setup to only allow ESP to call, not others.

Excellent, this is exactly what we're trying to do! In our case, the remote backend is also running ESP, so we want to configure ESP in the remote backend to only allow calls from the original ESP. To attempt this, we added a securityDefinition to the remote backend that verifies JWTs issued by the service account specified to the original via `--service_account_key`.

However, given that the JWT is issued by the GCP metadata server and not the service account, its `iss` value is `https://accounts.google.com`. So I think we cannot add a securityDefinition to the target backend that only allows calls from the original ESP. Is that correct? We could add a definition that verifies JWTs issued by accounts.google.com, but wouldn't that allow any process running anywhere inside GCP to fetch a valid token from the metadata server and call our target backend? (They'd need to know the correct JWT audience, I suppose, but I don't think that's a well-guarded secret.)

If this is indeed a feature request, I might frame it as "How can we configure one ESP instance to securely call a second ESP instance via `x-google-backend`"? If that makes sense to you, let me know if you think I should close this issue and file a feature request via our account representative. And you can think of any workarounds in the meantime, I'd be very happy to learn about them. Thank you!

**Comment by qiwzhang** [comment]
All Google ID tokens have the same issuer `https://accounts.google.com` and with same jwks_uri,  same public keys,   It is not safe to use ESP jwt authentication feature for authorization,  since any ID tokens from any service accounts will work.  ESP jwt authentication feature is designed for end-user JWT tokens with unique "iss" and unique jwks public keys,  not for Google ID token.

You have use Google IAM feature to use Google ID token.  Your second ESP needs to be front-ended by a GCLB with IAM support and setup IAM to only allow the first ESP ID token. 

In your setup, it seems it is difficult for the first ESP to get the ID token. So ID token approach may not work for you.

`x-google-backend` ID token feature was designed for calling backends running in GCP serverless platforms, such as Cloud Run, Cloud Function and App-Engine.  All of them support IAM.

**Comment by chrisfrank** [comment]
Okay, thanks very much @qiwzhang. I'll summarize our discussion below. If you could confirm which points I've got right or wrong, I'll go ahead and close this issue. (Are the ESP docs also open source? I'd be able to file a PR to help address these questions in case they come up again.)

- When using `x-google-backend` without `disable_auth`, ESPv2 fetches a Google ID token from the metadata server, regardless of whether `--service_acccount_key` is used.
- It is not possible to configure ESPv2 to sign its own tokens using a service account.
- Using `x-google-backend` without `disable_auth` only works when deployed to GCP. When deployed elsewhere, ESPv2 will still work, but will not generate ID tokens before calling the target backend.
- In a GKE cluster with Workload Identity enabled, if ESPv2 is running with `x-google-backend` (and without `disable_auth`), the user _must_ bind the ESPv2 k8s service account to a GCP service account with appropriate IAM roles. Otherwise ESP will not boot.
- ESPv2 can authenticate requests arriving from another ESPv2 via `x-google-backend` w/o `disable_auth`, but this authentication just verifies that the token is a Google ID token. ESPv2 cannot perform _authorization_ on such requests. Authorization should be implemented in the receiving application, or by deploying the receiving ESP behind a GCLB with IAM.

**Comment by qiwzhang** [comment]
Yes,  all of your summarized points are correct.  Thanks.

**Comment by chrisfrank** [comment]
Great, thank you very much for clarifying the intended behavior. This was tremendously helpful.
