### ISSUE TITLE
Please create a root level OWNERS file

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/esp-v2#5]
Example: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/74845fcac4da83697dbce5e9fba658bd8fb14b6d/OWNERS

/assign @TAOXUY

**Comment by TAOXUY** [comment]
What it is used for, by adding a OWNER files in the root of esp-v2 repo?

**Comment by fejta** [comment]
Similar to inside google. It is how prow's blunderbuss plugin determines who to auto-assign reviews to. It is also how prow's approve plugin decides when to add the approved label

**Comment by TAOXUY** [comment]
Thanks for the information.
We definitely will add this file after we fully migrate to github from gob.

**Comment by nareddyt** [comment]
Jason, you may want to make a PR now.

**Comment by TAOXUY** [comment]
Thanks for the reminder. Will do after the prow fully work.
