### ISSUE TITLE
Cloud Run ESPv2 + Cloud Functions - intermittently returns 403 error 

### ISSUE THREAD

**Issue by trevorlazarus** [GoogleCloudPlatform/esp-v2#508]
Our Cloud Run ESPv2 + Cloud Functions API (built using https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-functions) returns the following 403 error sometimes:

```< HTTP/1.1 403 Forbidden
< Content-Type: text/html; charset=UTF-8
< Referrer-Policy: no-referrer
< Content-Length: 1579
< Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
<
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/</code> from this server.  <ins>That’s all we know.</ins>```

**Comment by trevorlazarus** [comment]
We've double checked the permissions and can confirm that they're set correctly as otherwise successful requests would not be going through.

Could this be an issue related to scaling or availability as the Cloud Functions/Run App are hosted on a single region, while the requests failing are coming in from another region?

**Comment by qiwzhang** [comment]
This 403 error is not from ESPv2 from the page format.   

Could you be more specific on:
1) is this error always happen to a URL?  or only happen sometimes?
2) if you directly call your cloud function, will it work
3) if you call ESPv2,  how did you call it? what URL did you use?  what credential did you pass?  Is jwt auentication required for that URL?  Have you ever successfully called ESPv2?

**Comment by trevorlazarus** [comment]
Hi @qiwzhang, please find my response inline.

1. is this error always happen to a URL? or only happen sometimes?
-- This is only happening for CURL requests sent from a number particular source machines (the source machines have connectivity and can PING Google successfully) 

2. if you directly call your cloud function, will it work
-- I will get access to the source and try this out. As mentioned all other requests from every other source is working fine and we're able to see the logs (both for Cloud Run and Cloud Functions). However we're not able to see the requests that is rejected (possibly by GFE) in either of the logs (Cloud Functions or Cloud Run)

3. if you call ESPv2, how did you call it? what URL did you use? what credential did you pass? Is jwt auentication required for that URL? Have you ever successfully called ESPv2?
-- We're using CURL to call the Cloud Run URL. The API is open and does not require to pass any credentials/keys
-- No JWT Auth is required.
-- All other calls to the ESPv2 other than this source are going through successfully

We've also reached out to GCP support to see if something at the GFE layer is blocking requests from this. 

Thanks again for your help and support with this issue and your prompt response, we really appreciate your help.

**Comment by qiwzhang** [comment]
Sound like it is a GFE issue since the rejected requests did not reach ESPv2.

**Comment by trevorlazarus** [comment]
Leaving a comment for completeness. 

Huge thanks to the esp-v2(https://github.com/GoogleCloudPlatform/esp-v2) team for supporting and a special thanks to @qiwzhang for suggesting to try out the GCF directly!

Turns out it is was a GFE issue, the requests that were sent by our clients were being blocked by GFE as their IPs appeared as originating from a Google embargoed Country!

The Google geo-mapping team are working on fixing this.

Best,
Trevor.
