### ISSUE TITLE
Support of HTTP/2 server for ESP-v2 

### ISSUE THREAD

**Issue by mejuhi** [GoogleCloudPlatform/esp-v2#529]
While going through the documentation of  [Cloud run quota limit ](https://cloud.google.com/run/quotas), it says while using HTTP/1 server there is a limit on request payload size but while using HTTP/2 server we can bypass 32 mb request payload limit. To evaluate the feasibility of using HTTP/2 server (for bypassing the request payload limit) in our project,  it brings to following questions:

1. Is HTTP/2 server is already supported by ESP-v2, 
2. If its is already supported then is there any additional config/flag that needs to be setup/enabled to activate this feature or if it is supported out of the box.

Architecture setup:  [documentation for cloud run  with endpoint](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run) and [documentation for cloud function with endpoint](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-functions)
ESP base image used: [gcr.io/endpoints-release/endpoints-runtime-serverless:2.25](https://console.cloud.google.com/gcr/images/endpoints-release/GLOBAL/endpoints-runtime-serverless?gcrImageListsize=30)

**Comment by qiwzhang** [comment]
Http2 is supported by ESP-v2 out of box.   Your client just need to talk in Http2.

**Comment by mejuhi** [comment]
Thankyou for quick response! It was really helpful for us to understand if and how we can use it our project. :)
