### ISSUE TITLE
Reliable way to determine the `gcloud_build_image` image name

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/esp-v2#543]
Is there a reliable way to determine the image name generated by `gcloud_build_image`?

I'd been using:

```bash
IMAGE=gcr.io/${PROJECT}/endpoints-runtime-serverless:${ESP_HOST}-${CONFIG}
```
But this has recently revised to include the ESP version:

```bash
IMAGE=gcr.io/${PROJECT}/endpoints-runtime-serverless:${ESP_VERS}-${ESP_HOST}-${CONFIG}
```
And I'm currently manually updating the `ESP_VERS` in my script :-(

```bash
gcloud services enable ${ESP_HOST} \
--project=${PROJECT}

# Build an ESPv2 proxy
wget https://raw.githubusercontent.com/GoogleCloudPlatform/esp-v2/master/docker/serverless/gcloud_build_image
chmod +x ./gcloud_build_image

CONFIG="$(\
  gcloud endpoints configs list \
  --service=${ESP_HOST} \
  --project=${PROJECT} \
  --format="json" \
  | jq -r .[0].id)"
./gcloud_build_image \
-s ${ESP_HOST} \
-c ${CONFIG} \
-p ${PROJECT}

# Deploy the ESPv2 proxy in place of the placeholder
ESP_VERS="2.28.0"
IMAGE=gcr.io/${PROJECT}/endpoints-runtime-serverless:${ESP_VERS}-${ESP_HOST}-${CONFIG}

gcloud run deploy ${ESP_NAME} \
--image=${IMAGE} \
--no-allow-unauthenticated \
--platform=managed \
--region=${REGION} \
--project=${PROJECT}
```

**Comment by nareddyt** [comment]
The name change was almost a year ago in #229. We plan to keep the name as `gcr.io/${PROJECT}/endpoints-runtime-serverless:${ESP_VERS}-${ESP_HOST}-${CONFIG}` for the foreseeable future :)

This format is also documented in our tutorials: https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run#configure_esp

**Comment by nareddyt** [comment]
I see, your question is about how to automatically determine the image name in your scripts. You can copy this code snippet into your scripts to get the latest ESPv2 version: https://github.com/GoogleCloudPlatform/esp-v2/blob/59b16174cfce7dd2d37ddbdfa399c642960719ce/docker/serverless/gcloud_build_image#L59-L79

**Comment by DazWilkin** [comment]
Perfect! Thank you.
