### ISSUE TITLE
Ability to retry on specific Http code by using retriable-status-codes policy in backend_retry_ons set for ESPv2 Docker image 

### ISSUE THREAD

**Issue by mejuhi** [GoogleCloudPlatform/esp-v2#551]
[`backend_retry_ons` ](https://github.com/GoogleCloudPlatform/esp-v2/blob/master/src/go/configmanager/flags/flags.go)supports the policies which can be set on [` x-envoy-retry-on`](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-retriable-status-codes) header. One of the possible policy is `retriable-status-codes` which gives the ability to define the HTTP status codes which can be retried, but to define these retriable HTTP status codes additional header needs to be set [`x-envoy-retriable-status-codes`](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-retriable-status-codes)

From the [documented startup options](https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#timeout) it feels like it is not supported yet.

Can you help, in case if i have missed something in the documentation to retry certain http code for eg 500, and in case if [`x-envoy-retriable-status-codes`](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-retriable-status-codes) flag is not supported yet can you let us know if it can be supported?

**Comment by TAOXUY** [comment]
In fact, it has been supported inside ESP-v2; PTAL
https://github.com/GoogleCloudPlatform/esp-v2/blob/master/docker/generic/start_proxy.py#L594-L625

Our Cloud Endpoints doc hasn't been updated for some features we add.

**Comment by mejuhi** [comment]
From the code lines you pointed out, it specifies how to set `backend_retry_ons`, i wanted to know how to specify retriable http status code, in envoy it can be used by configuring envoy header [` x-envoy-retriable-status-codes`](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-retriable-status-codes)

I am still bit confused, apologies if I am missing out something something obvious. It would be really helpful if you can mention the startup option to use in ESP-v2

**Comment by TAOXUY** [comment]
Please see the section under [x-entry-retry-on.retriable-status-codes](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on); It can defined inside the proxy instead of triggering from client headers.

**Comment by mejuhi** [comment]
Is there any documentation/example available on how to define this in proxy. I was not able to find a way to define/edit proxy. I only know how to set client headers in while building docker image  using  espv2 as base image

**Comment by TAOXUY** [comment]
OK, I see; For your request, you need to set
```
x-envoy-retriable-status-codes:["503", "409"...]   #The http codes you wanna retry; 
x-envoy-retry-on: "retriable-status-codes". #This step can be replaced by setting flag `--backend_retry_ons=retriable-status-codes` to ESPv2
```

Yes, you are right. ESPv2 hasn't exposed flags for `x-envoy-retriable-status-codes` set in router;  Are you able to use ``x-envoy-retriable-status-codes` header instead?

We can put this in our FR list but FYI our team is occupied with other higher priority tasks so guarantee when it will be finished.

**Comment by TAOXUY** [comment]
Just saw your another post about cloud function 500 response. Have you considered using other retryOns like 5xx, gateway-error? I will be more cautious to set them in prod but I am assuming you are still debug your setup.

**Comment by TAOXUY** [comment]
Yeah, since it is debugging. You could use --backend_retry_ons=5xx and other retry flags for this 500 error. You don't necessarily need the more granular option.

**Comment by mejuhi** [comment]
We thought to consider adding 5xx in `backend_retry_ons`, but we have quite few business error which will have to be masked, so we were hoping to find a way to retry on specific http error code, since we see that 500 is returned most of the time.

For the debugging, its getting difficult to simulate these scenarios  in any other env, we have only seen it in our prod and with the usual traffic, so not sure can we even debug any further.

We did raise internal ticket on our GCP project, but most we got was that this could be error from GFE between cloud run and cloud function

**Comment by TAOXUY** [comment]
I see your point. You cannot reproduce this error locally so regard this as a mitigation. 

Even you set retrying on 500, is it OK to retry on the business error(you just mentioned)?

We can ingest this FR.

**Comment by mejuhi** [comment]
It will require bit of code change in our services (we are thinking to mask 500 business error code with some other HTTP status code, or make make that services retriable on 500 without loosing the integrity)

Once we do that, we can make 500 retriable from ESP side.
Although its not the nicest solution, but this could be one work around to solve this problem in our prod

**Comment by mejuhi** [comment]
Do you think there can be some way in which ESP is able to differentiate 500 coming from cloud function (bussiness error) and 500 coming from GFE and only retry in case where it was not able to reach the backend service (for eg cloud function/cloud run) at all

**Comment by TAOXUY** [comment]
Whether the rejection comes from GFE or the real backend is transparent to ESPv2 so I also don't have a good solution either. If possible, I would suggest you can fix this on the upstream side as my teammates put in https://github.com/GoogleCloudPlatform/esp-v2/issues/550

**Comment by mejuhi** [comment]
Okay thankyou for detailed explanations!
Do you have any ETA when we can have option to configure `x-envoy-retriable-status-codes` for ESP-v2 image.
Will it be possible to have this feature in the next release? since we are getting quite a few prod issues and we don't have any other proper workaround. It will be really great for us if you can accommodate this FR

**Comment by TAOXUY** [comment]
Hi Mejuhi, again we are out of resource currently. We will try our best if we have time and regarding it is a feature request, no guarantee when it would be ready.

You are super welcomed if you can contribute to our repo and we can help review. This would an [example](https://github.com/GoogleCloudPlatform/esp-v2/pull/436) you can follow, thanks!

**Comment by TAOXUY** [comment]
FYI, I made the https://github.com/GoogleCloudPlatform/esp-v2/pull/554 to resolve this issue .

**Comment by TAOXUY** [comment]
The PR is submitted and should be in the next release. If you don't want to wait, consider using the unreleased ones:
- Cloud Run: gcr.io/cloudesf-testing/apiproxy-serverless:f963f0318a8981e5713b99652f62438ca174fe4b
- GKE/GCE: gcr.io/cloudesf-testing/apiproxy:f963f0318a8981e5713b99652f62438ca174fe4b

It is the one built on the [retry feature PR](https://github.com/GoogleCloudPlatform/esp-v2/pull/554).

**Comment by mejuhi** [comment]
Okay, We will try to use these images for our dev and test env, and for prod we will wait for official release. Thankyou!

**Comment by mejuhi** [comment]
We have done the changes from our side and are ready to move this change to production, but we want to use the official image for production. Can you provide some approx. date when can we have a this feature available in official release?

**Comment by TAOXUY** [comment]
We are going to have an official release this week.

**Comment by mejuhi** [comment]
Okay! Thankyou for the update! :)
