### ISSUE TITLE
 ESPv2 configuration pointing to a different project.

### ISSUE THREAD

**Issue by marcobfj** [GoogleCloudPlatform/esp-v2#559]
Hello! 
I want to raise ESPv2 pointing to a google cloud endpoint configuration that is in a different project that the one that is going to raise ESPv2.

Is it possible?

![image](https://user-images.githubusercontent.com/52581201/124846960-86b79f00-df5f-11eb-80c7-3c0ccc645693.png)

**Comment by TAOXUY** [comment]
It is totally feasible. 

You only need to you grant the sufficient permission of project 2 on the workload identity of project 1 running the GKE cluster.

FYI, please see https://cloud.google.com/endpoints/docs/openapi/get-started-kubernetes-engine-espv2#checking_required_permissions

**Comment by TAOXUY** [comment]
Please note the gcloud cmd should be like 
```
gcloud projects add-iam-policy-binding SERVICE_CONFIG_PROJECT_ID \
        --member serviceAccount:SERVICE_ACCOUNT_NAME@DEPLOYMENT_PROJECT_ID.iam.gserviceaccount.com \
        --role roles/servicemanagement.serviceController

gcloud projects add-iam-policy-binding SERVICE_CONFIG_PROJECT_ID \
        --member serviceAccount:SERVICE_ACCOUNT_NAME@DEPLOYMENT_PROJECT_ID.iam.gserviceaccount.com \
        --role --role roles/cloudtrace.agent
```
as the service project and the proxy deployment project are different.

![image](https://user-images.githubusercontent.com/16471764/124850510-97fbae00-df55-11eb-8ca9-d97a2c1bd312.png)

**Comment by marcobfj** [comment]
Thank you very much for the reply.
Is there a way to do it without using workload identity? It's that I'm only using IAM service accounts.

**Comment by qiwzhang** [comment]
Yes,  if you are using GKE, the deploying service account for ESP is the node service account.  Please check out this [doc](https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#permissions).

You need to add the proper role to that service account as
```
gcloud projects add-iam-policy-binding ENDPOINT_PROJECT_ID \
        --member serviceAccount:SERVICE_ACCOUNT_NAME@DEPLOY_PROJECT_ID.iam.gserviceaccount.com \
        --role roles/servicemanagement.serviceController
```

Where the `ENDPOINT_PROJECT_ID`  is the project owns the endpoint config and `SERVICE_ACCOUNT_NAME@DEPLOY_PROJECT_ID.iam.gserviceaccount.com` is the your node service account.

**Comment by marcobfj** [comment]
I tried this 
`gcloud projects add-iam-policy-binding ENDPOINT_PROJECT_ID \
        --member serviceAccount:SERVICE_ACCOUNT_NAME@DEPLOY_PROJECT_ID.iam.gserviceaccount.com \
        --role roles/servicemanagement.serviceController
`
and still not working. 

This are the logs.
[downloaded-logs-20210709-105010.txt](https://github.com/GoogleCloudPlatform/esp-v2/files/6792546/downloaded-logs-20210709-105010.txt)

**Comment by marcobfj** [comment]
This is the deployment conf 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-endpoints-esp
spec:
  selector:
    matchLabels:
      app: cloud-endpoints-esp
  replicas: 2
  template:
    metadata:
      labels:
        app: cloud-endpoints-esp
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:2
        args: [
          "-s", "develop.ums.cargamos.com",
          "--rollout_strategy", "managed",
          "-z", "healthz",
          "--access_log=/dev/stdout",
          "--underscores_in_headers",
          "--cors_preset=basic",
          "--cors_allow_headers=*",
          "--http_request_timeout_s=600"
        ]
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        ports:
          - containerPort: 8080
```
And this is the SA permission on the cloud endpoints config project. 
![image](https://user-images.githubusercontent.com/52581201/125105809-81b03800-e0a4-11eb-97fb-ea36b28193eb.png)

**Comment by qiwzhang** [comment]
I suspected you used the wrong service account.  GKE usually uses compute engine default service account. 
Its name has this format "12345678-compute@developer.gserviceaccount.com".  Where 12345678 is your project number.

You can confirm which service account is used in the ESP container by talking to GCP Metadata server
1) use kubectl to "exec" into esp container
```
kubectl exec -ti POD  -c ESP-CONTAINER bash
```

2) then curl to GCP metadata server
```
curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/" -H "Metadata-Flavor: Google"
```

It will show which service account it is used.

**Comment by marcobfj** [comment]
You're right, it already worked.
Thanks for the support.

**Comment by qiwzhang** [comment]
I am so glad to hear that it works.
