### ISSUE TITLE
Cloud endpoints with GKE with an app engine backend.

### ISSUE THREAD

**Issue by marcobfj** [GoogleCloudPlatform/esp-v2#567]
Hi! 

We are running ESPv2 on GKE and trying to connect it to an application on App Engine.
We are doing it because that cloud endpoint has many services in k8s but precisely one is in app engine (it is the one that does not respond).
This is the error it throws at us. 
{
    "code": 503,
    "message": "upstream connect error or disconnect/reset before headers. reset reason: connection failure"
}

Cloud endpoint conf: 
```
/test:
  get:
    x-google-backend:
      path_translation: CONSTANT_ADDRESS
      address: http://[SERVICE]-dot-[PROJECT_ID].uc.r.appspot.com/v1/healthz
      deadline: 600.0
    operationId: test
    responses:
      200:
        description: "Success"
        schema:
          $ref: '#/definitions/Response'
```

**Comment by nareddyt** [comment]
Is App engine configured to serve with TLS? If so, the `x-google-backend.address` field must be `https://`.

https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#address

If that does not fix the issue, I will need some logs from ESPv2 to further debug.
1) Turn on the `--enable_debug flag` on ESPv2. https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#debugging
2) Send a request to ESPv2 that causes the 503 error above.
3) Download the ESPv2 application logs. You can follow [this guide](https://cloud.google.com/stackdriver/docs/solutions/gke/using-logs) to find the logs associated with the ESPv2 `k8s_container` resource.
4) Email them to me (nareddyt@google.com).

**Comment by marcobfj** [comment]
Hi!
I already changed the configuration so that it has https.
```
 /v1/healthz:
    get:
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS
        address: https://cdp-dot-cargamos-dev-1.uc.r.appspot.com
        jwt_audience: 932830985048-o1f74vk0hrop04b6j29tpg7j7duh8u4a.apps.googleusercontent.com
        deadline: 600.0
      security:
        - api_key: []
      description: healthz
      summary: healthz
      operationId: healthz
      tags:
        - Orders
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: "Success"
          schema:
            $ref: '#/definitions/ResponseGet'
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/Error'
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
```
And I sent you the email with the logs, I hope they work.
Greetings.

**Comment by marcobfj** [comment]
Hi! 
I was wondering if you could find any clues to help me. 
I sent you the email as you requested.
Best regards.

**Comment by nareddyt** [comment]
I don't think you sent me enough logs. I took a look and all the logs are for the automated health check you have.

```
    "textPayload": "D0720 21:57:55.998 37 envoy] [37][filter]get operation_name: espv2_deployment.ESPv2_Autogenerated_HealthCheck",
```

ESPv2 is responding to these with `HTTP 200 OK` as expected.

I do not see any logs for the request that causes the `HTTP 503` you mentioned above.

Can you try disabling health checks and doing the steps in my previous comment again? Or if you cannot disable health checks, try to download the logs around the time you sent the bad request.

**Comment by marcobfj** [comment]
Here are the new logs. 
[downloaded-logs-20210804-110752.txt](https://github.com/GoogleCloudPlatform/esp-v2/files/6932738/downloaded-logs-20210804-110752.txt)

And this is the section that marks the error 

![image (2)](https://user-images.githubusercontent.com/52581201/128216183-8dbc0e89-18fd-4ca8-a8ea-78857811175d.png)

**Comment by nareddyt** [comment]
The txt file you sent me does not have the corresponding logs that are in the image you pasted. I need to see those log lines and the context around them.

Based on the minimal information in the image you pasted, one thing that stuck out to me is the `connection to [...` lines. ESPv2 is using IPv6 addresses. Maybe this is not supported by App Engine.

Can you try configuring ESPv2 with the `--backend_dns_lookup_family=v4only` startup flag? https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#platform

If that does not work, please provide the same logs in the image as a txt file (and any surrounding logs that will help provide context).

**Comment by marcobfj** [comment]
I tried `--backend_dns_lookup_family=v4only` and it worked! :) 

Thank you very much for the help!

**Comment by marcobfj** [comment]
Hello again.
The request is already coming to app engine, the problem is that we are using IAP for authentication and apparently the token is not reaching it well when the request is made through ESP.
We suspect that the token is being uploaded before reaching the app engine.

The message error `Invalid IAP credentials: JWT 'email' claim isn't a string`

**Comment by nareddyt** [comment]
So your client is already sending a token, and you do not want ESPv2 to modify it? Then you need to set `disable_auth` in `x-google-backend`. Please read over this section: https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#jwt_audience_disable_auth
