### ISSUE TITLE
How to specify CORS for multiple origins 

### ISSUE THREAD

**Issue by MoSehsah** [GoogleCloudPlatform/esp-v2#568]
Hi Community,

We would like to use the flag `--cors_allow_origin` to include multiple hosts. Is this possible? if yes then how? 

If the only option to do that is to use `--cors_allow_origin_regex` then what's the reference that we can use to provide a valid regular expression? 

Thanks 🙏

**Comment by TAOXUY** [comment]
Hi MoSehsah, `--cors_allow_origin` only support the exact match for single host.

For `--cors_allow_origin_regex`, envoy use the Google [RE2 engine](https://regoio.herokuapp.com/) underlying. Possibly, you can use this online [RE validator](https://regoio.herokuapp.com/), which claims implemented based on Google RE2.

**Comment by MoSehsah** [comment]
Thanks 👍🙏
