### ISSUE TITLE
HTTP status code 401 (response_code_detail: "via_upstream") while calling Cloud Function by Cloud Run running "gcr.io/endpoints-release/endpoints-runtime-serverless:2.24" as base image

### ISSUE THREAD

**Issue by mejuhi** [GoogleCloudPlatform/esp-v2#569]
We got this error in prod, where cloud run ESP was not able to reach cloud function and returned 401. This looks similar to the error we have been getting in #550 

Adding screenshot when searched with traceid
![image](https://user-images.githubusercontent.com/45816852/127116920-2ac2d67e-6689-4312-a476-c81244642d3f.png)

log on cloud endpoint

```
{
  "insertId": "<insertId-value>",
  "jsonPayload": {
    "location": "europe-west1",
    "http_status_code": 401,
    "api_name": "1.<CloudRunESP-url>",
    "api_version": "1.0.0",
    "log_message": "1.<CloudRunESP-url>.<api-name> is called",
    "response_code_detail": "via_upstream",
    "producer_project_id": "<project-name>",
    "service_agent": "ESPv2/2.24.0",
    "service_config_id": "2020-11-30r0",
    "api_key": "<api-key>",
    "api_key_state": "VERIFIED",
    "api_method": "1.<CloudRunESP-url>.<api-name>",
    "timestamp": 1627307978.8599014
  },
  "httpRequest": {
    "requestMethod": "POST",
    "requestUrl": "/<api-path>",
    "requestSize": "2911",
    "status": 401,
    "responseSize": "781",
    "remoteIp": "212.244.52.32",
    "latency": "0.006s",
    "protocol": "http"
  },
  "resource": {
    "type": "api",
    "labels": {
      "version": "1.0.0",
      "method": "1.<CloudRunESP-url>.<api-name>",
      "project_id": "<project-name>",
      "service": "<service-name>",
      "location": "europe-west1"
    }
  },
  "timestamp": "2021-07-26T13:59:38.859901376Z",
  "severity": "ERROR",
  "logName": "projects/<project-name>/logs/<service-name>%2Fendpoints_log",
  "trace": "projects/<project-name>/traces/<trace-id>",
  "receiveTimestamp": "2021-07-26T13:59:40.486838978Z"
}
```

wanted to know if there is any reason for Cloud run ESP is getting 401 and how to mitigate this issue

**Comment by TAOXUY** [comment]
For 401 `Unauthorized`, it is the client side error that the client is unauthenticated and it should be some problem in the config. It doesn't work before, right?


Could you please check if you have done the step 4 of [Deploying the ESPv2 container](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-functions#deploy_esp)? Essentially, the service account running ESPv2 should has the role of `roles/cloudfunctions.invoker` in the backend project.

If you haven't grant the permission to the SA, please do that and verify the SA has the right permission by [locally calling](https://cloud.google.com/functions/docs/securing/authenticating#authenticating_developer_testing) your Cloud Function backend directly using your SA. If it passes, ESPv2 should work.

**Comment by mejuhi** [comment]
Yes, we have set all the right permission, this is service is in production and was working fine before and after this error, it is an isolated case, but still odd enough for it to suddenly appear when no changes on any service account or cloud run and cloud function was done.

**Comment by TAOXUY** [comment]
Does it still occur? Is it reproduceable? How many are they?

Look like it is a bug on the Cloud Function side.

**Comment by mejuhi** [comment]
So far one, not sure how to reproduce it
It seemed bit odd for it to throw 401 unauthorized without any further details/logs given env was untouched

**Comment by TAOXUY** [comment]
If it only happens once and not reproduceable, it would be hard for Cloud Function team to debug this. If you want to Cloud Function to debug this issue, could you please send the raw access log to my email taoxuy@google.com and I can issue a bug internally?
