### ISSUE TITLE
cors_preset=basic is broken

### ISSUE THREAD

**Issue by zhaytee** [GoogleCloudPlatform/esp-v2#578]
Hi all,

cors_preset=basic has been working for us until today. Now, ESPv2 will only accept `Origin: *` (yes, with a literal asterisk character). It will reject any other Origin header with this message:

```
{"message":"The CORS preflight request is missing one (or more) of the following required headers [Origin, Access-Control-Request-Method] or has an unmatched Origin header.","code":400}
```

**Comment by nareddyt** [comment]
We recently released ESPv2 v2.30.0 with this PR: https://github.com/GoogleCloudPlatform/esp-v2/pull/575

I see, it seems like we default the `--cors_allow_origin` flag to `*` here: https://github.com/GoogleCloudPlatform/esp-v2/blob/24a0bebeba8a54ad5a4906bff5b02b86d5ec2df7/docker/generic/start_proxy.py#L344

We did not realize `*` origin was allowed with `--cors_preset=basic`. The PR above will break your traffic then. I will rollback the new release and make ESPv2 2.29.1 the latest stable. Sorry for the confusion, thanks for notifying us.

**Comment by goulashify** [comment]
@nareddyt: automated build tools based on the gcloud bash script will still take 2.30.0 up as the latest. 

If you can, it would be nice to remove the image.

**Comment by qiwzhang** [comment]
Following Docker images with tag "2.30" and "2.30.0" are deleted.

gcr.io/endpoints-release/endpoints-runtime-serverless:2.30.0
gcr.io/endpoints-release/endpoints-runtime:2.30.0

**Comment by nareddyt** [comment]
> automated build tools based on the gcloud bash script will still take 2.30.0 up as the latest.

Just FYI - the tooling will *not* do this. It currently looks for the `2` tag and picks up `2.29.1`

```
Using base image: gcr.io/endpoints-release/endpoints-runtime-serverless:2
Determining fully-qualified ESP version for tag: 2
Building image for ESP version: 2.29.1
```

**Comment by MrMage** [comment]
FYI, the removal of the `2.30` Docker image tag has broken a few of my production instances. I usually specify the minor version (i.e. `2.30` instead of `2` or `latest`) to be able to upgrade on my own schedule. Pulling the `2.30` images then made my instances fail because the image I specified were no longer available.

I wonder if it would make sense to temporarily redirect e.g. the `2.30` images to `2.29` until a fixed `2.30.1` is released in such cases?

**Comment by nareddyt** [comment]
Yes, it was out mistake to delete the image once it is pushed. We will be careful not to do this in the future.

**Comment by qiwzhang** [comment]
Tag "2.30" to "2.29" is wrong.   I will see if I can re-install 2.30.0 image and tag 2.30 to it.

**Comment by qiwzhang** [comment]
OK,  I have restored tags 2.30 and 2.30.0 for following images:

gcr.io/endpoints-release/endpoints-runtime-serverless:2.30.0
gcr.io/endpoints-release/endpoints-runtime:2.30.0
