### ISSUE TITLE
Multiple gRPC Services, one endpoint

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/esp-v2#584]
I'm struggling to publish 2 distinct gRPC services (my application and the generic healthcheck service) with Cloud Endpoints.

Ref: https://github.com/GoogleCloudPlatform/esp-v2/issues/434 and a proposed [example](https://github.com/GoogleCloudPlatform/esp-v2/issues/434#issuecomment-740191187)

I have a working Cloud Endpoints deployment (hosted on Cloud Run).

The gRPC server comprises my application service and the Golang [implementation](https://github.com/grpc/grpc-go/tree/master/health) of [`health.proto`](https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto)

I realized I'd forgotten to include the health(checking) service in the gRPC service config and am, of course, unable to access it through the proxy:

```console
code = Unimplemented
desc = {"code":404,"message":"The current request is not defined by this API."}"
```

I added the service to the config:

```YAML
type: google.api.Service
config_version: 3
apis:
  - name: v1alpha1.SomeService
  - name: grpc.health.v1.Health
...
```

And I generated a descriptor for the `health.proto` service (`health.pb`)

But I'm unable to `gcloud endpoints services deploy` the two gRPC services:

```bash
gcloud endpoints services deploy health.pb myservice.pb myconfig.yaml --project=${PROJECT}
ERROR: (gcloud.endpoints.services.deploy) INVALID_ARGUMENT: Cannot convert to service config.
'location: "myconfig.yaml:7"
kind: ERROR
message: "Cannot resolve api \'grpc.health.v1.Health\'."
'
```
If I invert the pb files, it errors with my service:

```bash
gcloud endpoints services deploy myservice.pb health.pb myconfig.yaml --project=${PROJECT}
ERROR: (gcloud.endpoints.services.deploy) INVALID_ARGUMENT: Cannot convert to service config.
'location: "myconfig.yaml:6"
kind: ERROR
message: "Cannot resolve api \'v1alpha1.SomeService\'."
'
```
[`gcloud endpoints services deploy`](https://cloud.google.com/sdk/gcloud/reference/endpoints/services/deploy) accepts two service configs but it appears (!?) to be challenged with more than 2.

Some time ago, @qiwzhang [suggested](https://github.com/GoogleCloudPlatform/esp-v2/issues/523#issuecomment-854937808) I try combining a gRPC and a REST service by manually editing a deployed service config (`gcloud endpoints config describe`), is that approach more likely to work with 2 gRPC services?

Am I approaching this incorrectly?

<hr/>

```bash
grpcurl \
-H "Authorization: Bearer ${TOKEN}"  \
-d "{\"customer_id\": \"${CUSTOMER_ID}\"}" \
-proto some.proto \
${PROXY}:${PORT} \
v1alpha1.SomeService/SomeMethod
{
  "customer": {
    "name": "Daz Wilkin",
    "enabled": true
  }
}
```
And:
```bash
grpcurl \
-H "Authorization: Bearer ${TOKEN}" \
 -d "{\"service\": \"freddie\"}" \
-proto health.proto \
${PROXY}:${PORT} \
grpc.health.v1.Health/Check
ERROR:
  Code: Unimplemented
  Message: {"message":"The current request is not defined by this API.","code":404}
```

**Comment by qiwzhang** [comment]
Can you try to use "protoc" to combine two proto files into one descriptor file?

When "gcloud endpoints service deploy" takes two config files, one has to be the proto descriptor and another the yaml file.

**Comment by DazWilkin** [comment]
Thank you for the prompt reply!

I tried that and received errors:

```bash
protoc \
--include_imports \
--include_source_info \
--proto_path=. \
--descriptor_set_out=combined.pb \
--go_out=./api/v1alpha1 \
--go_opt=module=${MODULE} \
--go-grpc_out=./api/v1alpha1 \
--go-grpc_opt=module=${MODULE} \
./myservice.proto \
./health.proto
```
Yields:
```console
--go_out: google.golang.org/grpc/health/grpc_health_v1/health.pb.go: 
generated file does not match prefix "github.com/[[REDACTED]]"
```

Seeing your comment, I realized I don't need to generate the Golang sources in order to generate the descriptor:

```bash
protoc \
--include_imports \
--include_source_info \
--proto_path=. \
--descriptor_set_out=combined.pb \
./myservice.proto  \
./health.proto
```

I'm going to try deploying that, please give me 15 minutes to try it.

> **NOTE** Would it be prudent to revise the documentation to be clearer on this point: When "gcloud endpoints service deploy" takes two config files, one has to be the proto descriptor and another the yaml file.?

**Comment by DazWilkin** [comment]
Outstanding!

Thank you @qiwzhang 

```bash
grpcurl \
> -H "Authorization: Bearer ${TOKEN}" \
> -d "{\"service\": \"\"}" \
> -proto health.proto \
> ${ESP_HOST}:443 \
> grpc.health.v1.Health/Check
{
  "status": "SERVING"
}
```

**Comment by qiwzhang** [comment]
Will update the doc.  Thanks.
