### ISSUE TITLE
Loadbalancing possibility on ESPv2 with x-google-backend.address

### ISSUE THREAD

**Issue by mejuhi** [GoogleCloudPlatform/esp-v2#587]
Apologies if this is already supported, but was not able to find any documentation for it.

We were looking forward for a feature that could allow us to mention list of Cloud function/Cloud run URL in  x-google-backend.address rather than URL of 1 cloud Function/Run. This could be then used for managing traffic among those backends.

Is this feature supported or could be supported in future?

**Comment by qiwzhang** [comment]
No,  unfortunately, we don't support such load balancing feature in ESPv2.

**Comment by mejuhi** [comment]
Okay! Thankyou!
