### ISSUE TITLE
Add X-User-Agent to default --cors_allow_headers.

### ISSUE THREAD

**Issue by nsadeh** [GoogleCloudPlatform/esp-v2#595]
Hello,

I am configuring CORS on an ESPv2 container. I need to allow an additional header (X-User-Agent, which is used by grpc-web - this should probably be on by default for basic CORS settings, since it's supposed to support grpc-web out of the box). I added 

`ENV ESPv2_ARGS ^++^--cors_preset=basic++--cors_allow_headers="DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-User-Agent"`

in the place denoted [here](https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#cloud_run_for_serverless_platforms) and built the container. Then I deployed my container, but the CORS settings did not change in my service.

**Comment by nareddyt** [comment]
Your steps look good to me.

How did you confirm the CORS settings did not change? You sent a preflight CORS request and the `Access-Control-Allow-Headers` response header is missing `X-User-Agent`?

Let's look the the debug logs for the ESPv2 container. Add the `--enable_debug` flag to the `gcloud_build_image` script and redeploy the new container. View the Cloud Run application logs for the ESPv2 Cloud Run service. You can search for a log line like "adding cors route configuration". In this log line, do you see the `X-User-Agent` header?

**Comment by nsadeh** [comment]
@nareddyt I ended up powering past this issue by setting cors-allow_headers="*" directly in the . I have limited understanding of CORS but this seems insecure to me, so I do want to taper it down again to only basic+X-User-Agent.

Q: How did you confirm the CORS settings did not change?
A: I went in the service's YAML settings and saw that the ESPv2_ARGS variable was unchanged.

I'll try to re-deploy the container sometime soon without the blanket headers permissions to debug. In the meantime, I do want to get back to the point that `X-User-Agent` should be part of the `basic` headers allowed, since the documentation for ESPv2 states that it's compatible with grpc-web out of the box and that header is required to get it to work.

**Comment by nsadeh** [comment]
(didn't mean to close the issue - misclick)

**Comment by nareddyt** [comment]
> I went in the service's YAML settings and saw that the ESPv2_ARGS variable was unchanged.

When you change the ESPv2 startup flags, the changes will not show up in the service YAML. The service YAML describes your API at config time, but the startup flags change server behavior at runtime.

Reducing down the allowed headers make sense. CORS is a tricky topic, so I understand the confusion. Here is the correct way to test changes to the `--cors_allow_headers`:
1. Deploy the ESPv2 container built with the `ENV ESPv2_ARGS` above.
2. Send a [preflight CORS request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) from your client. You can use `curl` or Postman.
3. Verify the response contains the `X-User-Agent` header with the desired value. 

If the response contains that header, then ESPv2 is working fine. The problem may be somewhere else.

> X-User-Agent should be part of the basic headers allowed, since the documentation for ESPv2 states that it's compatible with grpc-web out of the box and that header is required to get it to work.

@qiwzhang WDYT? This should not break any pre-existing clients, right?

**Comment by qiwzhang** [comment]
@nareddyt  we can add X-User-Agent as the default allowed headers.  It should be safe.
