### ISSUE TITLE
ESP 2.30.2 crashes locally

### ISSUE THREAD

**Issue by nsadeh** [GoogleCloudPlatform/esp-v2#597]
I am running an ESPv2 container following the instructions on the Google Cloud documentations. For versions 2.30.2, and all  versions after 2.7 that I checked (did not check every single one), ESP runs for about a minute, hangs on the HTTP Manager Config stage (listener_generator.go:112), then crashes with 
```
CRITICAL: Envoy is down, killing all processes.
I0910 15:42:25.527380      11 config_manager.go:294] Envoy Dynamic Configuration is cached for service: gateway-job6uekyvq-ue.a.run.app
I0910 15:42:25.527819      11 rollout_id_change_detector.go:59] start detect latest rollout id every 1m0s
I0910 15:42:25.527962      11 config_manager.go:193] create new Config Manager for service (gateway-job6uekyvq-ue.a.run.app) with configuration id (2021-09-10r6), managed rollout strategy
I0910 15:42:25.533045      11 server.go:66] config manager server is running at @espv2-ads-cluster .......
[2021-09-10 15:42:25.522][29][critical][assert] [external/envoy/source/common/signal/signal_action.cc:62] assert failure: sigaltstack(&stack, &previous_altstack_) == 0.
qemu: uncaught target signal 6 (Aborted) - core dumped
```

I am currently working with 2.7, but the downside is that I can't pass the override flag [--enable_backend_address_override](https://cloud.google.com/endpoints/docs/grpc/specify-esp-v2-startup-options#testing). This forces me to create two ESP configs and two ESP deployments, one for production and one for local hosted backend for when I iterate on the frontend of my app.

**Comment by TAOXUY** [comment]
Could you please run ESPv2.30.2 with --enable_log and send the log and your service config to `esp-eng@google.com`? 


How to get service config?
```
SERVICE= # Your service name
CONFIG_ID= # The config id of your service, you should be able to see them under API&Service on Cloud Console.
curl --fail -o "service.json" -H "Authorization: Bearer $(gcloud auth print-access-token)" \
  "https://servicemanagement.googleapis.com/v1/services/${SERVICE}/configs/${CONFIG_ID}?view=FULL"
```

**Comment by nsadeh** [comment]
@TAOXUY done, thanks for your support.

**Comment by nsadeh** [comment]
Actually I just got a mail delivery failure for this address, is there another you can provide?

**Comment by qiwzhang** [comment]
you can send the log to me at qiwzhang@google.com

**Comment by qiwzhang** [comment]
From the debug log, Envoy failed to install signal_stack [here](https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/common/signal/signal_action.cc#L62).  Something wrong with the host machine.   

In this case,  the host machine is M1.  That maybe the case.
