### ISSUE TITLE
A lot of deprecation warnings on startup about using `envoy.config.route.v3.HeaderMatcher.exact_match`

### ISSUE THREAD

**Issue by daaain** [GoogleCloudPlatform/esp-v2#600]
I'm in the process of migrating from the ESP v1 image with GKE OpenAPI Cloud Endpoints and managed to get v2 working, but getting about a 100 or so of these deprecation warnings on startup.

Just wanted to check if this is something you're aware of? Is it because of some configuration I need to update? If not, is it something that needs to be fixed internally in this image?

Thanks in advance!

```
W0913 16:48:08.571 17 envoy] [17][misc]Deprecated field: type envoy.config.route.v3.HeaderMatcher Using deprecated option \'envoy.config.route.v3.HeaderMatcher.exact_match\' from file route_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
```

**Comment by qiwzhang** [comment]
Yes,  we will fix these warning.  Thanks for reporting.  

-Wayne
