### ISSUE TITLE
FR: Parameterize `gcloud_build_image` output image name

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/esp-v2#609]
`gcloud_build_image` [binds to GCR](https://github.com/GoogleCloudPlatform/esp-v2/blob/f26b351139f3577511d61817db184bb043229e00/docker/serverless/gcloud_build_image#L103) while Google is discouraging Google Container Registry's (GCR) use in favor of Google Artifact Registry (GAR):

![image](https://user-images.githubusercontent.com/1022400/134708091-49f8c894-0ec5-40ab-9b25-ef39d602a0fc.png)

Perhaps an additional flag could be added to `gcloud_build_image` to specify the output image name?

This would permit:

+ using e.g. a GAR repository instead of GCR
+ not having to enable GCR in a project for ESP
+ not having to sed `gcloud_build_image`

**Comment by qiwzhang** [comment]
Thanks.  It is a reasonable request.

**Comment by DazWilkin** [comment]
Awesome! Thank you
