### ISSUE TITLE
`gcloud_build_image` registry parameter incorrectly (for Artifact Registry) inserts GCP Project ID

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/esp-v2#612]
Thanks for responding so promptly to #609 with #610 

Unfortunately, this is incorrect for Google Artifact Registry (GAR). 

Using GAR, container image repositories have the form:

```
${REGION}-docker.pkg.dev/${PROJECT}/${REPOSITORY}
```

> **NOTE** Where `${REPOSITORY}` is a short name. Users are prompted to create repositories by such a short name but they're only ever accessible using a fully-qualified name of the form as shown above. The fully-qualified repository name (already) includes the Project ID (`${PROJECT}`).

Image paths in these repositories are:

```
${REGION}-docker.pkg.dev/${PROJECT}/${REPOSITORY}/${IMAGE}:${TAG}
```

In this line of `gcloud_build_image`, the :

https://github.com/GoogleCloudPlatform/esp-v2/blob/805904a9c84372a0bfdce14ac7caa897dbbdb18f/docker/serverless/gcloud_build_image#L111

`${PROJECT}` is duplicated (before and after the repository name) and is thus incorrect when using the newly added `-g` flag:

```
${REGION}-docker.pkg.dev/${PROJECT}/${REPOSITORY}/${PROJECT}
```

And thus the image path is incorrect too.

If a user specifies a repository using `-g`, `gcloud_build_image` should simply append the determined `image:tag`

**Comment by qiwzhang** [comment]
Hmm,  per my reading from this [doc](https://cloud.google.com/artifact-registry/docs/docker/names).  

Image name has following format
```
LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY
```

In our case, the REPOSITORY is
```
endpoints-runtime-serverless:${ESP_FULL_VERSION}-${SERVICE}-${CONFIG_ID}
```

will this not work?
