### ISSUE TITLE
Letsencrypt recent cert expiry breaks JWKs download

### ISSUE THREAD

**Issue by skymeyer** [GoogleCloudPlatform/esp-v2#615]
Because of the [recent expiry](https://docs.certifytheweb.com/docs/kb/kb-202109-letsencrypt/) of Letsencrypt's `DST Root CA X3` and its intermediate CA `R3`, all of our ESPv2 sidecars stopped working no longer able to fetch JWKs from our endpoint which uses Letsencrypt issued certs.

```
[26][jwt]Jwks async fetching url=https://***redacted***/.well-known/jwks.json: failed
```

This was experienced on both ESP `v2.30.2` as well as `v2.29.1`. When using `--enable_debug` we could observe this:
```
09:20:35.992 28 envoy] [28][router][C0][S6749944153606445985] performing retry
 09:20:35.992 28 envoy] [28][pool]queueing stream due to no available connections
 09:20:35.992 28 envoy] [28][pool]trying to create new connection
 09:20:35.992 28 envoy] [28][pool]creating a new connection
 09:20:35.992 28 envoy] [28][client][C16] connecting
 09:20:35.992 28 envoy] [28][connection][C16] connecting to 104.198.8.106:443
 09:20:35.992 28 envoy] [28][connection][C16] connection in progress
 09:20:35.993 28 envoy] [28][connection][C16] connected
 09:20:35.995 28 envoy] [28][connection][C16] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
 09:20:35.995 28 envoy] [28][connection][C16] closing socket: 0
 09:20:35.995 28 envoy] [28][connection][C16] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
 09:20:35.996 28 envoy] [28][client][C16] disconnect. resetting 0 pending requests
 09:20:35.996 28 envoy] [28][pool][C16] client disconnected, failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
 09:20:35.996 28 envoy] [28][router][C0][S6749944153606445985] upstream reset: reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

Testing `openssl` from within the sidecar passed and Qualys SSL Lab test was showing the trust chain correctly for our endpoint.

```
openssl s_client -connect ***redacted***:443 -servername ***redacted***
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = ***redacted***
verify return:1
---
Certificate chain
 0 s:CN = ***redacted***
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
subject=CN = ***redacted***
issuer=C = US, O = Let's Encrypt, CN = R3
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4705 bytes and written 408 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
...
    Start Time: 1633084843
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes

```

However it seems Envoy/BoringSSL was still preferring to validate through the expired `DST Root CA X3` instead of `ISRG  Root X1` (see https://letsencrypt.org/certificates/). The only solution we were able to come up with was explicitly excluding `DST Root CA X3` from the trusted root CA's on our container build:

```
ARG ENDPOINTS_RUNTIME_ARG
FROM gcr.io/endpoints-release/endpoints-runtime:${ENDPOINTS_RUNTIME_ARG} as base

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt \
    && sed -i '/DST_Root_CA_X3/d' /etc/ca-certificates.conf \
    && update-ca-certificates

USER envoy
```

Not sure if this is a BoringSSL bug or some configuration flag we overlooked. Hope this helps out others who run into this same issue.

**Comment by nareddyt** [comment]
Thanks for reporting the issue, this is surprising. @qiwzhang do you have any ideas on which component (Envoy or BorringSSL) is using the wrong validation chain?

More references on root certificate expiry: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by skymeyer** [comment]
Seems there is some more fallout related to this - BoringSSL starts looking like a decent suspect here.

![image](https://user-images.githubusercontent.com/593516/135680039-2bde8b05-adc2-4b2b-ace7-21f04d12f68a.png)

**Comment by rudi-ct** [comment]
i noticed BoringSSL forked from OpenSSL at v1.0.1 before 1.0.2 was released. Wonder if that could be part of the problem...
https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/

**Comment by nareddyt** [comment]
We confirmed with the BoringSSL team that they will have a fix for this issue early next week. It may take more time for Envoy, then ESPv2 to be updated.

In the time being, the workaround provided in the issue description should work fine if you are affect. Thanks @skymeyer for provided this information!

**Comment by nareddyt** [comment]
Just FYI: BoringSSL fixed the issue here: https://boringssl.googlesource.com/boringssl/+/8f5eb80b810ff63d14ad3535cb16f7cb8271a4f5%5E%21/

I'm unsure how long it will take to bubble up this dependency update to ESPv2
