### ISSUE TITLE
ESPv2  takes too long to process requests.

### ISSUE THREAD

**Issue by marcobfj** [GoogleCloudPlatform/esp-v2#635]
Hello. 
Hi, I have ESPv2 deployed on a GKE cluster and in my use case I have a load balancer at the edge of the topology. 
The problem is this: when I do some requests to the load balancer and it pass to ESPv2 takes too long to process the requests and others pass with an acceptable time. 
I deploy ESPv2 with flag **enable_debug** to see any error but there is no one, instead all the requests I made return a 200 code and I can't see any wear behaviour.  
I make the same requests inside the ESPv2 pod to my service and all of them work fine, only when they passed through ESPv2  the "issue" appears.
 
These are the logs from my service:
![image](https://user-images.githubusercontent.com/52581201/140581927-2cbed6ee-d6c0-4532-8e27-23e5048229da.png)

These are the logs from ESPv2:
![image](https://user-images.githubusercontent.com/52581201/140582012-30a88a10-33b4-4d1c-b7d6-6c13e16b9301.png)

And these are the requests from ESPv2 pod to My Service: 
![image](https://user-images.githubusercontent.com/52581201/140582304-e1e38437-3ce0-4640-8919-755b32a0d121.png)

And these are the logs from the service when I did he requests from ESPv2 pod. 
`10.156.3.209 - - [05/Nov/2021:21:29:14 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.68.0"
10.156.3.209 - - [05/Nov/2021:21:29:15 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.68.0"
10.156.3.209 - - [05/Nov/2021:21:29:16 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.68.0"
10.156.3.209 - - [05/Nov/2021:21:31:23 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.68.0"
10.156.3.209 - - [05/Nov/2021:21:31:23 +0000] "GET /docs HTTP/1.1" 200 1636108 "-" "curl/7.68.0"
10.156.3.209 - - [05/Nov/2021:21:31:23 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.68.0"
10.156.2.53 - - [05/Nov/2021:21:55:10 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:12 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:12 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:13 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:14 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:14 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:21 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:21 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:22 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:22 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:23 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"
10.156.2.53 - - [05/Nov/2021:21:55:23 +0000] "GET /docs HTTP/1.1" 200 1636277 "-" "curl/7.64.0"`

Thanks! And let me now if I can help you with something.

**Comment by qiwzhang** [comment]
Could you look at "trace" page?   In Cloud Console, you go to "Trace" and "Trace list" pages

**Comment by marcobfj** [comment]
I can't see any trace from this service, Do I need to enable something?

**Comment by qiwzhang** [comment]
Maybe you don't have enough samples.  You can increase trace_sampling_rate by using flag
```
--tracing_sample_rate=1.0
```

**Comment by marcobfj** [comment]
I did it. 
![image](https://user-images.githubusercontent.com/52581201/140814912-36d7107b-74eb-418b-a98b-6157ffd9c63c.png)

This is what can I see

**Comment by marcobfj** [comment]
And here is another one 
![image](https://user-images.githubusercontent.com/52581201/140816884-bf9050c1-e671-4f31-8965-9fd1c2e2ead5.png)

**Comment by marcobfj** [comment]
Here is `router BACKEND egress`
![image](https://user-images.githubusercontent.com/52581201/140818297-58d40464-5334-41b5-9163-c2a31e46cabe.png)

**Comment by nareddyt** [comment]
I see the response flag `UC`, which means "Upstream connection termination in addition to 503 response code."

It is not a problem with Cloud ESF, it is functioning as expected and publishing the correct telemetry. It seems like your backend is causing the latency. `UC` means your backend server is closing the TCP connection too early (before sending a full response back to Cloud ESF). The backend may be overloaded? https://httpstatuses.com/503

Do you have any mechanisms to debug your backend? Maybe some logs from your backend that could help trace down the latency?

**Comment by marcobfj** [comment]
Yes I have. 
Thanks for your help. :)
