### ISSUE TITLE
Transcoding with application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by annp1987** [GoogleCloudPlatform/esp-v2#648]
Hi team,

I got an error as below when trying to send a HTTPs request with content-type: application/x-www-form-urlencoded
```
{
    "message": "Unexpected token.\nname=%22testing%22\n^",
    "code": 400
}
```
Is there any way to make esp-v2 accept kind of request?

**Comment by qiwzhang** [comment]
Per my understanding,  `content-type: application/x-www-form-urlencoded`  put `name=value` pairs in the POST body. Not in the query parameters.  We don't support such format.

**Comment by annp1987** [comment]
@qiwzhang: Thank you for your response. Happy New Year!
