### ISSUE TITLE
Question: Does esp-v2 support client streaming RPC?

### ISSUE THREAD

**Issue by annp1987** [GoogleCloudPlatform/esp-v2#652]
Hi,

I have a question: Does the esp-v2 support client streaming RPC (https://grpc.io/docs/what-is-grpc/core-concepts/#client-streaming-rpc)? I don't find any document to mention it. So I create an issue about it.

Thanks,

**Comment by nareddyt** [comment]
Thanks for the question. Yes, ESPv2 supports both client and server streaming RPCs.

We have a test that verifies client gRPC streaming here: https://github.com/GoogleCloudPlatform/esp-v2/blob/master/tests/integration_test/grpc_streaming_test/grpc_streaming_test.go
