### ISSUE TITLE
POST not working from Cloud Endpoint Developer Portal with --cors_preset flag

### ISSUE THREAD

**Issue by stefaneacsu** [GoogleCloudPlatform/esp-v2#656]
At the moment we use a Cloud Run application that creates and deploys an ESPv2 with OpenAPI v2 and deploys a new revision to Cloud Run. (We have set up to allow all unauthenticated at the moment just to test)

We want to use the Developer Portal that it's included and from Postman since it's local everything works fine we can do a POST, GET with random data and everything works fine.

But from the Cloud Endpoints Developer Portal, we can do a GET and everything looks fine but when we do a POST with some random data in the Network tab we get the error that it's a CORS issue.

We have followed the following documentation (https://cloud.google.com/endpoints/docs/openapi/support-cors#handle_cors_with_or) and we added the "--set-env-vars=ESPv2_ARGS=--cors_preset=basic" variable in order to enable CORS and see if this would work.

The issue still persists and I am not sure what it is wrong? We plan to handle CORS in our application backend but at the moment until it's added we would at least try to fix it and see what it's not correct.

**Comment by qiwzhang** [comment]
Unfortunately,  we don't know much about Cloud Endpoint Developer Portal.  You can try to debug it by turn on --enable_debug when deploying ESPv2.   I bet that requests may not reach ESPv2.   If they do, then debug logs from ESPv2 may help.
