### ISSUE TITLE
Upload file HTTP-GRPC transcoding

### ISSUE THREAD

**Issue by jjkoh95** [GoogleCloudPlatform/esp-v2#666]
Hello

What is the way to upload file here? Is sending JSON with base64 encoded binary the only way?

It would be more natural for client side to send `multipart/form-data` but it is not supported as commented here: https://github.com/GoogleCloudPlatform/esp-v2/issues/648

Please let me know what is the common/best practice for this issue.

Thanks

**Comment by qiwzhang** [comment]
Sorry, we don't know the common practice of using HTTP-gRPC JSON transcoder feature to update files.   Maybe other can chip in.

**Comment by timburks** [comment]
@jjkoh95 If you use HttpBody as your request message ([as illustrated here](https://github.com/googleapis/googleapis/blob/49dd2981f58dc88e8b9e76c726046584541287ed/google/api/httpbody.proto#L54)), then you can post arbitrary data to your transcoded RPC.

This is supported by [Envoy](https://github.com/envoyproxy/envoy/pull/10110) and possibly other proxies.

**Comment by SpencerC** [comment]
This worked for me. It would be nice if the main Cloud Endpoints documentation mentioned this.

**Comment by jjkoh95** [comment]
Thanks! I'm closing this to reduce noise for the repo
