### ISSUE TITLE
Help for --version mentions flag -c

### ISSUE THREAD

**Issue by sukolenvo** [GoogleCloudPlatform/esp-v2#679]
Help text for --version arg is
`Set the service config ID of the Endpoints service. If omitted and -c not specified, ESPv2 contacts the metadata to fetch the service config ID.`
Code: https://github.com/GoogleCloudPlatform/esp-v2/blob/master/docker/generic/start_proxy.py#L117

But there is no doc for `-c` param?

**Comment by qiwzhang** [comment]
It should be "-v". Will correct it.

**Comment by sukolenvo** [comment]
This flag `-c` is also mentioned in `--service` help:
`Set the name of the Endpoints service.  If omitted and -c not specified, ESPv2 contacts the metadata service to fetch the service name.`
https://github.com/GoogleCloudPlatform/esp-v2/blob/master/docker/generic/start_proxy.py#L108

**Comment by qiwzhang** [comment]
Thanks for info.
