### ISSUE TITLE
Http 415 when sending json to espv2 

### ISSUE THREAD

**Issue by gombasp** [GoogleCloudPlatform/esp-v2#693]
Hi, 

this is a continuation of the issue https://github.com/cloudendpoints/esp/issues/859.

@qiwzhang suggested that we should try ESPv2 instead of v1. However the same setup with espv2 produces a http 415 error code. For the setup and original code (very simple hello world grpc java example) see that repo please. 

ESP config i used:

sudo docker run \
    --detach \
    --name="esp_hello12" \
    --net="host" \
    --volume=/home/peti/projects/:/esp \
    --publish=8087 \
    gcr.io/endpoints-release/endpoints-runtime:2 \
    --service=helloservice.endpoints.playground-petergombas.cloud.goog \
    --rollout_strategy=managed \
    --http_port=8087 \
    --backend=grpc://localhost:8089 \
    --service_account_key=/esp/hello.json
    --non_gcp
    --enable_debug

Logs of the Java backend app:

[javalog.txt](https://github.com/GoogleCloudPlatform/esp-v2/files/8601711/javalog.txt)

Logs of the esp container:

[espv2.log](https://github.com/GoogleCloudPlatform/esp-v2/files/8601688/espv2.log)

As we have currently this issue, using espv2 is also not possible for us. 

Regards,

Peter

**Comment by qiwzhang** [comment]
It seem that ESPv2 grpc_transcoder is not configured properly so httpjson_to_grpc transcoding did not happen.

For grpc_transcoding,  ESPv2 and ESPv1 is different,  it gets the trancoding data from proto descriptor file instead of the service config file.  I looked at the data it got,  it is very small.  

In this [step](https://cloud.google.com/endpoints/docs/grpc/get-started-kubernetes-engine-espv2#deploy_configuration)
When running
```
gcloud endpoints services deploy api_descriptor.pb api_config.yaml
```
The `api_descriptor.pb` is generated from this [step](https://cloud.google.com/endpoints/docs/grpc/get-started-kubernetes-engine-espv2#endpoints_configure)  Specifically this command
```
python -m grpc_tools.protoc \
    --include_imports \
    --include_source_info \
    --proto_path=. \
    --descriptor_set_out=api_descriptor.pb \
    --python_out=generated_pb2 \
    --grpc_python_out=generated_pb2 \
    bookstore.proto
```

Could you try to rerun these steps?

You can verify if the new config by running
```
curl --fail -o "service.json" -H "Authorization: Bearer $(gcloud auth print-access-token)" \
  "https://servicemanagement.googleapis.com/v1/services/${SERVICE}/configs/${CONFIG_ID}?view=FULL"
```

Open the `service.json` to see if it has a bit "descriptor" field which is base64 encoded.

**Comment by gombasp** [comment]
Hi, 

i dont have too much luck with this example. We use a Maven plugin to generate the descriptor, please see below:

[api.zip](https://github.com/GoogleCloudPlatform/esp-v2/files/8762986/api.zip)
 
I added the file api_config.yaml like this:

type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: helloservice.endpoints.playground-petergombas.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Hello gRPC API

...and deployed the stuff like:

gcloud endpoints services deploy api.pb  api-config.yaml

When i started the espv2 container like above in my description it did start up however had connection problems (error 111). Note that i was using the same machine, same config, and so on, so i dont belive there should be a connection issue (no proxy or whatsover, it can reach the GCP). 

Any ideas what am i doing wrong?

Logs:

[log.log](https://github.com/GoogleCloudPlatform/esp-v2/files/8763044/log.log)

**Comment by nareddyt** [comment]
From your logs:

```
F0524 13:08:22.272898       7 server.go:54] fail to initialize config manager: fail to fetch and apply the startup service config, fail to initialize ServiceInfo, service config must have one api at least
```

Your service configuration did not specify the APIs aspect. Please see https://cloud.google.com/endpoints/docs/grpc/grpc-service-config, specifically the `apis:` section in the YAML file

**Comment by gombasp** [comment]
I managed to get the config working, however i see always following in Postman:

{
    "code": 503,
    "message": "upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111"
}

Logs:

D0524 16:45:43.627 46 external/envoy/source/common/http/conn_pool_base.cc:76] [46][pool]queueing stream due to no available connections
D0524 16:45:43.627 46 external/envoy/source/common/conn_pool/conn_pool_base.cc:268] [46][pool]trying to create new connection
D0524 16:45:43.627 46 external/envoy/source/common/conn_pool/conn_pool_base.cc:145] [46][pool]creating a new connection
D0524 16:45:43.628 46 external/envoy/source/common/http/http2/codec_impl.cc:1729] [46][http2][C13] updating connection-level initial window size to 268435456
D0524 16:45:43.628 46 external/envoy/source/common/network/connection_impl.h:89] [46][connection][C13] current connecting state: true
D0524 16:45:43.628 46 external/envoy/source/common/http/codec_client.cc:57] [46][client][C13] connecting
D0524 16:45:43.628 46 external/envoy/source/common/network/connection_impl.cc:912] [46][connection][C13] connecting to [::1]:8089
D0524 16:45:43.628 46 external/envoy/source/common/network/connection_impl.cc:931] [46][connection][C13] connection in progress
D0524 16:45:43.628 46 external/envoy/source/common/http/http1/conn_pool.cc:53] [46][pool][C12] response complete
D0524 16:45:43.628 46 external/envoy/source/common/conn_pool/conn_pool_base.cc:210] [46][pool][C12] destroying stream: 0 remaining
D0524 16:45:43.628 46 external/envoy/source/common/network/connection_impl.cc:695] [46][connection][C13] delayed connect error: 111
D0524 16:45:43.628 46 external/envoy/source/common/network/connection_impl.cc:250] [46][connection][C13] closing socket: 0
D0524 16:45:43.628 46 external/envoy/source/common/http/codec_client.cc:107] [46][client][C13] disconnect. resetting 0 pending requests
D0524 16:45:43.628 46 external/envoy/source/common/conn_pool/conn_pool_base.cc:439] [46][pool][C13] client disconnected, failure reason: delayed connect error: 111
D0524 16:45:43.628 46 external/envoy/source/common/router/router.cc:1170] [46][router][C5][S17830066558599306816] upstream reset: reset reason: connection failure, transport failure reason: delayed connect error: 111
D0524 16:45:43.628 46 external/envoy/source/common/conn_pool/conn_pool_base.cc:410] [46][pool]invoking idle callbacks - is_draining_for_deletion_=false
D0524 16:45:43.641 46 external/envoy/source/common/router/router.cc:1749] [46][router][C5][S17830066558599306816] performing retry
D0524 16:45:43.641 46 external/envoy/source/common/http/conn_pool_base.cc:76] [46][pool]queueing stream due to no available connections
D0524 16:45:43.641 46 external/envoy/source/common/conn_pool/conn_pool_base.cc:268] [46][pool]trying to create new connection
D0524 16:45:43.641 46 external/envoy/source/common/conn_pool/conn_pool_base.cc:145] [46][pool]creating a new connection
D0524 16:45:43.641 46 external/envoy/source/common/http/http2/codec_impl.cc:1729] [46][http2][C14] updating connection-level initial window size to 268435456
D0524 16:45:43.641 46 external/envoy/source/common/network/connection_impl.h:89] [46][connection][C14] current connecting state: true
D0524 16:45:43.641 46 external/envoy/source/common/http/codec_client.cc:57] [46][client][C14] connecting
D0524 16:45:43.641 46 external/envoy/source/common/network/connection_impl.cc:912] [46][connection][C14] connecting to [::1]:8089
D0524 16:45:43.641 46 external/envoy/source/common/network/connection_impl.cc:931] [46][connection][C14] connection in progress
D0524 16:45:43.641 46 external/envoy/source/common/network/connection_impl.cc:695] [46][connection][C14] delayed connect error: 111
D0524 16:45:43.642 46 external/envoy/source/common/network/connection_impl.cc:250] [46][connection][C14] closing socket: 0
D0524 16:45:43.642 46 external/envoy/source/common/http/codec_client.cc:107] [46][client][C14] disconnect. resetting 0 pending requests
D0524 16:45:43.642 46 external/envoy/source/common/conn_pool/conn_pool_base.cc:439] [46][pool][C14] client disconnected, failure reason: delayed connect error: 111
D0524 16:45:43.642 46 external/envoy/source/common/router/router.cc:1170] [46][router][C5][S17830066558599306816] upstream reset: reset reason: connection failure, transport failure reason: delayed connect error: 111
D0524 16:45:43.642 46 external/envoy/source/common/http/filter_manager.cc:961] [46][http][C5][S17830066558599306816] Sending local reply with details upstream_reset_before_response_started{connection_failure,delayed_connect_error:_111}

The backend is configured for the container like 

--backend=grpc://localhost:8089

Tried 127.0.0.1 as well, didnt work, request is not getting to the backend. Any suggestions?

**Comment by qiwzhang** [comment]
One thing I noticed that you were using  "--net=host".  In some platforms, it may not work.   You can try to create a separate network for containers,  here is a [instruction](https://cloud.google.com/endpoints/docs/openapi/get-started-compute-engine-docker#running_the_api_and_esp_in_a_docker_container) to create a `esp_net`

**Comment by gombasp** [comment]
Thanks @qiwzhang this was a good point. I managed to get it working without error, with latest java grpc lib. I think we will try to update to espv2.

**Comment by nareddyt** [comment]
Just FYI, here is the guide for updating: https://cloud.google.com/endpoints/docs/grpc/migrate-to-esp-v2
