### ISSUE TITLE
GCP API Gateway returning 500 Status Code

### ISSUE THREAD

**Issue by erhan-talarian** [GoogleCloudPlatform/esp-v2#694]
Hi, I'm performing load test to an App Engine Standard application behind GCP API Gateway with about 100 requests per second. The GW performs authentication with Google ID tokens. However, occasionally I get 500 errors when the tests run for a few hours. I only see the following log, no other logs are printed on the app engine side:

```
{
  "insertId": "...@ae",
  "jsonPayload": {
    "api_version": "v1",
    "service_agent": "ESPv2/2.35.0",
    "http_status_code": 500,
    "api_key_state": "NOT CHECKED",
    "api_method": "v1.....CreateEvents",
    "service_config_id": "...rqphuuma7",
    "timestamp": 1651482875.057296,
    "response_code_detail": "via_upstream",
    "producer_project_id": "...",
    "log_message": "v1.....CreateEvents is called",
    "api_name": "v1...._cloud_goog",
    "location": "us-central1"
  },
  "httpRequest": {
    "requestMethod": "POST",
    "requestUrl": "/api/v1/...",
    "requestSize": "2568",
    "status": 500,
    "responseSize": "652",
    "remoteIp": "....",
    "latency": "0.026s",
    "protocol": "http"
  },
  "resource": {
    "type": "api",
    "labels": {
      "location": "us-central1",
      "service": ".....cloud.goog",
      "method": "v1.....CreateEvents",
      "version": "v1",
      "project_id": "..."
    }
  },
  "timestamp": "2022-05-02T09:14:35.057295995Z",
  "severity": "ERROR",
  "logName": "....cloud.goog%2Fendpoints_log",
  "receiveTimestamp": "2022-05-02T09:14:37.153951207Z"
}
```

Here, especially the line below makes me think it maybe something related to API GW, since I tried to read the ESPv2 code a little bit it seems the state shouldn't be NOT CHECKED on normal conditions. 
`"api_key_state": "NOT CHECKED",`

Is this something related to ESPv2 or OAuth servers or is there secret error on application side? Any help would be much appriciated.
Thanks

**Comment by nareddyt** [comment]
In the log you posted above, I see this line:

```
    "response_code_detail": "via_upstream",
```

That means the issue is not in ESPv2, it is most likely from your backend application (or possibly a networking failure between ESPv2 and your backend). Please check your backend application logs to see if it returned 5xx errors

**Comment by nareddyt** [comment]
> Here, especially the line below makes me think it maybe something related to API GW, since I tried to read the ESPv2 code a little bit it seems the state shouldn't be NOT CHECKED on normal conditions

If you are using JWT for authentication and made API keys optional, then this is expected. `api_key_state` will only be checked if the client provided an API key

**Comment by erhan-talarian** [comment]
Thank you @nareddyt, in that case I'll check the application code more thoroughly.

**Comment by gdhananjay** [comment]
@nareddyt ,

How do you fixed this, I am getting similar issue. Could you help me on this.

**Comment by erhan-talarian** [comment]
Unfortunately I couldn't solve it, still get occasional 500 responses from API GW where there is no trace of the request on the App Engine backend. I decided to assume these are network errors and accept them.

**Comment by gdhananjay** [comment]
Oh,
Thanks for update, Even i am also about to accept them as networking error. But its bit hard to digest that GCP API gateway has these kind of error. Worked on AWS API gateway for a long time and it was smooth there. Here its different experience. 
Just in case i mentioned my problem in detail at :
https://stackoverflow.com/questions/73864927/how-to-resolve-gcp-api-gateway-error-500
