### ISSUE TITLE
ESPv2 doesn't sync with cloud endpoints configuration

### ISSUE THREAD

**Issue by gpkmr-genesys** [GoogleCloudPlatform/esp-v2#695]
Hello ! 

I am using `Cloud Endpoints` with `ESPv2`(2.35.0) hosted on `Cloud Run` as the front end for my `Cloud Functions` which serves as the backend. 

Whenever I update the API spec configuration YAML, it gets reflected in `Cloud Endpoints` but the `ESPv2` isn't picking up the change. I was stuck with this issue for days and then one day it worked some how (couldn't remember what I did).

Now again I have a requirement to update the YAML config where I notice the same issue.

How do I keep the `ESPv2` in sync with `Cloud Endpoints` ?

Scenario 1: Added a new `path` but received the below error
```{"code":404,"message":"The current request is not defined by this API."}```

Scenario 2: Changed the security definition of API key from `query` to `header` but the request was still accepting API key in `query`.

Scenario 3: Changed the existing `path` to a different name but still the request is working on old path which doesn't even exist in the current configuration. Upon using the new `path`, I get the below error.
```{"code":404,"message":"The current request is not defined by this API."}```

**Comment by nareddyt** [comment]
When using ESPv2 with Cloud Run, ESPv2 does not automatically pick up your Cloud Endpoints deployments because the configuration is built into the ESPv2 container. See the explanation here: https://cloud.google.com/endpoints/docs/openapi/set-up-cloud-run-espv2#configure_esp

**Comment by gpkmr-genesys** [comment]
Thanks for pointing out Teju. May be I overlooked that part. 
I re-built the image and deployed post which it works as expected.
