### ISSUE TITLE
Add ability to disable JWT audience checking in ESPv2

### ISSUE THREAD

**Issue by hravnaas** [GoogleCloudPlatform/esp-v2#706]
We have the need to at least temporarily disable the JWT "aud" claim check in ESPv2. My organization does not currently include the "aud" claim and it will be a slow process to get it added. Also, it'd just be a static string used in all tokens so it would provide very little value if any all all.

It seems that the JWT RFC calls out "aud" as optional. I've tried removing aud from the token and x-google-audiences from the OpenAPI doc, but I'm getting the "Audience not allowed" error still. Same error when using x-google-audiences: "", so setting it to an empty string. I can however get an empty string to work if I use x-google-audiences: "," but that still requires the aud claim to be present in the token, so "aud: ""

The JWT is only used internally in our org. It will not be used externally.

As mentioned above, with the RFC labeling "aud" as optional, it seems appropriate that ESPv2 would allow it to truly be optional. See statement [here](https://2rfc.net/7519#4.1.3:~:text=generally%20application%20specific.-,Use%20of%20this%20claim%20is%20OPTIONAL.,-4.1.4.%C2%A0%C2%A0%22exp).

Works:
`securityDefinitions:
  jwt_company:
    authorizationUrl: "https://www.company.com"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "company.com"
    x-google-jwks_uri: "https://storage.googleapis.com/somefile.json"
    x-google-audiences: "webserver.company.com"`

Fails (no x-google-audiences)
`securityDefinitions:
  jwt_company:
    authorizationUrl: "https://www.company.com"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "company.com"
    x-google-jwks_uri: "https://storage.googleapis.com/somefile.json"`

If aud is missing, the default service name seems to be added in today: https://github.com/GoogleCloudPlatform/esp-v2/blob/master/src/go/configgenerator/filterconfig/filter_gen_jwt_authn.go#L118

Perhaps a solution could be to allow both an empty string or no aud claim at all if this was provided: x-google-audiences: ""

**Comment by eduardchai** [comment]
Hi, I encounter the same issue. Is there any workaround for this so far?

**Comment by eduardchai** [comment]
Thank you @qiwzhang for the fix. Any ETA for the release? Thank you.

**Comment by eduardchai** [comment]
Hi @qiwzhang, is there any update on this? Thank you.
