### ISSUE TITLE
gcloud_build_image exposes access token locally

### ISSUE THREAD

**Issue by dseomn** [GoogleCloudPlatform/esp-v2#712]
https://github.com/GoogleCloudPlatform/esp-v2/blob/948edb9658114b99d95452d40e43dd4a67b4f544/docker/serverless/gcloud_build_image#L98 includes the output of `gcloud auth print-access-token` in the command line arguments to `curl`, and command line arguments are generally world-readable in linux. https://curl.se/docs/manpage.html#-H mentions an `@file` syntax which I'm guessing would avoid this problem.

**Comment by qiwzhang** [comment]
Not clear why it matters.  Will the stdout of the script be piped to a public site?  If so, can that individual user change the script to use @file.

**Comment by dseomn** [comment]
> Not clear why it matters.

It matters if anybody runs the script on a shared workstation or server. Probably not the most common use case, but the comment above the line I linked to seems wrong at the moment.

> Will the stdout of the script be piped to a public site?

I don't think anything is leaked on stdout, just in the command line arguments.

**Comment by dseomn** [comment]
Looking at this more, there's another place where this is not secure in a multi-user environment. This `cd` command looks like it's meant to ensure that the `service.json` and `Dockerfile` files are in a secure directory owned by the current user:

https://github.com/GoogleCloudPlatform/esp-v2/blob/948edb9658114b99d95452d40e43dd4a67b4f544/docker/serverless/gcloud_build_image#L95

But even with `set -eo pipefail`, if `mktemp` fails, the cd command won't do anything. E.g., running `bash -c 'set -eo pipefail; cd "$(false)"; pwd'` prints out the current directory with no error.
