### ISSUE TITLE
Secure API Gateway external url

### ISSUE THREAD

**Issue by darshan-willow** [GoogleCloudPlatform/esp-v2#731]
Hello,

I have setup my GCP infra connecting Cloud functions to API gateway to Cloud DNS with SSL certs. Which is exactly as the documentation says [here](https://cloud.google.com/api-gateway/docs/gateway-serverless-neg). I'm using **ESPv2/2.35.0**

The issue is after couple of days of setting up all this, we observed that there are https requests from unknown sources. Those paths are not even defined in our openspec docs. On further investigation, we got to know its some external bot hitting our https gateway url. How do I block such requests & only allow request coming from GCP Cloud DNS?

I thought of using Cloud Armor but it seems of no use as explained [here](https://stackoverflow.com/questions/67786747/how-to-restrict-access-to-api-gateway-from-external-gcp)

**Comment by nareddyt** [comment]
Unfortunately, API Gateway does not support this today. I suggest filing a feature request to the Cloud API Gateway team.

Is there any reason you are concerned about these external requests? ESPv2 / Cloud API Gateway is designed to reject these requests as early as possible, so it should not cause too much resource usage for your gateway.

**Comment by nareddyt** [comment]
If you do need more control over the networking path, you can always deploy ESPv2 yourself instead of using Cloud API Gateway. It requires more maintenance work on your end, but you get full control.

https://cloud.google.com/endpoints/docs/openapi/set-up-cloud-run-espv2

**Comment by darshan-willow** [comment]
Thanks @nareddyt . I do not want to manage ESPv2 by myself. I'll try to figure out something else.
