### ISSUE TITLE
Firebase app checks with API Gateway 

### ISSUE THREAD

**Issue by darshan-willow** [GoogleCloudPlatform/esp-v2#733]
Hello,
Is there a way to check validity of firebase app checks in API gateway or in Cloud Armor?
I want something like [this](https://firebase.blog/posts/2021/10/protecting-backends-with-app-check#verifying-app-check-tokens-in-apigee) .

**Comment by darshan-willow** [comment]
Thanks for the reply. Can you please explain **Firebase App Check under your project.**.  Is it like _https://firebaseappcheck.googleapis.com/${PROJECT_NUMBER}_ or is it the app bundle id?
Please write an example if you can or point me to any docs

**Comment by qiwzhang** [comment]
To be honest,  I don't know anything about `Firebase App Check`.  I just read you linked doc, and come up such suggestion.  
here is ESPv2 [doc](https://cloud.google.com/endpoints/docs/openapi/authenticating-users-firebase) for authentication.

For `x-google-issuer` field, it has to match the `iss` field in the token payload.  You can use [jwt.io](https://jwt.io/) to open your JWT token to find out its `iss` field.

I don't know anything bout "debug token" either.  If it has different issuer, jwks_uri,  you may need to define a new "securityDefinitions" for it.

**Comment by darshan-willow** [comment]
Thanks. I think we needs better documentation on this. Its hard to find any helpful articles on this topic

**Comment by nareddyt** [comment]
From the doc you linked, here is how Apigee is configured

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<VerifyJWT continueOnError="false" enabled="true"
        name="Firebase-App-Check-Token-Verification">
    <DisplayName>Firebase App Check Token Verification</DisplayName>
    <Algorithm>RS256</Algorithm>
    <Source>request.headers.X-Firebase-AppCheck</Source>
    <PublicKey>
       <JWKS uri="https://firebaseappcheck.googleapis.com/v1beta/jwks"/>
    </PublicKey>
    <!-- Be sure to use your real project number in <Issuer> and <Audience>. -->
    <Issuer>https://firebaseappcheck.googleapis.com/123456789</Issuer>
    <Audience>projects/123456789</Audience>
    <!-- You can also optionally check that the Subject matches your app's App Id. -->
    <Subject><!-- Insert your app's App ID here. --></Subject>
</VerifyJWT>
```

It has the same fields required for ESPv2 config: Issuer, Audience, Subject, and JWKS URI. You can place these values in ESPv2 `securityDefinitions` as @qiwzhang mentioned above.

**Comment by darshan-willow** [comment]
Thanks @nareddyt  for the reply. I'll try it out.

**Comment by unitario** [comment]
> From the doc you linked, here is how Apigee is configured
> 
> 
> 
> ```
> 
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> 
> <VerifyJWT continueOnError="false" enabled="true"
> 
>         name="Firebase-App-Check-Token-Verification">
> 
>     <DisplayName>Firebase App Check Token Verification</DisplayName>
> 
>     <Algorithm>RS256</Algorithm>
> 
>     <Source>request.headers.X-Firebase-AppCheck</Source>
> 
>     <PublicKey>
> 
>        <JWKS uri="https://firebaseappcheck.googleapis.com/v1beta/jwks"/>
> 
>     </PublicKey>
> 
>     
> 
>     <Issuer>https://firebaseappcheck.googleapis.com/123456789</Issuer>
> 
>     <Audience>projects/123456789</Audience>
> 
>     
> 
>     <Subject></Subject>
> 
> </VerifyJWT>
> 
> ```
> 
> 
> 
> It has the same fields required for ESPv2 config: Issuer, Audience, Subject, and JWKS URI. You can place these values in ESPv2 `securityDefinitions` as @qiwzhang mentioned above.

Apigee is great but cost $1500 (at minimum) per month. I learned that the hard way. Valid option a bank maybe but not for your average backend API.
