### ISSUE TITLE
Envoy v1.24.1

### ISSUE THREAD

**Issue by estensen** [GoogleCloudPlatform/esp-v2#776]
Not sure what happened to `v1.24`, but I think the version in the `WORKSPACE` file isn't pinning an actual version. Maybe a release should be pinned?

**Comment by orionHong** [comment]
Hi @estensen, the current Envoy version was updated to the tree HEAD on 2022-11-30 because we wanted to include `jwt_authn` changes. The current Envoy version is still ahead of `v1.24`. Since `v1.24` doesn't include critical security fixes, we decided not to pin this release.

**Comment by qiwzhang** [comment]
In general, we will like to pin to a envoy release.  But for some bug fixings, we need to get  this [change](https://github.com/envoyproxy/envoy/pull/24184),  we are taking the risk of pining to the tree HEAD on 2022-11-30.

Once that pr is in a envoy release, we will start to pin to official envoy release.

**Comment by estensen** [comment]
Thanks for responding!
