### ISSUE TITLE
Go version EOL

### ISSUE THREAD

**Issue by estensen** [GoogleCloudPlatform/esp-v2#778]
Go only supports the latest two versions.
The one pinned here, 1.15 ended support 16 Aug 2021
Is there any plan for upgrading?

**Comment by orionHong** [comment]
Thanks for checking this. Yes, 1.15 has indeed [ended support](https://endoflife.date/go). I think we should upgrade our golang verison to the latest `1.19`. We will add it to our planning, but we don't know the exact ETA at this point.
If there's critical security fixes from 1.15 version above, we can make it a high priority.

**Comment by estensen** [comment]
You can see [here](https://go.dev/doc/devel/release) all the security fixes that has been done after 1.15.15 released 2021-08-05 (latest 1.15)
Some security fixes (not sure about how critical they are), but not sure if they affect you

**Comment by nareddyt** [comment]
In our project, the golang code is only used to generate configs. Those code paths are not exposed to API clients. This means the impact of security bugs is minimal (as the code is only run by trusted users), so we did worry too much about updating it.

The C++ code that processes API client requests/responses is more critical, hence we are regularly updating it.

Agreed we should update golang though.
