### ISSUE TITLE
2.44.0 not latest release

### ISSUE THREAD

**Issue by estensen** [GoogleCloudPlatform/esp-v2#812]
Hi, I saw that [2.44.0](https://github.com/GoogleCloudPlatform/esp-v2/releases/tag/v2.44.0) was recently released, but the latest tag doesn't point to it yet. Is it not yet the recommended?

**Comment by nareddyt** [comment]
Hi @estensen,

We don't tag images with `latest` because that would cause a breaking change between SemVer major versions.

You can use gcr.io/endpoints-release/endpoints-runtime:2 instead. This will always point to the latest `v2.x.x` image. Currently it does point to `v2.44.0`.
