### ISSUE TITLE
Cloud Run Deployment Failure

### ISSUE THREAD

**Issue by kamalakarrao** [GoogleCloudPlatform/esp-v2#839]
During the deployment of the container image using the following command:

`gcloud run deploy service-name --image="gcr.io/project-id/endpoints-runtime-serverless:2.45.0-service-url-2023-07-17r1" --allow-unauthenticated --platform managed --project project-id
`

We encountered the following error message:

Revision 'service-name-00083-yaw' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8000 environment variable.

**Comment by kamalakarrao** [comment]
**RCA:** Upon investigation, we discovered that the issue stemmed from using the default version of the container image, specifically version 2.45.0, during the deployment process.

**Solution:** To address this deployment issue, we recommend using a different version of the container image during the deployment process. By explicitly specifying version 2.44.0 with the "-v" flag in the "gcloud_build_image" command, as shown below:

`./gcloud_build_image -s service-url -c 2023-07-19r0 -p project-id -v 2.44.0
`

By default, If we don't specify -v version then it will pick latest version.

The latest version got updated to 2.45.0 after July 12th which possible causing the issue.

By This Solution, The deployment should proceed successfully

@rjerrems Thanks for contributing to this repo.
 However, I noticed that above issue in the latest version 2.45.0 To ensure all users can benefit from the improvements, I suggest addressing this problem in the latest version as well.

Thanks

**Comment by nareddyt** [comment]
Hi @kamalakarrao , I was not able to reproduce this issue.

Could you provide the ESPv2 application logs from Cloud Run when you use image `gcr.io/project-id/endpoints-runtime-serverless:2.45.0-service-url-2023-07-17r1`?

Follow this guide, try to find any WARNING or ERROR logs: https://cloud.google.com/run/docs/logging

**Comment by nareddyt** [comment]
@nickjosph this is very helpful. Can you share the output of this command and email it to me at nareddyt@google.com ?

```shell
gcloud endpoints configs describe "${CONFIG_ID}" \
  --project="${PROJECT}" \
  --service="${SERVICE}" \
  --format=json \
  > service.json
```

**Comment by pablobenitogonzalez** [comment]
Hello @nareddyt,
Same problem here.

Even right now, generating the image with version 2.44 and the same OpenAPI yaml, after deploying, it is impossible to find the endpoints. The Cloud Run returns a 404 Not Found ("_The current request is not defined by this API._").

**Comment by nareddyt** [comment]
@pablobenitogonzalez that sounds like a separate issue. Feel free to file a new issue on Github, and please include any ESPv2 application logs (with `--enable_debug` flag) if you have them

**Comment by nareddyt** [comment]
https://github.com/GoogleCloudPlatform/esp-v2/pull/850 should resolve this issue. We'll make a new ESPv2 release next week with this change.
