### ISSUE TITLE
 503 or 504 error case 

### ISSUE THREAD

**Issue by ben-swit** [GoogleCloudPlatform/esp-v2#849]
I am operating in a Kubernetes environment using an API server and ESP in a sidecar 

but today when i open the log exploer i saw this many message

UNAVAILABLE:Calling Google Service Control API failed with: 503 and body

\[70][filter]Failed to call report, error: UNAVAILABLE:Calling Google Service Control API failed with: 503 and body: upstream connect error or disconnect/reset before headers. reset reason: connection failure, str body: upstream connect error or disconnect/reset before headers. reset reason: connection failure

44][filter]Failed to call report, error: UNAVAILABLE:Calling Google Service Control API failed with: 504 and body: upstream request timeout, str body: upstream request timeout

I want to know if this is an internal error of ESP or another case 

![스크린샷 2023-08-31 오후 6 03 21](https://github.com/GoogleCloudPlatform/esp-v2/assets/68882242/af8b366d-c979-4493-b75e-b9a2290b5bf6)

**Comment by nareddyt** [comment]
These errors are from ESPv2.

Are these errors still occuring? Most likely these were temporary errors, either cause by broken cloud networking in that particular region/zone, overloaded Google Service Control API, etc.

ESPv2 fails open by default on such networking errors, meaning your API clients do not see the errors and ESPv2 still continues serving requests with degraded functionality.

You may want to check the [Cloud Endpoints access logs](https://cloud.google.com/endpoints/docs/openapi/ref-endpoints-logs) to understand which API client requests were affected by this temporary error.

**Comment by ben-swit** [comment]
@nareddyt  interruptions are still occurring, and there was another interruption of about 1 minute today, which we perceived as an outage situation. Is there any way to confirm this other than logs?  
we use gcr.io/endpoints-release/endpoints-runtime:2 image gcr.io/endpoints-release/endpoints-runtime@sha256:1ffd99d09d89722cfbc9157eeec171a5566009c9fa36f081bbe8a462e9457225

**Comment by ben-swit** [comment]
it is same issue https://github.com/GoogleCloudPlatform/esp-v2/issues/694
