### ISSUE TITLE
Question about deprecation for gcr.io/endpoints-release/endpoints-runtime:2, Container Registry

### ISSUE THREAD

**Issue by gongmax** [GoogleCloudPlatform/esp-v2#893]
According to https://cloud.google.com/container-registry/docs/release-notes#May_15_2023, it states that gcr.io/endpoints-release/endpoints-runtime are deprecated in Container Registry and users are required to migrate to Artifact Registry.

Do you have any plans to migration to Artifact Registry?

Thank you all for your contributing.

**Comment by siqidong** [comment]
Thank you for your question.
Yes my team plans to migrate endpoints runtime repos from Container Registry to Artifact Registry before March 2025.

**Comment by LCLMLE** [comment]
Hi @siqidong , since the GCR image will be deprecated next month and you mentioned that you will target completing migration to Artifact Registry by March next year, I'm wondering if there is a transit solution for us between May 2024 and Mar 2025? Thanks.

**Comment by siqidong** [comment]
Hi @LCLMLE , IIRC GCR will keep serving existing traffic by directing traffic to Artifact Registry, which should not affect the current users.

**Comment by LCLMLE** [comment]
@siqidong Thanks, let me just further confirm it. We currently use "gcr.io/endpoints-release/endpoints-runtime:2", so we can still keep using this path even it is deprecated next month? And we don't need to do manually do any actions like migrating it to AR, right? Thanks.

**Comment by siqidong** [comment]
Yes, if your projects currently have the required permissions and are pulling the image from "gcr.io/endpoints-release/endpoints-runtime:2" without any issue, this deprecation should not impact you.

The shutdown of GCR starts March 2025 and we will finish the migration before that time, will keep you updated if there is any action items from client side. Thanks!
