### ISSUE TITLE
⚠️ Docker registry is gone

### ISSUE THREAD

**Issue by RTae** [GoogleCloudPlatform/esp-v2#924]
I think your docker registry is gone. I cannot pull ESP image from this repro **gcr.io/endpoints-release/endpoints-runtime**

<img width="810" alt="Screen Shot 2567-08-28 at 01 06 09" src="https://github.com/user-attachments/assets/351b0976-0ba8-4fb1-9513-ef2ab5a1a179">

<img width="693" alt="Screen Shot 2567-08-28 at 01 08 26" src="https://github.com/user-attachments/assets/c922abdb-c252-4006-8d7e-761235a58993">

**Comment by shuoyang2016** [comment]
There's an incident. Devs are on it.

**Comment by shuoyang2016** [comment]
The issue is mitigated. Let us know if you still see the problem. Thanks.

**Comment by mike-serchenia** [comment]
> The issue is mitigated. Let us know if you still see the problem. Thanks.

seems to be fixed

**Comment by SpringMT** [comment]
Has it come back?

**Comment by shuoyang2016** [comment]
We started the migration again and now 10% traffic is redirecting to new repo. Did you see some flakiness?

**Comment by SpringMT** [comment]
Currently, we are encountering an error with gcr.io/endpoints-release/endpoints-runtime-serverless:2. The error message is: unexpected status code [manifests 2]: 403 Forbidden.

**Comment by garysferrao** [comment]
i get the same error and i cannot access the repository.
<img width="732" alt="Screenshot 2024-09-12 at 11 00 10" src="https://github.com/user-attachments/assets/7b3e88ea-5b9e-40a5-ae37-992cc0a94882">

is there a web page that lists this issue instead of reporting on GitHub?
