### ISSUE TITLE
Troubleshooting ESPv2 Container Deployment and Image Naming Issues

### ISSUE THREAD

**Issue by dangnam739** [GoogleCloudPlatform/esp-v2#942]
We have followed the [ESPv2 App Engine](https://cloud.google.com/endpoints/docs/openapi/set-up-app-engine-standard-environment-espv2) documentation steps to build and deploy new containers and services. The images are stored in the Container Registry. 

However, we've noticed that the newly created images have different names than previous ones. The format of the image name is correct according to the documentation as `<ESP_VERSION>-<CLOUD_RUN_HOSTNAME>-<CONFIG_ID>`, but recently the image names have included the prefix `no-new-use-public-image` (as shown in the screenshot below).

![Screenshot 2024-11-28 at 10 25 15](https://github.com/user-attachments/assets/2e470ab2-52d8-48a5-932b-bc47c1640c6a)

Additionally, during the "Deploying the ESPv2 container" step using the `gcloud run deploy` command, we encounter an error indicating that the images cannot be accessed, even though the image url is correctly and the necessary permissions have been granted.
```log
Cloud Run API check failed. Requests will be rejected after January 2025 hard enforcement deadline. User does not have access to image gcr.io/<project_id>/endpoints-runtime-serverless:<image_name>
```

Why did the image name cha
nge like that and is this name change causing an error when deploying the espv2 container on cloud run?
I would appreciate your explanation and any solutions you can provide.
Thank you.

**Comment by azoom-l-x-duy** [comment]
@dangnam739 
Hi, I got the same issue recent days.
I think the cause is GCP team don't want we to use ESPv2 that with version that less than v2.51.0 anymore, so they push tag prefix **no**-new-**use-public**.

Please try with [v2.51.0](https://github.com/GoogleCloudPlatform/esp-v2/releases/tag/v2.51.0)
```
ESP_TAG="2.51.0"
```


<img width="1038" alt="Screenshot 2024-11-28 at 17 00 44" src="https://github.com/user-attachments/assets/027db998-90b8-4320-9d6d-b6b19b542868">

**Comment by dangnam739** [comment]
@azoom-l-x-duy a
Thank you for your suggestion.
Specifying the latest version of ESP indeed prevents the creation of the image with the "no-new-use-public-image" prefix. However, when deploying Cloud Run, I still encounter an error indicating that I can't access the image, even with the new image without prefix.
Have you encountered a similar error? If so, I would appreciate any solutions or guidance you could provide.

**Comment by azoom-l-x-duy** [comment]
@dangnam739 
> when deploying Cloud Run

I have successfully redeployed espv2 to cloudrun after updating the version to 2.51.0 already.

>  I still encounter an error indicating that I can't access the image, even with the new image without prefix.

Your cloudrun service and container registry for storing image after build in the same project right? and you granted necessary permissions already.
Have you success deploy espv2 to cloudrun before and doesn't change any config? I think yes.

> Requests will be rejected after January 2025 hard enforcement deadline

Maybe your problem now is not from espv2 anymore, please take a look at [Clodurun release notes] (https://cloud.google.com/run/docs/release-notes#October_21_2024) related to organization policies.

<img width="914" alt="Screenshot 2024-11-29 at 10 18 52" src="https://github.com/user-attachments/assets/d911c5ce-aa85-41ef-a6f5-32adb7cb67d4">

Please check right permission with your image after build is stored in **Artifact Registry** or **Container Registry**.

**Comment by dangnam739** [comment]
@azoom-l-x-duy 
> Your cloudrun service and container registry for storing image after build in the same project right? and you granted necessary permissions already.

In my project, the circle-ci deploy cloud run by command `gcloud run deploy esp --image="$newimage" --allow-unauthenticated --platform managed --project=$DEV_GOOGLE_PROJECT_ID --region=$REGION`. The CI service account is granted the roles of Cloud Run Admin, Storage Admin, Service Account User, and Artifact Registry Reader. Following [this](https://cloud.google.com/run/docs/deploying#required_roles), it seems that the necessary permissions are granted, right?


> Have you success deploy espv2 to cloudrun before and doesn't change any config? I think yes.

Yes, the cloud run deployment was successful until 29/10/2024 and there is no change in the cloud run's config.

**Comment by TheCloudGate** [comment]
@dangnam739 

I encountered the same issue and resolved it by storing the new images in an Artifact Registry folder instead of the Container Registry. After making this change, I was able to deploy new version of our Cloud Run services without encountering any permission-related errors.

**Comment by dangnam739** [comment]
@TheCloudGate 
Hi, I also deployed a new image to Artifact Registry instead of Container Registry this afternoon, and subsequent deployment to Cloud Run went smoothly, with no access errors as before. 
[Container Registry was deprecated](https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation) on May 15, 2024, so there may have been some recent changes on the Google Cloud side regarding access to images stored in the Container Registry.

**Comment by azoom-l-x-duy** [comment]
@dangnam739 
Hi, have you resolved your problem?

Today when I check into cloud revision log, I see the same issue as you got before, but it seems like a notice and not ban your cloudrun deploy for now.

> User does not have access to image gcr.io/<project_id>/endpoints-runtime-serverless:<image_name>

This issue because you use an image from Container Registry (I also use both Container Registry and Artifact Registry), but my endpoints service is CR for now.

You said that you already `「deployed a new image to Artifact Registry instead of Container Registry」` but your log said that your image from `gcr.io/<project_id>/...` instead of `pkg.dev`.
Artifact Registry uses new hosts under pkg.dev rather than gcr.io.
I you should check your build and deploy step again.

Even though I get the same error message, the cloudrun revision for my endpoints is still replaced and routing traffic successfully. (Tested with some openapi spec changed and deployed)

<img width="893" alt="Screenshot 2024-12-02 at 12 00 18" src="https://github.com/user-attachments/assets/12e8b5aa-7fc8-4ad6-b867-78c1814aad5e">

**Comment by dangnam739** [comment]
@azoom-l-x-duy 
I have resolved this issue already.

> Today when I check into cloud revision log, I see the same issue as you got before, but it seems like a notice and not ban your cloudrun deploy for now.

Yes, this error does not ban cloud run deployment. But, it affects the tracking log of your web api. It can be seen when you look at the log of the app engine version, no log is recorded if cloud-run service occurs this error.

>You said that you already 「deployed a new image to Artifact Registry instead of Container Registry」 but your log said that your image from gcr.io/<project_id>/... instead of pkg.dev.
Artifact Registry uses new hosts under pkg.dev rather than gcr.io.

What you said is correct, GAR uses the `pkg.dev` domain so the image URL may be changed to `pkg.dev`. In my original question, the error message contains `gcr.io` because the image was uploaded to GCR.

In addition, to prepare for GCR to be suspended, I think you should also migrate images from GCR to GAR. When transiting images from GCR to GAR, you can keep the `gcr.io` domain in GAR as in this [guide](https://cloud.google.com/artifact-registry/docs/transition/auto-migrate-gcr-ar). You can choose to continue using the `gcr.io` or `pkg.dev` domain for newly uploaded images.

**Comment by azoom-l-x-duy** [comment]
@dangnam739 
I'm happy to heard that you resolved this issue.

Thank you about reminding migrate to GAR before the deadline, I'm in progress to do that by one of two ways below.

`#1`. [auto-migrate-gcr-ar](https://cloud.google.com/artifact-registry/docs/transition/auto-migrate-gcr-ar) with gcp cli command
`#2`. Build new images and push to new target in GAR.

`#1` also copy existing images from GCR to GAR that maybe doesn't need anymore so I depend on my project purpose case by case 👷

**Comment by dangnam739** [comment]
@azoom-l-x-duy 
Thank you for the update. It's great to hear that you're already in the process of migrating to GAR. Both methods you mentioned are valid, and it's wise to consider the specific needs of your project when deciding whether to migrate existing images or build new ones.
In my project, I'm progressing on the way 1 for backup purposes and creating a new domain in GAR for the future upload image to separate with previous image from GCR.
